# 전처리 연습 (Tokenize, Cleansing & Normalization, Stemming & Lemmatization)

1. 데이터셋(corpus)을 찾는다. (만들어진 데이터 셋, 크롤링, ...)
2. 전처리
    2-1. 의미가 있는 단어 단위로 vocabulary
    2-2. corpus -> 토큰화 + 전처리 -> 문장

1. 데이터셋(corpus)을 찾는다. (만들어진 데이터셋, 크롤링, ...)
    - **🐿️ 이어지는 실습에 쓸 수 있을 법한 데이터 찾기 Tip**
    - 여러 문장으로 이루어진 데이터셋이라면 일단 good
        - 리뷰 등 이어지지 않는 짧은 문장 여러 건 ok
        - 소설 등 이어지는 긴 문장 여러 건 ok
    - 대화형 데이터셋도 good
        - QnA로 구성되어 있는 corpus도 좋고
        - 일반적인 대화로 구성되어 있는 corpus도 좋아요~
    - 특정 도메인에 대한 정보를 담고 있는 데이터셋도 good
2. 전처리를 해본다.
    - 텍스트 자체를 깔끔하게 만드는 것까지만

In [ ]:
# !pip install selenium

In [7]:
# !pip install webdriver-manager

In [ ]:
import time
from selenium import webdriver
from selenium.webdriver import Chrome
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

# driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
driver = webdriver.Chrome() 

youtube_video_url = "https://www.youtube.com/watch?v=7AWHmCQq35Q"
data = []

try:
    driver.get(youtube_video_url)
    wait = WebDriverWait(driver, 20)

    driver.find_element(By.TAG_NAME, 'body').send_keys(Keys.PAGE_DOWN)
    time.sleep(3)


    for i in range(100): 
        driver.find_element(By.TAG_NAME, 'body').send_keys(Keys.END)
        time.sleep(2)
        print(f'{i}페이지 탐색 완료')


    comments = wait.until(EC.presence_of_all_elements_located((By.CSS_SELECTOR, "#content-text")))

    for comment in comments:
        data.append(comment.text)
        
    print(f"총 {len(data)}개의 댓글")

finally:
    time.sleep(5)
    driver.quit()

0페이지 탐색 완료
1페이지 탐색 완료
2페이지 탐색 완료
3페이지 탐색 완료
4페이지 탐색 완료
5페이지 탐색 완료
6페이지 탐색 완료
7페이지 탐색 완료
8페이지 탐색 완료
9페이지 탐색 완료
10페이지 탐색 완료
11페이지 탐색 완료
12페이지 탐색 완료
13페이지 탐색 완료
14페이지 탐색 완료
15페이지 탐색 완료
16페이지 탐색 완료
17페이지 탐색 완료
18페이지 탐색 완료
19페이지 탐색 완료
20페이지 탐색 완료
21페이지 탐색 완료
22페이지 탐색 완료
23페이지 탐색 완료
24페이지 탐색 완료
25페이지 탐색 완료
26페이지 탐색 완료
27페이지 탐색 완료
28페이지 탐색 완료
29페이지 탐색 완료
30페이지 탐색 완료
31페이지 탐색 완료
32페이지 탐색 완료
33페이지 탐색 완료
34페이지 탐색 완료
35페이지 탐색 완료
36페이지 탐색 완료
37페이지 탐색 완료
38페이지 탐색 완료
39페이지 탐색 완료
40페이지 탐색 완료
41페이지 탐색 완료
42페이지 탐색 완료
43페이지 탐색 완료
44페이지 탐색 완료
45페이지 탐색 완료
46페이지 탐색 완료
47페이지 탐색 완료
48페이지 탐색 완료
49페이지 탐색 완료
50페이지 탐색 완료
51페이지 탐색 완료
52페이지 탐색 완료
53페이지 탐색 완료
54페이지 탐색 완료
55페이지 탐색 완료
56페이지 탐색 완료
57페이지 탐색 완료
58페이지 탐색 완료
59페이지 탐색 완료
60페이지 탐색 완료
61페이지 탐색 완료
62페이지 탐색 완료
63페이지 탐색 완료
64페이지 탐색 완료
65페이지 탐색 완료
66페이지 탐색 완료
67페이지 탐색 완료
68페이지 탐색 완료
69페이지 탐색 완료
70페이지 탐색 완료
71페이지 탐색 완료
72페이지 탐색 완료
73페이지 탐색 완료
74페이지 탐색 완료
75페이지 탐색 완료
76페이지 탐색 완료
77페이지 탐색 완료
78페이지 탐색 완료
79페이지 탐색 완료
80페이지 탐색 완료
81페이지 탐색 완료
82페이지 탐색 완료
83페이지 탐색 완료
84페이지 탐색 완료
85페이지 탐색 완료
86페이지 탐색 완료
87페이지 탐색 완료
88페이지 탐색 완료
89페이지 탐색 완료
90페이지 탐색 완료
91페이지 탐색 완료
92페이지 탐색 완료
93페이지 탐색 완료
94페이지 탐색 완료
95페이지 탐색 완료
96페이지 탐색 완료
97페이지 탐색 완료
98페이지 탐색 완료
99페이지 탐색 완료
총 1146개의 댓글을 수집했습니다.

In [8]:
data

['공인회계사 최종합격자와 카이스트 컴공이 취업을 걱정해야 하는 세상...',
 '카이스트  물리학과  컴공 복수전공한 분이  AI때문에 취업이  쉽지않다고 하면  다른  대학출신은  얼마나  힘들지  상상이  안가네요.',
 '다들 먼 이야기라고 생각하겠지만\n지금 당장 tv만 봐도 재연을 대역배우가 아닌 그냥 ai영상으로 다 대체하고 있음;;\n벌써 시작하고 있잖음',
 '회계사가 대체될 정도면 이미 컴퓨터 앉아서 하는 대부분의 사무직은 곧 전멸하겠네',
 '앞으로 살아가야 할 내 자식들, 청년들 미래가 너무 불투명하고 안타깝고 서글프다...',
 '5년에 걸쳐서 버스안내양 합격했는데... 자동문 나와버린 꼴;;;',
 '숫자다루는 업무는 특히 ai가  잘할듯',
 '개발잔데요.. 그냥 기도합니다\n제발 이 기술이 모두의 공리와 행복을 증진시키는 방향으로 발전되기를.. 개인이 발버둥쳐서 대비하거나 바꿀 수 있는 수준이 아닙니다. 그야말로 대혁명.. 불의 발견, 전기의 발견에 버금가거나 그 이상으로 느껴집니다.',
 '정말 어려운 시험인데 그걸 따고도 백수라니....너무 안타깝다',
 '유튜브에 회계사 합격하고 가족들에게 울면서 전화하는 합격자 있었는데... 이영상보니 진짜  허무하네요',
 '문과 사무직인데, 불과 5년전만해도 주변에 퇴사하고 코딩 교육받아서 개발자로 재취업하는 사람들 은근 있었는데 시장이 이렇게 와장창 무너질줄이야...',
 '합격증 받자마자 저렇게 비닐에 싸서 보관할정도면 그만큼 진심이고, 그만큼 인생에서 중요한 순간이라고 생각했을텐데…\n진짜 타이밍 안좋으신 듯\n인공지능이 충분히 다 일을 대신할 수 있을 지경까지 올걸 누가 알았을까',
 '공인회계사 합격하려고 몇년을 시간을 갈아넣어서 자격증을 땃을텐데.. 세상이 이렇게 변해버렸으니. 너무 슬프다.',
 'It대 다니고있는데 교수님 왈 컴공 개발자 구인구직이 인문학과보다 더 떨어진 상황이라네요. 갑자기 이렇게 세상이 변할줄 누가 알았을까요…',
 '회계사라고 하면 와~~하고 알아 주던 직업군이었는데ㅠ\n너무 안타깝네요',
 '근데 내가보이엔 지금은 스펙이고 나발이고간에 취업시장자체가 너무좁음... 그냥 취업이 힘든게 맞음',
 '시대를 예측하지 못한것보다 시대가 너무 빠른거 아니냥',
 '이미 전망없는 직업에 청춘 바치지말고 편견을 버리고 다양한 직업에 도전해야함',
 '회사의 경리회계 더존 프로그램 처음 나왔을때 경리부 직원들 많이 짤렸지.. 분개,기장을 더존프로그램이 해버리니... 과장급이상 해야 할일을 신입여사원이 다할수 있는 일이 된 획기적인 사건이었지',
 '뭐해먹고살라고 진짜ㅜ먹고살기힘드네',
 '본질은 컴퓨터 앞에 앉아서 하는 일들은 다 대체된다는거다',
 '제일 먼저 없어져도 무방하고 오히려 AI로 대체되길 바라는 직업이 대한민국의 판사들입니다.',
 '이 영상중간에도 제미나이 광고나오네ㅋㅋ 시대의흐름이다ㅜ',
 '인터뷰 찍는 카메라에도 Ai 탑재됨 ㅋㅋ 전문 카메라맨도 사라짐',
 '필요없는 공부를 하고 너무 많은 인원을 뽑아서',
 '옛날부터 은행원, 회계사,세무사,변호사등.. 없어질직업이라고 했음. 점점 희미해져가고 있네. 정말로.',
 '회계사 세무사는 진짜 이제 답이 없다..',
 '세상변화 속도가 너무빠르다.',
 '앞으로는 주니어에 이어 중간급도 사라질듯',
 '헐 심하긴 하구나. 추적 60분까지 나올정도니',
 '노력이 배신하는시대가 왔구나!!!',
 'AI를 검수할 고인물 능력자 빼고는 신규와 중간관리자는 안뽑아요.\n미국은 피바람불고있음',
 '병찬이 자기는 이제 짬도 있고 안전하니까 사다리 걷어차려는거 보소ㅋㅣㄱ',
 '과거는 자의에 의한 취업 유예였다면 지금은 타의에 의한 취업 절벽이죠',
 '진짜  서글픈 세상이네요\n힘든  시험인데 ㅠㅠ \n얼마나   허망할까요 ㅠㅠ',
 '참 서글프다 \n5년 동안 얼마나 노력해을까',
 '회계는 더 안타까운게 ai적용시키기 더 간단함.',
 '10년전쯤 미래에 ai로 대체될 직업이라는 리스트 보고 친구랑 이야기한적 있었는데 그게 진짜 현실이됐네..',
 '출장다니면서 서버 구축하고 부품 고쳐주는 유지보수 엔지니어 해야 입에 풀칠은 할겁니다...',
 '세상이 진짜 빠르게 변해가네..',
 '재무관리 경영학 경제학 시험을 왜 보냐. 쓸데없이 난이도 높여 수험생 괴롭힌 시험이 CPA 시험임. 본질 가치 대비 고평가 되어온 자격증.',
 '모든 사무직종에서.  AI 때문에 어시가 하던 일을 더 빨리, 더 깔끔하게 처리해준다.  실무자 혹은 결정권자 입장에서 어시가 필요 없어짐..',
 '참 인생 알 수 없는 게, 얼마 전 용산에서 밥 먹는데, 옆 테이블에 삼일 회계사들이 회식중이더라. 아모레 사옥에 삼일이 있지 아마. 딱 저 나이대 친구들이야. 젊더라고. 그들도 입사한 지 얼마 안 됐을 거 같아. 길어야 1~2년.  몇 년 전에 합격한 이들과 지금 합격한 이들 인생의 향방이 이렇게 달라진다. 앞으로 그게 더 심해질 것이고, 그 회식에 참석한 친구들도 앞으로 어떻게 될 지 모르는 거지. 나도 그래서 살아남기 위해서 정말 고민이 많고 분투 중이다.',
 '좌우국회의원들 모두 AI로\n대체되길..',
 '4:51 아마 많은 취준생들이 비슷할 거라고 봄.. 너무 밝게 얘기하셔서 더 슬프네요',
 '창근 님 대표님이 칭찬해 주니까 허리 펴는 모습 귀엽다.',
 '협회는 지금 자격증 장사 중',
 '원래 대전환기에는 당연하게 발생하는 일이잖아. 스마트폰 나오니 삐삐공장 파산하고...ai나오니 전문직 필요없어지고..세상이 변하는데 어쩔 수 있나',
 'AI때문에 신입들이 취업이 어렵다고 아우성쳐도 정작들어와서 AI없으면 일을 못함... 더 심해지는게 요즘엔 AI로 레포트내던 친구들이 들어온다는점',
 'ai날이 갈수록 미쳤다 3초면 끝나는세상',
 '공인회계사..예전 2009년 쯤 학교 교수님이 없어질 직종이라든데..당시만해도 엄청 유망해보였는데 이게 지금 실화가 되네..',
 '쓸모없는 변호사들도 다 필요없음.\n소장도 알아서 써주는데 변호사 소장 대충쓰고서 6-800이상 받아감.',
 '회계사 세무사\n법무사도 이제 끝나감\n\n법무사 ai로 신고서식\n간펀하게 보급되어져야함\n\n비싼 수수료 자기로 처리해야함',
 '우리나라같이 노동경직성있는 국가에서는 안그래도 고용과 해고가 힘든데.  리스크가 큰사실을 외면하고있음.',
 '가장 비싼 일자리일수록 ai대체될수밖에 ',
 '사무직 웹디자인 컴퓨터로 할수있는 직업들 은행원등 다 없어지고 있는 직종',
 '컴퓨터 앞에서 일하는 사람들은.................다 위기 입니다.',
 '아프지만 말아요. 우선!',
 '열심히 공부해서 어렵게딴 자격증으로 평생 벌어먹을 수 잇던 직장들이 2년 사이에 우르르 무너지네',
 '현실을 빨리 수긍하는 게 생존에 유리함. 내가 여태 열심히 해왔다고 현실은 인정해주지 않음. 이걸 빨리 적응하지 못 하면 죽음 뿐',
 '부모는 공부만 시킬게아니라\n세상을 멀리 내다보는눈을 키워주는게 중요하다',
 '회계사 합격할 정도 인재면 다른 걸 해도 잘 함.. 힘내시오.',
 '변호사 ,판사도 AI 가해야한다.',
 '앞으로 앉아서 컴퓨터 두드리는 직종은 많이 사라진다고 봐야지',
 '우리 부부는 어떻게든 살아남을 수는 있을거 같은데, 이제 초딩인 우리 아이는 뭘 대비시켜줘야 할지ㅠㅠ 정말 너무 빠르게 변해서 모두가 막막한 사회다',
 '출산 장려하지마라. 내 자식 장래가 암울하다. 대책을 마련하고 장려를 하든해야지',
 '회계사 미지정은 이미 역사가 길다 700명대 시대에도 있었다 잠깐 호황으로 착시현상이 있었을뿐',
 '회계사면 진짜 어마무시하게 공부하신 분일텐데..',
 '해외는 인턴들은 무급이나 되게 적게 받고 일시킨다고함..',
 '카이스트에서 복전한 사람이 다 떨어지고 취업캠프를 가서 다시 5군데 중 한군데... 스타트업인데도 진짜 빡세네..',
 '전문직이 저 정도니 일반 대졸자들은 어떻다는 얘기인지…',
 '무서운 세상이야...',
 '기자 부터 ai대체 하자\n판사 다 없애라\n 국민의 삶에 소금 뿌린 자',
 '진짜 맨나중으로가면 진짜 아예 인간 을 채용하지 않을듯',
 '개발자 직군이 진짜 ㅈㄴ 타격입은거지 몇년전에 코딩 붐일어서 단기속성으로 몇개월 공부해서 프로그래머로 취업한 사람들이 지금 연차 조금 쌓였을텐데 거기까지가 딱 마지노선인거같음 그 이후 신입분들은 ai땜에 취업시장 발도 못붙임',
 '그니까 시니어끼리 시다를 주니어가 아니라 ai한테 시키는거잖아',
 '진짜 심각하다 ㄷㄷㄷ',
 '화이트칼라는 AI로 인한 대체가 걱정이고...블루칼라는 중국발 저가 덤핑 공세 때문에 문제고...쉽지 않다 정말',
 '회계사를 필요이상으로 많이뽑았고\n회계사도 학벌을 봅니다. 지잡대 회계사들 안뽑아요. 수요보다 공급이 많은데 뭐하러 뽑습니까\n그리고 AI로 프로그램 돌리고 현재 근무하는 직원들에게 좀더 전문적으로 일을맏기고 좀더 연봉을 지급합니다. 전문화 되어있으니~\n그래서 신입을 안뽑아요. 뽑을 이유도없고\n\n벌률상담도 챗GPT나 제미나이 돌리면 자세하게 알려줘요\n심지어 소장도 적어줍니다. 상담30분에 유료10-30만원 내던게 사라졌어요.',
 '회계사 걱정할 정도면 다른 업무는 이미 폭망중',
 '잘라말해서 아버지 연줄 없으면 수습기간 채용해주는 회사 없습니다.',
 '무섭다',
 '회계사는 정말 AI대체 예상 1위였죠.  역시 올것이 왔네요',
 '에구\n젊은분들 취업이 점점 더 어려워지겠네요.\n걱정입니다',
 '웹   프로 그래머도  5년 전에도  800 이상  20년 전에도   500  이상 벌었다   이제    제일 먼저   나가야 되는 현실',
 '회계사자격증 취득한사람 카이스트 컴공이 취업을 걱정해야해..?',
 '솔직히 지금 경력있는 회계사들도 운이조아 시대를 잘 타고나서 지금 시대에 AI를 쓸 수있는 회계사가 된거지. 지금 시대에 취직하려면 똑같이 이력서 백개써도 안될거임.',
 '세상이 정말 빠르게 변하고 있다는걸 요즘 많이 느끼는중...',
 '세상만 빨리변해가는듯 해요 너무 빨라서 소름 입니다 사람들은 세상 이상한 사람들로만 늘어가는듯 하고 ',
 '판사를 ai로 대체하라는 말이 판사도 사람이고 분명 정황상 억울한 상황이 있고, 특히나 타인의 의한 살생행위에 대해 피해받은 사람, 그로 인해 남은 가족들이 앞으로 살아가는동안의 감내해야 될 큰 상처들 등 그런 사안을 피해자입장에서 헤아리지 않고, 그저 법리대로만 판결할거면 정석대로 ai로 가란 뜻임. 특히, 음주운전으로 인해 사망한 억울한 죽음, 묻지마 폭행,살인 등 이러한 사건은 심신미약 ,초범 형량 감경을 없애야 함. 한 사람의 생명뿐 아니라 앞으로 남은 인생을 살아가야 할 그 가족들 또한 피해자로 엮어야함.',
 '울나라에 시험제도가 잘 못 되었다.\n해외처럼 단계별 시험제도로 기회를 주는게 아니라 울나라는 떨어트리려는 시험제도 때문에  시험문항도 쓸때 없는 공부량이 많고 시대에 흐름을 따라가지 못 하는 시험제도 부터 바꿔라',
 '30년정도 일찍태어날껄 \n인간일자리가 점점 더 없어지네 ㅠ 집값은 미친듯이 오르고',
 '판사부터 AI로 대체되어야죠',
 '무서운  세상..',
 '현직입니다 본 영상에서 말하는 것과 같이 단순하게 Ai 자동화로 인해 저연차 회계사에 대한 수요감소로 미지정 상태가 난 것이 아닙니다. 구조적으로 20년 초반까지 업황이 피크를찍고 내리막이 예상되고 있었는데 관련당국은 업계수요를 무시하고 선발인원을 오히려 더 늘렸습니다. 업황도 안좋은데 ai 자동화로인해 저연차에 대한 수요도 감소한 효과가 겹쳐져서 미지정 상태가 발생한 것 입니다.',
 '공무원이 답인가. 벌써 공무원으로 몰리고 있던데',
 '지금은 3~5년차 회계사라고 하셨는데 Ai가 더욱 발전하고 저렇게 계속 학습시켜 주면 내년엔 시니어 회계사 업무도 도맡아 할듯..',
 '개발자 7년간 하고있는데 내가 시작할때에는 \n4차산업혁명이니 뭐니 하면서 진짜 개발자를 많이 뽑아다 진짜 개 븅신처럼 해도 회사에서 신입을 키워서 써야한다는 생각으로 직원을 채용했다. \n코로나 터진 시점 이후로 ai가 발전하더니 프로젝트 급 줄어들고 한순간에 신입들이 취업하기 힘든 환경이되었다. 당장 이일을 15년 20년 해먹을수 있을까에서 10년 아니 5년 ... 점점 줄어드는 느낌이다 미래가 불투명해진다. 할줄아는일이 개발밖에 없어서 뭐먹고 살아야하나 고민이 크다..',
 '시작은 저년차 신입들 대상이지만 좀 더 발전하면 중간급 실무자들도 다 박살나겠구만',
 '앞으로시대는 더힘들끼다  이건 대세기때매 절대피해갈수없음.',
 '일의 전문성과 상관없이 노동집약적인 업무는 거의 ai가 대체한다고 봐야겠네 이제',
 '어쩌면 저출산이 당장은 문제지만 먼 미래를 본다면 축복일지도 모른다',
 '불과 3-4년 전만해도 저출산은 비교문화의 폐해라고 생각했는데, 이젠 정말 생존의 문제로 디폴트가 되어가는것 같다.',
 '재무직 신입 취업하려하는데 너무 안됩니다……..4년제고 학과도 세무학과고 자격증도있는데 안돼여 정말..',
 '전문직 자격증도 안심 못하는 시기구나',
 '지금은 2-3년차 회계사지만 내년은 6-7년차\n정속이 아닌 무섭게 가속 중입니다.\n물리AI까지 보급화되는 순간.ㅠ',
 'Ai때문도 있지만 타업종도\n불경기가 심각해서 애초에 채용자체를 안함.\n\n주변 공장단지들 식품,제조,건설,유통업 대표나 직원들 만나서 얘기해보면 최대매출 -60%빠진곳도 들어봄. \n작년까지는 누구는 잘됐다는 소식이 있었는데 지금은 진짜 좋은소식자체가 아예 안 들림.\n\nAI + 경기침체\n앞으로 2~3년내에 정말 많이 변할것같음.',
 '45세 일인 자영업자입니다.\n무우. 배추. 양배추.대파.오이 등등 차에 싣고 다니면서 새벽에 식당에 납품합니다.\n큰돈은 안되고 집 살 능력은 안됩니다.\n저보다 똑똑하신 젊은이들은 힘을 내고 꺽이지 않는 마음을 가지고 취업 성겅하길 바랍니다 . 화이팅!!',
 '인구수는 줄어드는게 맞다니깐\n이 상황에서 출산율 높다?? 경쟁불지옥 대한민국됨',
 '공감 it 작년부터 조짐이상한거 업계에 모르는사람 없었지',
 '미국에 사는데요 미국도 AI 때문에 졸업생들 정말 힘들어요... 많은 한인 자녀들이 컴공이나 수학을 사용하는 직업으로 많이 빠지는데 정말 취업 힘들어요',
 '어떻게 이런 일이.....................',
 '세상에 휘둘리면 이도저도 못한다. 그냥 본인에게 집중하고 본인이 하고싶은거 하고 살아요.',
 'IT 뉴스를 안 보고 지낸  씁쓸한 결말이네요',
 '4:04 맞는 얘기긴 한데 본인 밥그릇 생각해서 사다리 차는 느낌도 나는 멘트네',
 '저출생은 그냥 자연스러운 자연의선택이네',
 '자격증으로 결정되는 직업들은 걍 안하는게 맞는듯... 미래가 없음',
 '3~4년 지나면 사무직은 다 집에 가야될 듯',
 '이걸보니 열심히 공부하고 노력해봤자 아무소용없다는 생각이듬',
 'AI라는 거대한 흐름 앞에서 자격증이 무슨 소용.. 시대를 읽는 것도 능력이거늘',
 '의사도 수술빼고 많이 비슷.\n혈액검사 결과지 보여주니 너무 잘 설명해 줌.\n처방약 알려줘도 설명 많고 이해도 쉬움.\n병원가서 의사랑 대화해봐야 6~8문장으로 끝임.\n의사 바빠보여서 질문도 많이 못함.',
 '병찬씨 붙고 나니까 밥그릇 지킬라고 이제는 덜뽑는게 맞다!!! 하시네 ㅋㅋㅋㅋㅋㅋㅋ',
 '택배 기사나 하자… 몸 써야 된다 이젠',
 '저렇게 열심히 공부했는데 남일같지않고 마음이 아프네요..',
 '담달에 리니지 클래식하니까 회계사 변호사 세무사 분들 오픈런 ㄱㄱ',
 '판사를 AI 가 해야하는 이유',
 '에이아이 사용해도 오류 진짜 많이 나오던데... 다시 확인을 해야하던데',
 '5년 뒤에 자기계발용으로 회계사 자격증 따둬야겠네',
 '4:05 본인은 많이 뽑을때 합격해놓고 이제는 더 뽑지말래 ㅋㅋㅋㅋㅋㅋㅋ',
 '자급자족 농사가 답이다.',
 '회계사 도장을 받아야하는 일도 없애면된다',
 '큰일이네요',
 '근데 회계사는 연도바이연도가 원래부터 좀 심했음. 어떨 땐 4대 법인 전체 티오가 회계사 시험 합격자 총합보다 많아서 그냥 4대 전부 원서 넣으면 무조건 4대 회계법인 합격인 연도도 있었고 어떨 때는 스카이 상경계 - 회계사 시험 합격이라는 초엘리트 코스 밟지 않으면 이름 들어본 회계법인에는 못 들어가는 그런 해도 있고 그랬음. 뭐 이번엔 좀 심각하긴 함',
 '일론이  미래에  인간의사보다  로봇의사가  더  치료  잘할거라네요',
 '모든 산업이 똑같아요ㅠ 미국 금융권에서 일하는데 금융, 컨설팅, 테크 채용은 박살났고 그나마 포지션 열린데는 의료 정도..? 당장 저만 해도 몇년 전에 10명 팀이 1달 동안 하던 일을 지금은 저 혼자 2주만에 하고 있어요. 그나마 90년대생까지는 어떻게든 밥벌이 할 경력이라도 쌓였는데 00년대생 신입들은 자리가 아예 없어요...',
 '시간의 문제일뿐 안전한 직업은 없다.',
 '앞으로는 없어지는\n직업을 미리 알아보고\n공부해야되고\n자격증도 따야됨',
 '책상머리에 앉아서 컴퓨터나 끄적대는 일들은 다 없어질것임. 몸으로 해야만하는 일들만 인간에게 남을것임.',
 '카이스트 복수전공자가  스타트업에 겨우 취직햇다고? ㄷㄷㄷㄷㄷ',
 '앞으로는 미래지향적으로 공부 방향을 전환',
 'AI로 가장먼저 세무사 회계사 없어짐',
 'cpa합격자면 여기서 댓들로 걱정하는 분들보다 나은 인생이니 걱정 안하셔도됩니다',
 '회계사 수를 줄이는게 아니라 수임료를 낮춰야지',
 '컴공 나왔는데 ㄹㅇ 답없어서 공기업 자리 선점하러 왔습니다. 당분간은 먹고살 수는 있겠네요',
 '초딩~대졸까지 투자한 시간과 돈 대비 얻어지는 결과물이 이러면 공부가 의미가 있는 시대야? 정말 힘든 세상이네',
 '진짜 충격적인게 제미나이 실습으로 면접봤는데, 카이스트출신이라도 생성형 AI활용도가 낮은 지원자보다, 일반고등학교 졸업하고 생성형 AI이용을 극대화해서 결과물을 제출한 사람중에 후자가 뽑혔다는게 더 충격적입니다. \n모 스타트업에 실제 있었던 일입니다.',
 '지금 공대 컴공 전공자\n작살 나는 중....',
 '이런거 보면 확실히 AI기업이나 주가에 거품이 끼었을지는 몰라도 AI가 생산성 향상에 도움을 둔다는 것 자체는 진실이라는걸 알 수 있음',
 '60년대 70년대생들이 최고로 운이 좋음...',
 'AI가 못하는 손기술있는 배관공, 타일공들이 대세가 된다잖아',
 '04:06 와.. 황병찬님 본인 회계사 일하고 있다고 자기는 일 잘릴일 없으니까 신입들 많이 안 뽑아도 된다는 말을 하시네요. ㄷㄷ',
 '앞으로 회계사는 공인 중개사랑 똑같은 취급 된다.',
 '지금 회계사 걱정할때가 아니다.다들 젓됐어.',
 '4:1 회사가 지금 200:1 됬음 겨우 디자이너 한명 뽑는데 it 아이티 망한지 오래임 ㅎ 잘할 필요없는 ai가 다해서 정치 잘해서 윗사람한테 잘보여서 나오지마셈',
 '신입 변호사, 회계사가 몇날 몇일을 자료 모으고 정리해야 할 일을 몇 초면 끝내버리니..',
 '회계사, 세무사 등 숫자관련쪽은 대체가 쉽죠.\n3명이 하던걸 혼자 할 수 있게 되는거고. 나중에는 일반인들도 AI와 상담하면서 회계사, 세무사에 의존도가 낮아 질거고.  모든분야가 조금이라도 영향을 받을 것 같네.',
 '현직 회계산데\nai는 핑계일뿐, 수요예측 안하고 회계사 합격자수 미친듯이 높여놓고\n업계 자체가 덤핑으로 곪아가고 있는데, \n욕심많은 윗대가리 새끼들이 스탭들 싸게 부리고 갈아치울라고  많이 뽑은게 이 사단이 난거임\n아직까지는 ai는 거들뿐임.. 앞으로는 ai때문에 진짜로 업계가 힘들어질 날도 오긴 하겠지만..',
 '화장품 사업 하는데 직원 3명 필요한 일을 3만원 gpt가 해줌. 느끼는건 브랜드를 만들고 ai활용해사 키우는게 답. 유통, 광고, 회계, 번역 통역, 컨텐츠 등 점점 직원 필요 없어짐',
 '힘들게 공부했는데 취업이 않되니  젊은이들이 희망이 없는나라  ㆍ싸움질하는 국회의원 숫자나 줄이지',
 '가계부 앱 받아서 쓰는데 졷같은 광고 계속떠서 내가 앱만들어서 쓰고 있씀. ㄷㄷㄷ 이런 시대임. 하다못해 이런것도 안하면 그냥 밑바닥 되는거임.',
 '하....... 작년 컴공 졸업생 진심 개빡침....',
 '하 진짜 전공을 뭐해야하는거냐 아예 이젠 대학이 의미가없는거냐 취업은 어케하라고 ㅠㅠㅠ',
 '황당하겠다',
 '이래서 요즘 유튜브에 세무사들 자극적으로\n세무조사 세금폭탄 어쩌고 하는 영상들이\n많아진거같음',
 '사람이 필요없는시대임\n근대 왜자꾸 애를 낳으라고 하는지 몰겠음',
 '생각의 속도를 인간이 따라가지 못한다. 더빨리 변할것이다. 우리가 느끼기도 전에',
 '정말 우려되는 현실이다.',
 '예상은 했지만 요즘 기술 발달하는거보면 진짜 무서울 정도...\n앞으로 직업 생태계가 완전히 바뀔거라는 예상하고 있는데 이젠 사람 5감 만족 시키는 체험형아이템이나 아이디어가 필요한 분야가 커질거로 예상.. 숙련기술의 경계 자체가 없어지고 있음..',
 '꼭 자기코앞에 떨어져야 아~~ 이러고들 있는지   미리미리 들 생각 못하는지~~~',
 '지가 땃으니까 줄여야 된댘ㅋㅋㅋㅋㅋㅋㅋㅋ',
 '이젠 우리 스스로 다 필요없는 인간들이 되어가고 있는 듯 ㅠ',
 'IT업계는 진짜 진작에 AI에 다 먹힘;; 소프트웨어쪽은 특히나 심한데 제일 심한게 바로 게임업계임...\n진짜 끝났음;;; 신입 및 저연차뿐만이 문제가 아니라 경력직들도 회사 망하는 순간 구직난임...고연차는 능력 좋은 사람도 안뽑는 시대임 ㅋㅋㅋㅋ',
 '부모들이 정신차려야됨..애들 대학 보낼 생각하지말고 그 돈 아끼고 빨리 자기만의 기술을 배우게 해야됨',
 '회계사랑 세무사 완전 존망해가는중\n이 공부하시려는 분들은 시작도 하지마세요 인생 좇될수있음',
 '아주 재밌는 장난: 10년 넘게 공부 시킨 다음에 AI로 대체하기',
 'AI 시대, 질문이 곧 무기다.\n두리뭉실한 질문엔 AI도 평범해진다.\n페라리를 타고 출퇴근만 할 건가?\n제대로 질문 하는 자만이, AI를 진짜로 달릴 수 있다.',
 '변호사 세무사 회계사 전부 망했지 뭐',
 '사람 한명 가치가 H200한장에도 미치지 못해지는시대',
 '회계사를 합격할 정도면 다른 시험도 충분히 합격해서 다시 시작할 수 있답니다',
 '자기가 그자리차지하고있다고해서 후배들자리없애려는 표독한 사람들',
 '미국에서 일반 회계사는\n매번 계약직 생활이고\n\n세무사는 동네 마트에서 \n책상 하나놓고 영업하며 상담함.',
 '개인이 단체가 나라가 발버둥치고 막아보려해도 이건 어쩔수없는 현상이다.. 에휴.. 이제 어떻게 살지..?',
 '젊은애들은 살수가 없는구조가 됐구나 노가다나 농업만 해야하는거구만',
 '전문직 고시생 여기없나 ...... 아 살려주셈',
 '4:00 붙은사람이 이런얘기하면 안붙은사람이 섭섭하지 ',
 '퇴사는 진짜 미친 행동이다\n나가면 들어갈 곳이 없다',
 'ㅋㅋ 병찬씨\n당신 자리두 얼마 안남았어요 \nㅋㅋㅋㅋㅋ',
 '2:20 고객사 회계자료를 걍 ai에 넣어버린다 ??  ㅋㅋㅋ  유출 될거라고는 예상 안하나 ? 그리고 난 합격했고 ai가 발달됐으니 합격자 줄이라는건 뭔 심보여 ㅋㅋ',
 '괜히 배관공이 미래에서는 제일 고소득직군이라 하는 이유가 있음',
 '나완 상관없다고 편해졌다고\n안심하면 안됨... 결국은 모든 사람에게\n이득보단 피해사례가 더 많아질것임\nAI는 정보검색등 적당 수준에서 선을 그어야 할듯',
 '현실 부정하지 말고 빨리 공장 노가다 하러가라...',
 '대학교 막 졸업하신 분들은 진짜 어렵겠다. ㅜㅜ. 일단 취직하시고 봐야합니다.. 안그러면 기회가 더 없을거에요..',
 '일론머스크가 의사 나가리도 언급했지 ㅋㅋ 한나라의 최고의 인재가 의대만 가는데, 미래가...',
 '다음 타겟은  통역관련업무 입니다',
 'ai 문제 없다던 전문직들 튀어나와보세요',
 '현직 공무원이라 그나마 다행이네요,,,신분은 보장되니.,.요즘 다시 공무원 인기가 저 들어올때처럼 20%이상 상승했다고 들었는데\n앞으로 더 힘들듯...',
 '이제 잘리면 청소업체에 들어가야겠다\nAi가 청소는 못하겠지ㅋ',
 '로펌도 비슷한 상황입니다. 저희로펌 하루 찍어도 지금 IT기업이랑 동일한변화가 생겼습니다. 기초법령, 판례리서치, 이를통한 확률검토 전부 AI가 즉각적으로하는 일들이라 주니어 고용변호사님을 시켜서 받는것보다 시간이 훨씬 절약되서 굳이 뽑을 이유가 사라집니다. 같은 법조계선배로서 진짜 안타갑네요',
 '조아써  이제  판사도 적용시켜보자',
 '10여년 전부터 ai로 가장 먼저 대체될  직업군 이라고 시끄러윘는데.',
 '회계사만 그런게 아니야.. 문제는 AI가 사람만큼 아니 보다 더 정확하고 일잘한다는거지',
 '약사는 ㄹㅇ ai타격이 크겠다',
 '잔인한 장난이다\n장기간 공부시키고 직업은 ai로 대체되기',
 '운이 없다고 할 수 밖에. 그런데, 곧 다른 직업들도 따라갈거 같아서 미래가 참 어찌될지.',
 '아 내 아들 일같아 마음 아프다 ㅠㅠ 청년들 일자리 많아졌으면 너무 좋겠다',
 '대학 졸업장이 큰 의미가 없어지는 세상이 온거다. 그걸 전 사회가 깨닫는데 5년은 걸리겠지만.  직업학교역할 하던 대학들은 문 닫는다.',
 '청년실업이 심각하다. 정부는 정년연장에만 관심갖지말고 취업에 대한 대책 먼저 마련해라',
 '시대의 필요에 따라 직업군도 당연히 바뀌지...',
 '그와중에 되는 회계사들은 코딩, AI배워서 어떻게 실무에 적용하고 기존 프로세스 개선할 수 있는지 사이드프로젝트 만든걸로 어필해서 취업하더라. 안된다고 징징댈게 아니라 왜 예전의 방식으로는 안되는지, 어떻게 하면 기회를 잡을지 정확하게 진단해내면 누구나 할 수 있다는 방증.',
 '여기 댓글들 왜 이렇게 꼬였냐 사람들이',
 '04:09 사회 트렌드? ㅋㅋㅋ 내 밥그릇은 뺏으면 안되지~ 라고 입은 삐뚤어져도 말은 똑바로 솔직하게 해야지 ㅋㅋㅋㅋ',
 '5년..진짜 스스로도 미치겠네',
 '애초에 많이 뽑은 게 회계기준 개정으로 갑자기 인력 필요해져서 아닌가?',
 '국내 중소기업 다죽어가는데 뭔 회계사고 ㅋㅋㅋㅋ\n손님들이없는데 뽑을리가',
 '그대들의 성실함을 인정합니다! ㅎ',
 '세상이 많이 변했어요\n다른 직업들도 많이 없어지겠죠\n그 과정중 하나일뿐 안타깝네요',
 '판사가 왜필요하노 법대로안하는데 AI로대체해라',
 '지금은 프롬프트 라도 잘짜는게 능력이라지만.. 이 조차도 한 5년쯤 지나면 걍 생가나는 대로 지껄이면 그 프롬프트 조차도 짜주는 수준으로 될거임. 지금 부장이 신입급한테 프롬프트급으로 조리있게 업무지시 안하잖어?.. 걍 알잘딱깔센 같은 느낌으로 25년도 분기별 매출실적 예쁘게 정리해봐 정도 레벨만 말해도 돌아가는 수준까지 몇년 안남음..',
 '인간이 필요없어짐. 앞으로 인간이 할수 있는 일은 밥먹는 거 외에 없음',
 '상담직도 사라질수도.. gpt한테 상담해봐라  부끄러운것도 없고 나름 그사람 감정 이해하고 객관적인 답해줌 ㄷㄷ',
 '진짜 한국은 저출산이 축복이다 ㅋㅋㅋ 이런 상황에서 출생아수 70만명이면 취업 못한사람들 수두룩\n사회가 불안할듯',
 '이거보니 아들 공부하란 소리가 안나오네요 ',
 '8:22 지원을 5개밖에 안했다는 거 자체가 이상했는데 카이스트.. ㅋㅋㅋ',
 '변호사도 없어질듯\n고소장이랑 의견서를 ai가 직접 작성해줌',
 '젊은 세대가 참으로 딱하고 \n안타깝습니다 ㅠㅠ',
 '작곡도도 살아남기.힘듬',
 '판검변호사도 조속히 AI로 대체해야 합니다ㅡ',
 '이제 시작인가 지금 정치권이 자기 밥그릇 싸움할 때가 아닌 것 같은데 말야 국민들도 이런 사회적 문제를 더 심각하게 받아 들여야 한다. 누굴를 감옥 보내고 이런건 우리의 삶과 아무 소용없는 것들이다. 더 무서운 게 다가오고 있는데 쓸모없는 일에 우리가 몰두하고 있는 게 아닌가를 생각할 때인 것 같다.',
 '의사도 ai로봇 수술기로 대체 될것이다. 이미 의료기본사항들은 ai가 터득다함.',
 'Ai를 이기지말고 그냥 이용하자 그냥 창업해 물론 힘들겠지만 그냥 새로운걸 창조해내자',
 '자기는 AI로 대체되기 싫고 신입 회계사들만 대체하고 싶어서 회계사 공급통제하자고 주장하는게 얼마나 이기적인가. 지들은 1000명씩 뽑을 때 붙어놓고는ㅋㅋㅋ',
 '심각한 위기라고 생각되네요..에휴  우리세대는 그럭적럭 살아왓다만  내 손주세대는 정말 걱정스럽다.. 결국은 몸으로 때우는 일만이 사람이 직접해야 하는것만이 살아남겟네..',
 '인생은 선택을 잘해야함. 아무리 머리좋고 노력 많이해도 세상 흐름 못읽고 잘못된 선택하면 도태됨.',
 '출산하면 안되는 시대\n이제는 결혼해도\n자식 낳지말자 로 가야함.\n금수저나 상위 몇프로만\n자식 낳자.\n흙수저는 낳지 말자.\n생각없이 낳다가 내 자식\n직업 없으면 어쩌려고\n현실을 바로 보자 ~',
 '이런영상보면 중국인지 한국인지 모르겠다.상황이 똑같네.',
 '사람에 의한 건 인공지능으로 대체 못함.',
 '안됐지만 눈을 돌리셔야합니다.\n몸쓰는 일에도 가능성을 열어두시길..',
 'AI로 판사부터 대체해라.',
 'ai와  로봇의  조합은  육체노동도  상당수  대체가능할것. 로봇이  자율주행차에서  내려서  택배기사처럼  배달하겟지.',
 '구구단 5년동안 외웠는데 계산기 나온꼴',
 '2.3백이라도 벌어서 ai기업이나\n미래 산업에 투자를 해서 이 죽음의 나선을 벗어나야지.\nAi랑 싸울려고 하면 안됨.\n거대한 흐름에 편성하고\n자본시장을 인정해야지\n범재가 노동으로 역전할수 있는\n세상은 이미 지났음.',
 '그동안 숫자놀음 해주고 과도하게 받앗던거지 ai 몇초면 되는걸',
 '우리아이들은 무슨일을 하고 살아야할까요 걱정이네요..',
 '공인회계사 난이도는 거의 3고시 다음 아닌가..?\n얼마나 속이 뒤집어지고 울화통이 터질지 이해\n가 간다.',
 'ai가 마지막까지 대체하지 못하는 직업 중에 하나가 미용사입니다.',
 '이미 코로나전부터도 회계사,변호사 AI는 나왔었음. 그냥 부정하고 싶어서 "우리 직종은 절대 AI가 대체 불가하다.그게 한국어로 번역과정에서 경리를 회계사로 오역한거다" 라고 합리화 하고 있었을뿐.\n시간문제인데 한국은 노조가 있어서 시간 좀 걸릴듯',
 '나도 회계사지만, 어쩔수 없다. 시대가 요구하는 수준으로 나를 끌어올려야 한다. 세상을 탓하지말고 자신의 부족함을 탓해야~ 자격증 하나로 평생 먹고 살려는 생각부터 버려야 한다.',
 '결국은 기술직이 살아남겠다',
 '다큐의 제왕\n공영방송 KBS 잘 봤습니다.',
 '사람이 꼭 필요한 현장 기술직  노가다 등이  가장 오래 살아남을 직종이죠ㆍㆍ ㆍㆍ  로봇으로 대처가 가능한 건 공장의  일이고',
 '그냥 빨리 ai로 대체할수있는건 대체하고 기본소득줘라',
 '억울해도 어쩔수없어요. 시대흐름을 따라가야죠. 다른일 알아보세요.',
 '수습도 안 해 줄 거면 시험 자체를 없애라',
 '전화 교환원이 사라진거랑 같은맥락임…앞으로 저런게 점점 더 늘어날꺼야 빠르면 1년 길어도 10년…',
 '중소 지원 안하냐는 말하는 뉴스 댓글들 많이봤는데\n이게 현실임 ㅋㅋ 중소조차 한명뽑는데, 과제, 시험, n차 면접 하는 시대이더군요\n막상들어가면 시스템은 중소라 당연히 없을테고 ..\n청년 세대는 시작을 못하고 중년 세대는 언제 대체될지 모르고..\n근데 이게 걱정인게 시니어가 하루아침에 만들어지는게 아닌데\n다음 시니어 세대가 되었을때 주니어가 없으니 .. \n일본의 잃어버린 30년이 생각나네요',
 '회계사 되고 싶어서 cpa 시험 준비하고 있는데 가끔은 막막해질 때가 많네요..',
 'AI를 활용해 더 성장하는 사람이 있고 도태되는 사람이 있음\n시대의 흐름을 읽고 잘 적응해 살아남아야 함',
 '대학 타이틀만으로 취업하던시대는 또 언제냐? 내가아는건 20년전에도 그런적은 없다는거임. 그때도 코딩테스트 다 하고 인재인지 벌래인지 가려냈음',
 '젠슨황이 전기기사 배관공은 ai시대에서도 살아남는다 그랬음',
 '몸으로 때우는 시설관리나 현장직업이 끝까지 살아남을듯',
 '머해먹고 사냐?   대학도 굳이 다닐필요도 없을듯 한데...',
 '05학번인데 저희 졸업할 때가 회계사 막바지 전성기였다고 생각합니다. 2010년대부터 앞으로 사라질 직업 상위권에 회계사가 꾸준히 나오기 시작했거든요. 15년만에 일반인도 체감할 수준으로 나타난 거구요. 그런데 모두가 바라는 법조계의 AI대체는 기득권 때문에 절대 현실화되진 않을 것 같아요.우리 나라는 문과가 정치를 주도하는 국가인지라...',
 '공공기관 행정직 입니다. AI가 업무 판도를 싹 다 바꿔놨습니다. 사업 제안서, 결과, 발표자료 등 예전에는 20~30분 걸릴 작업을 지금은 5분이내로 그것도 더 좋은 퀄리티로 만들어냅니다. 무결성 데이터 관련해선 아직 다시 확인해야 되지만, 글짓기 같은건 내가 찾는 범위+속도와 비교도 안되게 AI가 더 빠르고 광범위하게 찾으니 더 논리적이고 위에 보고할때도 설득이 훨씬 더 빠릅니다. 업무뿐 아니라 일상생활까지 다 바꿔놨는데요. 최근에는 15년 동안 붓고 있던 종신보험도 계약서 PDF 딱 올려서 현재 이걸 유지해야 되나 특약변경을 해야되나 그만 넣어야 하나 하는 판단도 보험설계사 이상 수준으로 30초 내에 정리를 해서 보여줍니다. 이게 얼마나 무서운거냐면, 지금도 AI를 잘 안쓰는 사람들이 많아요. AI를 100% 잘 활용하는 사람과, 조금 써보는 사람과 아예 안쓰는 사람 간의 격차가 엄청나게 벌어진다는 겁니다. 지금도 저희 회사만 봐도 AI 잘 활용하는 직원과 안쓰는 직원 차이 엄청 납니다. PC에 익숙하지 않은 부장 이상 세대에선 AI 이전에도 젊은 직원들과 격차가 있었는데 지금은 완전 바보가 되어 가는 중이에요.',
 'Ai 창작물 무단학습 규제 법안좀 만들어주세요...작품이나 디자인 저작물 학습 극혐입니다',
 '가장먼저 ai 대체가 시급한 직업군이 바로 판사, 검사인데 말이지...',
 "It's not just Korea",
 '이런논리라면 의대도 줄여야됨 증원한다고 소란피우지말고',
 '공대나와서 코딩만할줄알면 취업보장되는시절이 있었는데 몇년사이에 이렇게 바뀔줄이야…',
 '04:00 저 회계사분은 적게 뽑아야\n한다고 할때가 아닌데 저러다 완전 AI로 대체되면 어쩌려구 저러나…',
 '문과 전문직 자격증은 3년안에 싹 다 없어질겁니다. ',
 '한공회가 쳇지피티로 데이터를 정리한다고? 정보보안법 위반 아니냐?',
 '인문계는  문 닫는다.',
 'AI가 프로그래밍이나 자료 정리를 도와줘도 결국 누군가는 AI를 다뤄야 하기 때문에 사람이 필요하긴 한데 경력자는 필요하고 신입은 필요가 없게 되는 상황. 근데 프로그램도 그렇고 회계도 그렇고 정형화된 업무나 데이터가 아닌 경우는 물론이고 최종적으로는 사람이 돌아가게 해야 하기 때문에 사람 없이는 안됨. 주니어 레벨의 필요가 줄어들긴 하는데 그냥 AI 핑계로 감원하는 거 같음.',
 '이기주의봐라. 출입문은 줄이고 법령으로 철밥통은 보호받고 싶다고? 회계사들 이기주의봐라.',
 '백날 천날 면허 하나로 날먹하는 의새들이 이상한거 ㅋㅋ 최소 5년에 한번씩 면허 갱신 시험제도 도입해야함',
 '이제는 감정 이용하고 몸 쓰는 직업이 오히려 수요인듯',
 '회계사/변호사/세무사가 몇년안에 없어질 직업이라고 하던데...;;;',
 '회계사 도장받아야 되는 일 그냥 기관 담당자가 지피티로 엑셀에 함수넣어서 돌려보고 오류없으면 통과시키자. 회계사 진짜 필요없음',
 '카이스트 나와도 취업걱정을 하다니..진짜 전기공,배관공 해야되나봐...',
 '디자인쪽도 마찬가지 채용공고가 2026년 들어서서 급격하게 줄음 그나마 올라오는것도 지원자가 100명이 넘음....5인미만 중소기업인데도 100명 넘게 지원함...다른길을 도전해야되나 심란하다 매일매일이',
 '대학에 갈 필요가 없어졌어. 이젠 예체능, 감정서비스, 심리상담가등 서비스업과 손노동만이 살아남을듯.',
 '분석이 완전 틀렸는데..ㅋㅋ\nAI 때문에 회계사 일자리가 없는게 아님\n회계감사 가격후려치기 때문에 법인들 이익이 줄고, 그로인해 신규채용이 줄어든거임',
 '어찌하리오~~시험하실정도로 머리가 좋으신분이니까 인공지능에 맞는 분야 찾아서 다시 시작 가능하실듯\n능력이 별로 없는  나 ...슬프네',
 '세상과 경제가 변하면서 직업이 사라지고 생기기도 한다.  거기에 맞추어 살아 남는 수밖에..,',
 '회계사 자격 있으면 먹고 살 수 있다.\n자기 사업을 시작하는 것도 괜찮다.\n대부분은 용기가 없어 낭떨어지 못 떨어진다.\n그러나 용기가 있는자는 자생하여 더 강해진다.',
 '와 진짜 꼬우면 일찍 태어나야했구나',
 '간 초음파 사진 AI에게 넣고 물어본 내용과 이후 병원 진료일에 의사한테 들은 이야기가 똑같...\n이젠 의사의 역할도 사라질 판...',
 '마지막 말이 핵심. "컴퓨터 앞에 앉아서 일하는 사람들은 다 위기에요." !!!',
 '뭔가 착각하는게 회계사 자격증이 회계감사 업무에만 필요하다고 보는 모양이지.?? 미국처럼 일정 점수 이상이면 모두 합격시켜주고 합격 후 진로는 본인들의 능력으로 가는거다.. 이 놈의 나라는 왜 자꾸 제한을 두어서 경쟁을 막으려 하는지 모르겠다..',
 '앞으로 회계사 세무사 필요없다\nAI 발전이 상상을 초월한다\n사람보다 더 탁월하다\n무섭다',
 '현직 회계산데 빅펌에서 미취업 신입회계사가 많아지는 이유는 AI가 아니라 몇년동안 지속된 증원때문입니다. 이런식으로  호도하지마세요 방송국들아',
 '이젠 어떤 직업을 찾아야하나.....',
 '이건 또 뭐냐...진짜.. AI떄문 맞나?',
 '사실상 10년안에 없어질 직업 : 회계사,세무사,법무사,변리사,행정사, 약사, 전화응대원, 몽키 코더 등등,  업무가 정형화된 반복작업만 하는 것들.',
 '제일 쓸데없는 걱정이 전문직 연예인 걱정임 ㅋㅋㅋ 전문직 걱정하는거 아니야~ 약코 적당히 해라',
 '스포츠 선수는 대체 불가 겠네요 .',
 '진짜 큰문제임 회계사 세무사는 5년내 공인중개사 정도와 비슷해짐 ai를 정통으로 얻어맞음',
 '세무사 회계사들\n솔까 10분상담에 20만원씩 잘\n받아쳐먹었자나 그동안\n그것도 현금으로\n\n최근에 세무사상담 5분에 15만원 주고 받았는데\n챗지피티가\n알려준 거보다 덜 정확하드라\n그냥 인간에게 들으니\n안심한 정도 그이상도 이하도 아니더라\n\n회계사 세무사\n특히 세무사들은 국세청에서도 ai돌리면 뭐 가공경비 다 잡아낼테네 필요없어지몀서 투명해질듯',
 '이렇게 될걸 모르는게 이상한거 아냐...? 저거 붙을 머리로',
 '옛날 전화번호부를 전부 외우는 시험이 있다고 가정했을때 난이도는 아주 어렵겠지만 메모리 장치의 상용화로 쓸모가 없음.\nCPA도 AI의 등장으로 비슷한 흐름으로 가는거지...\n근데 저분들은 뭘해도 될 분들이라 제 길을 잘 찾아가시리라 믿음.',
 '판사도 대체해라 솔직히 3분의 1만 써도 될듯',
 '기타 사무직은 가만 냅두고 전문직인 회계사가 먼저 사라질거라는분들 ㅜㅜ 저기요. 저희들이 가서 보는게 님들이 뭔짓 해놨는지 보는거에요ㅋㅋㅋ님들이 헛짓거리 해놓은거는 ai도 몰라요. 태반이 세상에 없는거라서요ㅋㅋ회계업계가 ai로 다 장악되려면 우선 일반 회사자체가 전부 표준화된 전산화가 가능해야합니다.\n지금 회계사 미지정은 문정부때 갑자기 확 늘려놨는데 그때는 내부회계도 있었고, 코로나로 돈풀려서 기업도 호황이고 그랬었는데, 내부회계 다구축해서 더이상 일없고, 경기안좋아서 대규모 채용안하는 이유가 더커요.',
 '다른 업종은 모르겠지만, 현재 회계사가 AI로 대체되는 것이 아니라, 파트너 등 임원들이 프로젝트를 따오기 위해서 가격을 후려치는 저가 수임이 만연화되었고, 얼마 되지 않는 계약금으로 일을 하려다보니 충분한 인원을 투입하지 않고 있는 상황입니다. 저가 계약으로 3명이 해야 하는 일을 1명이 하다 보니, 최근 회계빅펌에서 자살하거나 젊은 나이에도 병으로 사망하는 사례가 나오고 있고, 회계사들은 새벽 2시 퇴근이 빠른 퇴근이라고 할 정도의 극한 환경에 내몰리고 있습니다. AI는 약간의 보조 도구일 뿐, 회계사의 업무를 중단기내  대체하기에는 아직 그 수준이 너무 미흡합니다. 현재는 AI 핑계로 고위급들이 투입 인력을 무리하게 급격히 줄이고 있을 뿐, 실제 사람이 해야할 일은 그대로 남아 있는 것이 진짜 문제입니다.',
 '단순노동이 제일 늦게 대체될수밖에 없는게 가장 싸거든 세상이 무너지기 시작한다',
 'ㅋㅋㅋㅋㅋ이런 뉴스보고 좋아라하는 사람들은 몸쓰는 사람들이 태반인가? 자영업자라던지 일용직이라던지',

In [10]:
clean_data = [comment.replace('\n', ' ').strip() for comment in data]
clean_data

['공인회계사 최종합격자와 카이스트 컴공이 취업을 걱정해야 하는 세상...',
 '카이스트  물리학과  컴공 복수전공한 분이  AI때문에 취업이  쉽지않다고 하면  다른  대학출신은  얼마나  힘들지  상상이  안가네요.',
 '다들 먼 이야기라고 생각하겠지만 지금 당장 tv만 봐도 재연을 대역배우가 아닌 그냥 ai영상으로 다 대체하고 있음;; 벌써 시작하고 있잖음',
 '회계사가 대체될 정도면 이미 컴퓨터 앉아서 하는 대부분의 사무직은 곧 전멸하겠네',
 '앞으로 살아가야 할 내 자식들, 청년들 미래가 너무 불투명하고 안타깝고 서글프다...',
 '5년에 걸쳐서 버스안내양 합격했는데... 자동문 나와버린 꼴;;;',
 '숫자다루는 업무는 특히 ai가  잘할듯',
 '개발잔데요.. 그냥 기도합니다 제발 이 기술이 모두의 공리와 행복을 증진시키는 방향으로 발전되기를.. 개인이 발버둥쳐서 대비하거나 바꿀 수 있는 수준이 아닙니다. 그야말로 대혁명.. 불의 발견, 전기의 발견에 버금가거나 그 이상으로 느껴집니다.',
 '정말 어려운 시험인데 그걸 따고도 백수라니....너무 안타깝다',
 '유튜브에 회계사 합격하고 가족들에게 울면서 전화하는 합격자 있었는데... 이영상보니 진짜  허무하네요',
 '문과 사무직인데, 불과 5년전만해도 주변에 퇴사하고 코딩 교육받아서 개발자로 재취업하는 사람들 은근 있었는데 시장이 이렇게 와장창 무너질줄이야...',
 '합격증 받자마자 저렇게 비닐에 싸서 보관할정도면 그만큼 진심이고, 그만큼 인생에서 중요한 순간이라고 생각했을텐데… 진짜 타이밍 안좋으신 듯 인공지능이 충분히 다 일을 대신할 수 있을 지경까지 올걸 누가 알았을까',
 '공인회계사 합격하려고 몇년을 시간을 갈아넣어서 자격증을 땃을텐데.. 세상이 이렇게 변해버렸으니. 너무 슬프다.',
 'It대 다니고있는데 교수님 왈 컴공 개발자 구인구직이 인문학과보다 더 떨어진 상황이라네요. 갑자기 이렇게 세상이 변할줄 누가 알았을까요…',
 '회계사라고 하면 와~~하고 알아 주던 직업군이었는데ㅠ 너무 안타깝네요',
 '근데 내가보이엔 지금은 스펙이고 나발이고간에 취업시장자체가 너무좁음... 그냥 취업이 힘든게 맞음',
 '시대를 예측하지 못한것보다 시대가 너무 빠른거 아니냥',
 '이미 전망없는 직업에 청춘 바치지말고 편견을 버리고 다양한 직업에 도전해야함',
 '회사의 경리회계 더존 프로그램 처음 나왔을때 경리부 직원들 많이 짤렸지.. 분개,기장을 더존프로그램이 해버리니... 과장급이상 해야 할일을 신입여사원이 다할수 있는 일이 된 획기적인 사건이었지',
 '뭐해먹고살라고 진짜ㅜ먹고살기힘드네',
 '본질은 컴퓨터 앞에 앉아서 하는 일들은 다 대체된다는거다',
 '제일 먼저 없어져도 무방하고 오히려 AI로 대체되길 바라는 직업이 대한민국의 판사들입니다.',
 '이 영상중간에도 제미나이 광고나오네ㅋㅋ 시대의흐름이다ㅜ',
 '인터뷰 찍는 카메라에도 Ai 탑재됨 ㅋㅋ 전문 카메라맨도 사라짐',
 '필요없는 공부를 하고 너무 많은 인원을 뽑아서',
 '옛날부터 은행원, 회계사,세무사,변호사등.. 없어질직업이라고 했음. 점점 희미해져가고 있네. 정말로.',
 '회계사 세무사는 진짜 이제 답이 없다..',
 '세상변화 속도가 너무빠르다.',
 '앞으로는 주니어에 이어 중간급도 사라질듯',
 '헐 심하긴 하구나. 추적 60분까지 나올정도니',
 '노력이 배신하는시대가 왔구나!!!',
 'AI를 검수할 고인물 능력자 빼고는 신규와 중간관리자는 안뽑아요. 미국은 피바람불고있음',
 '병찬이 자기는 이제 짬도 있고 안전하니까 사다리 걷어차려는거 보소ㅋㅣㄱ',
 '과거는 자의에 의한 취업 유예였다면 지금은 타의에 의한 취업 절벽이죠',
 '진짜  서글픈 세상이네요 힘든  시험인데 ㅠㅠ  얼마나   허망할까요 ㅠㅠ',
 '참 서글프다  5년 동안 얼마나 노력해을까',
 '회계는 더 안타까운게 ai적용시키기 더 간단함.',
 '10년전쯤 미래에 ai로 대체될 직업이라는 리스트 보고 친구랑 이야기한적 있었는데 그게 진짜 현실이됐네..',
 '출장다니면서 서버 구축하고 부품 고쳐주는 유지보수 엔지니어 해야 입에 풀칠은 할겁니다...',
 '세상이 진짜 빠르게 변해가네..',
 '재무관리 경영학 경제학 시험을 왜 보냐. 쓸데없이 난이도 높여 수험생 괴롭힌 시험이 CPA 시험임. 본질 가치 대비 고평가 되어온 자격증.',
 '모든 사무직종에서.  AI 때문에 어시가 하던 일을 더 빨리, 더 깔끔하게 처리해준다.  실무자 혹은 결정권자 입장에서 어시가 필요 없어짐..',
 '참 인생 알 수 없는 게, 얼마 전 용산에서 밥 먹는데, 옆 테이블에 삼일 회계사들이 회식중이더라. 아모레 사옥에 삼일이 있지 아마. 딱 저 나이대 친구들이야. 젊더라고. 그들도 입사한 지 얼마 안 됐을 거 같아. 길어야 1~2년.  몇 년 전에 합격한 이들과 지금 합격한 이들 인생의 향방이 이렇게 달라진다. 앞으로 그게 더 심해질 것이고, 그 회식에 참석한 친구들도 앞으로 어떻게 될 지 모르는 거지. 나도 그래서 살아남기 위해서 정말 고민이 많고 분투 중이다.',
 '좌우국회의원들 모두 AI로 대체되길..',
 '4:51 아마 많은 취준생들이 비슷할 거라고 봄.. 너무 밝게 얘기하셔서 더 슬프네요',
 '창근 님 대표님이 칭찬해 주니까 허리 펴는 모습 귀엽다.',
 '협회는 지금 자격증 장사 중',
 '원래 대전환기에는 당연하게 발생하는 일이잖아. 스마트폰 나오니 삐삐공장 파산하고...ai나오니 전문직 필요없어지고..세상이 변하는데 어쩔 수 있나',
 'AI때문에 신입들이 취업이 어렵다고 아우성쳐도 정작들어와서 AI없으면 일을 못함... 더 심해지는게 요즘엔 AI로 레포트내던 친구들이 들어온다는점',
 'ai날이 갈수록 미쳤다 3초면 끝나는세상',
 '공인회계사..예전 2009년 쯤 학교 교수님이 없어질 직종이라든데..당시만해도 엄청 유망해보였는데 이게 지금 실화가 되네..',
 '쓸모없는 변호사들도 다 필요없음. 소장도 알아서 써주는데 변호사 소장 대충쓰고서 6-800이상 받아감.',
 '회계사 세무사 법무사도 이제 끝나감  법무사 ai로 신고서식 간펀하게 보급되어져야함  비싼 수수료 자기로 처리해야함',
 '우리나라같이 노동경직성있는 국가에서는 안그래도 고용과 해고가 힘든데.  리스크가 큰사실을 외면하고있음.',
 '가장 비싼 일자리일수록 ai대체될수밖에',
 '사무직 웹디자인 컴퓨터로 할수있는 직업들 은행원등 다 없어지고 있는 직종',
 '컴퓨터 앞에서 일하는 사람들은.................다 위기 입니다.',
 '아프지만 말아요. 우선!',
 '열심히 공부해서 어렵게딴 자격증으로 평생 벌어먹을 수 잇던 직장들이 2년 사이에 우르르 무너지네',
 '현실을 빨리 수긍하는 게 생존에 유리함. 내가 여태 열심히 해왔다고 현실은 인정해주지 않음. 이걸 빨리 적응하지 못 하면 죽음 뿐',
 '부모는 공부만 시킬게아니라 세상을 멀리 내다보는눈을 키워주는게 중요하다',
 '회계사 합격할 정도 인재면 다른 걸 해도 잘 함.. 힘내시오.',
 '변호사 ,판사도 AI 가해야한다.',
 '앞으로 앉아서 컴퓨터 두드리는 직종은 많이 사라진다고 봐야지',
 '우리 부부는 어떻게든 살아남을 수는 있을거 같은데, 이제 초딩인 우리 아이는 뭘 대비시켜줘야 할지ㅠㅠ 정말 너무 빠르게 변해서 모두가 막막한 사회다',
 '출산 장려하지마라. 내 자식 장래가 암울하다. 대책을 마련하고 장려를 하든해야지',
 '회계사 미지정은 이미 역사가 길다 700명대 시대에도 있었다 잠깐 호황으로 착시현상이 있었을뿐',
 '회계사면 진짜 어마무시하게 공부하신 분일텐데..',
 '해외는 인턴들은 무급이나 되게 적게 받고 일시킨다고함..',
 '카이스트에서 복전한 사람이 다 떨어지고 취업캠프를 가서 다시 5군데 중 한군데... 스타트업인데도 진짜 빡세네..',
 '전문직이 저 정도니 일반 대졸자들은 어떻다는 얘기인지…',
 '무서운 세상이야...',
 '기자 부터 ai대체 하자 판사 다 없애라  국민의 삶에 소금 뿌린 자',
 '진짜 맨나중으로가면 진짜 아예 인간 을 채용하지 않을듯',
 '개발자 직군이 진짜 ㅈㄴ 타격입은거지 몇년전에 코딩 붐일어서 단기속성으로 몇개월 공부해서 프로그래머로 취업한 사람들이 지금 연차 조금 쌓였을텐데 거기까지가 딱 마지노선인거같음 그 이후 신입분들은 ai땜에 취업시장 발도 못붙임',
 '그니까 시니어끼리 시다를 주니어가 아니라 ai한테 시키는거잖아',
 '진짜 심각하다 ㄷㄷㄷ',
 '화이트칼라는 AI로 인한 대체가 걱정이고...블루칼라는 중국발 저가 덤핑 공세 때문에 문제고...쉽지 않다 정말',
 '회계사를 필요이상으로 많이뽑았고 회계사도 학벌을 봅니다. 지잡대 회계사들 안뽑아요. 수요보다 공급이 많은데 뭐하러 뽑습니까 그리고 AI로 프로그램 돌리고 현재 근무하는 직원들에게 좀더 전문적으로 일을맏기고 좀더 연봉을 지급합니다. 전문화 되어있으니~ 그래서 신입을 안뽑아요. 뽑을 이유도없고  벌률상담도 챗GPT나 제미나이 돌리면 자세하게 알려줘요 심지어 소장도 적어줍니다. 상담30분에 유료10-30만원 내던게 사라졌어요.',
 '회계사 걱정할 정도면 다른 업무는 이미 폭망중',
 '잘라말해서 아버지 연줄 없으면 수습기간 채용해주는 회사 없습니다.',
 '무섭다',
 '회계사는 정말 AI대체 예상 1위였죠.  역시 올것이 왔네요',
 '에구 젊은분들 취업이 점점 더 어려워지겠네요. 걱정입니다',
 '웹   프로 그래머도  5년 전에도  800 이상  20년 전에도   500  이상 벌었다   이제    제일 먼저   나가야 되는 현실',
 '회계사자격증 취득한사람 카이스트 컴공이 취업을 걱정해야해..?',
 '솔직히 지금 경력있는 회계사들도 운이조아 시대를 잘 타고나서 지금 시대에 AI를 쓸 수있는 회계사가 된거지. 지금 시대에 취직하려면 똑같이 이력서 백개써도 안될거임.',
 '세상이 정말 빠르게 변하고 있다는걸 요즘 많이 느끼는중...',
 '세상만 빨리변해가는듯 해요 너무 빨라서 소름 입니다 사람들은 세상 이상한 사람들로만 늘어가는듯 하고',
 '판사를 ai로 대체하라는 말이 판사도 사람이고 분명 정황상 억울한 상황이 있고, 특히나 타인의 의한 살생행위에 대해 피해받은 사람, 그로 인해 남은 가족들이 앞으로 살아가는동안의 감내해야 될 큰 상처들 등 그런 사안을 피해자입장에서 헤아리지 않고, 그저 법리대로만 판결할거면 정석대로 ai로 가란 뜻임. 특히, 음주운전으로 인해 사망한 억울한 죽음, 묻지마 폭행,살인 등 이러한 사건은 심신미약 ,초범 형량 감경을 없애야 함. 한 사람의 생명뿐 아니라 앞으로 남은 인생을 살아가야 할 그 가족들 또한 피해자로 엮어야함.',
 '울나라에 시험제도가 잘 못 되었다. 해외처럼 단계별 시험제도로 기회를 주는게 아니라 울나라는 떨어트리려는 시험제도 때문에  시험문항도 쓸때 없는 공부량이 많고 시대에 흐름을 따라가지 못 하는 시험제도 부터 바꿔라',
 '30년정도 일찍태어날껄  인간일자리가 점점 더 없어지네 ㅠ 집값은 미친듯이 오르고',
 '판사부터 AI로 대체되어야죠',
 '무서운  세상..',
 '현직입니다 본 영상에서 말하는 것과 같이 단순하게 Ai 자동화로 인해 저연차 회계사에 대한 수요감소로 미지정 상태가 난 것이 아닙니다. 구조적으로 20년 초반까지 업황이 피크를찍고 내리막이 예상되고 있었는데 관련당국은 업계수요를 무시하고 선발인원을 오히려 더 늘렸습니다. 업황도 안좋은데 ai 자동화로인해 저연차에 대한 수요도 감소한 효과가 겹쳐져서 미지정 상태가 발생한 것 입니다.',
 '공무원이 답인가. 벌써 공무원으로 몰리고 있던데',
 '지금은 3~5년차 회계사라고 하셨는데 Ai가 더욱 발전하고 저렇게 계속 학습시켜 주면 내년엔 시니어 회계사 업무도 도맡아 할듯..',
 '개발자 7년간 하고있는데 내가 시작할때에는  4차산업혁명이니 뭐니 하면서 진짜 개발자를 많이 뽑아다 진짜 개 븅신처럼 해도 회사에서 신입을 키워서 써야한다는 생각으로 직원을 채용했다.  코로나 터진 시점 이후로 ai가 발전하더니 프로젝트 급 줄어들고 한순간에 신입들이 취업하기 힘든 환경이되었다. 당장 이일을 15년 20년 해먹을수 있을까에서 10년 아니 5년 ... 점점 줄어드는 느낌이다 미래가 불투명해진다. 할줄아는일이 개발밖에 없어서 뭐먹고 살아야하나 고민이 크다..',
 '시작은 저년차 신입들 대상이지만 좀 더 발전하면 중간급 실무자들도 다 박살나겠구만',
 '앞으로시대는 더힘들끼다  이건 대세기때매 절대피해갈수없음.',
 '일의 전문성과 상관없이 노동집약적인 업무는 거의 ai가 대체한다고 봐야겠네 이제',
 '어쩌면 저출산이 당장은 문제지만 먼 미래를 본다면 축복일지도 모른다',
 '불과 3-4년 전만해도 저출산은 비교문화의 폐해라고 생각했는데, 이젠 정말 생존의 문제로 디폴트가 되어가는것 같다.',
 '재무직 신입 취업하려하는데 너무 안됩니다……..4년제고 학과도 세무학과고 자격증도있는데 안돼여 정말..',
 '전문직 자격증도 안심 못하는 시기구나',
 '지금은 2-3년차 회계사지만 내년은 6-7년차 정속이 아닌 무섭게 가속 중입니다. 물리AI까지 보급화되는 순간.ㅠ',
 'Ai때문도 있지만 타업종도 불경기가 심각해서 애초에 채용자체를 안함.  주변 공장단지들 식품,제조,건설,유통업 대표나 직원들 만나서 얘기해보면 최대매출 -60%빠진곳도 들어봄.  작년까지는 누구는 잘됐다는 소식이 있었는데 지금은 진짜 좋은소식자체가 아예 안 들림.  AI + 경기침체 앞으로 2~3년내에 정말 많이 변할것같음.',
 '45세 일인 자영업자입니다. 무우. 배추. 양배추.대파.오이 등등 차에 싣고 다니면서 새벽에 식당에 납품합니다. 큰돈은 안되고 집 살 능력은 안됩니다. 저보다 똑똑하신 젊은이들은 힘을 내고 꺽이지 않는 마음을 가지고 취업 성겅하길 바랍니다 . 화이팅!!',
 '인구수는 줄어드는게 맞다니깐 이 상황에서 출산율 높다?? 경쟁불지옥 대한민국됨',
 '공감 it 작년부터 조짐이상한거 업계에 모르는사람 없었지',
 '미국에 사는데요 미국도 AI 때문에 졸업생들 정말 힘들어요... 많은 한인 자녀들이 컴공이나 수학을 사용하는 직업으로 많이 빠지는데 정말 취업 힘들어요',
 '어떻게 이런 일이.....................',
 '세상에 휘둘리면 이도저도 못한다. 그냥 본인에게 집중하고 본인이 하고싶은거 하고 살아요.',
 'IT 뉴스를 안 보고 지낸  씁쓸한 결말이네요',
 '4:04 맞는 얘기긴 한데 본인 밥그릇 생각해서 사다리 차는 느낌도 나는 멘트네',
 '저출생은 그냥 자연스러운 자연의선택이네',
 '자격증으로 결정되는 직업들은 걍 안하는게 맞는듯... 미래가 없음',
 '3~4년 지나면 사무직은 다 집에 가야될 듯',
 '이걸보니 열심히 공부하고 노력해봤자 아무소용없다는 생각이듬',
 'AI라는 거대한 흐름 앞에서 자격증이 무슨 소용.. 시대를 읽는 것도 능력이거늘',
 '의사도 수술빼고 많이 비슷. 혈액검사 결과지 보여주니 너무 잘 설명해 줌. 처방약 알려줘도 설명 많고 이해도 쉬움. 병원가서 의사랑 대화해봐야 6~8문장으로 끝임. 의사 바빠보여서 질문도 많이 못함.',
 '병찬씨 붙고 나니까 밥그릇 지킬라고 이제는 덜뽑는게 맞다!!! 하시네 ㅋㅋㅋㅋㅋㅋㅋ',
 '택배 기사나 하자… 몸 써야 된다 이젠',
 '저렇게 열심히 공부했는데 남일같지않고 마음이 아프네요..',
 '담달에 리니지 클래식하니까 회계사 변호사 세무사 분들 오픈런 ㄱㄱ',
 '판사를 AI 가 해야하는 이유',
 '에이아이 사용해도 오류 진짜 많이 나오던데... 다시 확인을 해야하던데',
 '5년 뒤에 자기계발용으로 회계사 자격증 따둬야겠네',
 '4:05 본인은 많이 뽑을때 합격해놓고 이제는 더 뽑지말래 ㅋㅋㅋㅋㅋㅋㅋ',
 '자급자족 농사가 답이다.',
 '회계사 도장을 받아야하는 일도 없애면된다',
 '큰일이네요',
 '근데 회계사는 연도바이연도가 원래부터 좀 심했음. 어떨 땐 4대 법인 전체 티오가 회계사 시험 합격자 총합보다 많아서 그냥 4대 전부 원서 넣으면 무조건 4대 회계법인 합격인 연도도 있었고 어떨 때는 스카이 상경계 - 회계사 시험 합격이라는 초엘리트 코스 밟지 않으면 이름 들어본 회계법인에는 못 들어가는 그런 해도 있고 그랬음. 뭐 이번엔 좀 심각하긴 함',
 '일론이  미래에  인간의사보다  로봇의사가  더  치료  잘할거라네요',
 '모든 산업이 똑같아요ㅠ 미국 금융권에서 일하는데 금융, 컨설팅, 테크 채용은 박살났고 그나마 포지션 열린데는 의료 정도..? 당장 저만 해도 몇년 전에 10명 팀이 1달 동안 하던 일을 지금은 저 혼자 2주만에 하고 있어요. 그나마 90년대생까지는 어떻게든 밥벌이 할 경력이라도 쌓였는데 00년대생 신입들은 자리가 아예 없어요...',
 '시간의 문제일뿐 안전한 직업은 없다.',
 '앞으로는 없어지는 직업을 미리 알아보고 공부해야되고 자격증도 따야됨',
 '책상머리에 앉아서 컴퓨터나 끄적대는 일들은 다 없어질것임. 몸으로 해야만하는 일들만 인간에게 남을것임.',
 '카이스트 복수전공자가  스타트업에 겨우 취직햇다고? ㄷㄷㄷㄷㄷ',
 '앞으로는 미래지향적으로 공부 방향을 전환',
 'AI로 가장먼저 세무사 회계사 없어짐',
 'cpa합격자면 여기서 댓들로 걱정하는 분들보다 나은 인생이니 걱정 안하셔도됩니다',
 '회계사 수를 줄이는게 아니라 수임료를 낮춰야지',
 '컴공 나왔는데 ㄹㅇ 답없어서 공기업 자리 선점하러 왔습니다. 당분간은 먹고살 수는 있겠네요',
 '초딩~대졸까지 투자한 시간과 돈 대비 얻어지는 결과물이 이러면 공부가 의미가 있는 시대야? 정말 힘든 세상이네',
 '진짜 충격적인게 제미나이 실습으로 면접봤는데, 카이스트출신이라도 생성형 AI활용도가 낮은 지원자보다, 일반고등학교 졸업하고 생성형 AI이용을 극대화해서 결과물을 제출한 사람중에 후자가 뽑혔다는게 더 충격적입니다.  모 스타트업에 실제 있었던 일입니다.',
 '지금 공대 컴공 전공자 작살 나는 중....',
 '이런거 보면 확실히 AI기업이나 주가에 거품이 끼었을지는 몰라도 AI가 생산성 향상에 도움을 둔다는 것 자체는 진실이라는걸 알 수 있음',
 '60년대 70년대생들이 최고로 운이 좋음...',
 'AI가 못하는 손기술있는 배관공, 타일공들이 대세가 된다잖아',
 '04:06 와.. 황병찬님 본인 회계사 일하고 있다고 자기는 일 잘릴일 없으니까 신입들 많이 안 뽑아도 된다는 말을 하시네요. ㄷㄷ',
 '앞으로 회계사는 공인 중개사랑 똑같은 취급 된다.',
 '지금 회계사 걱정할때가 아니다.다들 젓됐어.',
 '4:1 회사가 지금 200:1 됬음 겨우 디자이너 한명 뽑는데 it 아이티 망한지 오래임 ㅎ 잘할 필요없는 ai가 다해서 정치 잘해서 윗사람한테 잘보여서 나오지마셈',
 '신입 변호사, 회계사가 몇날 몇일을 자료 모으고 정리해야 할 일을 몇 초면 끝내버리니..',
 '회계사, 세무사 등 숫자관련쪽은 대체가 쉽죠. 3명이 하던걸 혼자 할 수 있게 되는거고. 나중에는 일반인들도 AI와 상담하면서 회계사, 세무사에 의존도가 낮아 질거고.  모든분야가 조금이라도 영향을 받을 것 같네.',
 '현직 회계산데 ai는 핑계일뿐, 수요예측 안하고 회계사 합격자수 미친듯이 높여놓고 업계 자체가 덤핑으로 곪아가고 있는데,  욕심많은 윗대가리 새끼들이 스탭들 싸게 부리고 갈아치울라고  많이 뽑은게 이 사단이 난거임 아직까지는 ai는 거들뿐임.. 앞으로는 ai때문에 진짜로 업계가 힘들어질 날도 오긴 하겠지만..',
 '화장품 사업 하는데 직원 3명 필요한 일을 3만원 gpt가 해줌. 느끼는건 브랜드를 만들고 ai활용해사 키우는게 답. 유통, 광고, 회계, 번역 통역, 컨텐츠 등 점점 직원 필요 없어짐',
 '힘들게 공부했는데 취업이 않되니  젊은이들이 희망이 없는나라  ㆍ싸움질하는 국회의원 숫자나 줄이지',
 '가계부 앱 받아서 쓰는데 졷같은 광고 계속떠서 내가 앱만들어서 쓰고 있씀. ㄷㄷㄷ 이런 시대임. 하다못해 이런것도 안하면 그냥 밑바닥 되는거임.',
 '하....... 작년 컴공 졸업생 진심 개빡침....',
 '하 진짜 전공을 뭐해야하는거냐 아예 이젠 대학이 의미가없는거냐 취업은 어케하라고 ㅠㅠㅠ',
 '황당하겠다',
 '이래서 요즘 유튜브에 세무사들 자극적으로 세무조사 세금폭탄 어쩌고 하는 영상들이 많아진거같음',
 '사람이 필요없는시대임 근대 왜자꾸 애를 낳으라고 하는지 몰겠음',
 '생각의 속도를 인간이 따라가지 못한다. 더빨리 변할것이다. 우리가 느끼기도 전에',
 '정말 우려되는 현실이다.',
 '예상은 했지만 요즘 기술 발달하는거보면 진짜 무서울 정도... 앞으로 직업 생태계가 완전히 바뀔거라는 예상하고 있는데 이젠 사람 5감 만족 시키는 체험형아이템이나 아이디어가 필요한 분야가 커질거로 예상.. 숙련기술의 경계 자체가 없어지고 있음..',
 '꼭 자기코앞에 떨어져야 아~~ 이러고들 있는지   미리미리 들 생각 못하는지~~~',
 '지가 땃으니까 줄여야 된댘ㅋㅋㅋㅋㅋㅋㅋㅋ',
 '이젠 우리 스스로 다 필요없는 인간들이 되어가고 있는 듯 ㅠ',
 'IT업계는 진짜 진작에 AI에 다 먹힘;; 소프트웨어쪽은 특히나 심한데 제일 심한게 바로 게임업계임... 진짜 끝났음;;; 신입 및 저연차뿐만이 문제가 아니라 경력직들도 회사 망하는 순간 구직난임...고연차는 능력 좋은 사람도 안뽑는 시대임 ㅋㅋㅋㅋ',
 '부모들이 정신차려야됨..애들 대학 보낼 생각하지말고 그 돈 아끼고 빨리 자기만의 기술을 배우게 해야됨',
 '회계사랑 세무사 완전 존망해가는중 이 공부하시려는 분들은 시작도 하지마세요 인생 좇될수있음',
 '아주 재밌는 장난: 10년 넘게 공부 시킨 다음에 AI로 대체하기',
 'AI 시대, 질문이 곧 무기다. 두리뭉실한 질문엔 AI도 평범해진다. 페라리를 타고 출퇴근만 할 건가? 제대로 질문 하는 자만이, AI를 진짜로 달릴 수 있다.',
 '변호사 세무사 회계사 전부 망했지 뭐',
 '사람 한명 가치가 H200한장에도 미치지 못해지는시대',
 '회계사를 합격할 정도면 다른 시험도 충분히 합격해서 다시 시작할 수 있답니다',
 '자기가 그자리차지하고있다고해서 후배들자리없애려는 표독한 사람들',
 '미국에서 일반 회계사는 매번 계약직 생활이고  세무사는 동네 마트에서  책상 하나놓고 영업하며 상담함.',
 '개인이 단체가 나라가 발버둥치고 막아보려해도 이건 어쩔수없는 현상이다.. 에휴.. 이제 어떻게 살지..?',
 '젊은애들은 살수가 없는구조가 됐구나 노가다나 농업만 해야하는거구만',
 '전문직 고시생 여기없나 ...... 아 살려주셈',
 '4:00 붙은사람이 이런얘기하면 안붙은사람이 섭섭하지',
 '퇴사는 진짜 미친 행동이다 나가면 들어갈 곳이 없다',
 'ㅋㅋ 병찬씨 당신 자리두 얼마 안남았어요  ㅋㅋㅋㅋㅋ',
 '2:20 고객사 회계자료를 걍 ai에 넣어버린다 ??  ㅋㅋㅋ  유출 될거라고는 예상 안하나 ? 그리고 난 합격했고 ai가 발달됐으니 합격자 줄이라는건 뭔 심보여 ㅋㅋ',
 '괜히 배관공이 미래에서는 제일 고소득직군이라 하는 이유가 있음',
 '나완 상관없다고 편해졌다고 안심하면 안됨... 결국은 모든 사람에게 이득보단 피해사례가 더 많아질것임 AI는 정보검색등 적당 수준에서 선을 그어야 할듯',
 '현실 부정하지 말고 빨리 공장 노가다 하러가라...',
 '대학교 막 졸업하신 분들은 진짜 어렵겠다. ㅜㅜ. 일단 취직하시고 봐야합니다.. 안그러면 기회가 더 없을거에요..',
 '일론머스크가 의사 나가리도 언급했지 ㅋㅋ 한나라의 최고의 인재가 의대만 가는데, 미래가...',
 '다음 타겟은  통역관련업무 입니다',
 'ai 문제 없다던 전문직들 튀어나와보세요',
 '현직 공무원이라 그나마 다행이네요,,,신분은 보장되니.,.요즘 다시 공무원 인기가 저 들어올때처럼 20%이상 상승했다고 들었는데 앞으로 더 힘들듯...',
 '이제 잘리면 청소업체에 들어가야겠다 Ai가 청소는 못하겠지ㅋ',
 '로펌도 비슷한 상황입니다. 저희로펌 하루 찍어도 지금 IT기업이랑 동일한변화가 생겼습니다. 기초법령, 판례리서치, 이를통한 확률검토 전부 AI가 즉각적으로하는 일들이라 주니어 고용변호사님을 시켜서 받는것보다 시간이 훨씬 절약되서 굳이 뽑을 이유가 사라집니다. 같은 법조계선배로서 진짜 안타갑네요',
 '조아써  이제  판사도 적용시켜보자',
 '10여년 전부터 ai로 가장 먼저 대체될  직업군 이라고 시끄러윘는데.',
 '회계사만 그런게 아니야.. 문제는 AI가 사람만큼 아니 보다 더 정확하고 일잘한다는거지',
 '약사는 ㄹㅇ ai타격이 크겠다',
 '잔인한 장난이다 장기간 공부시키고 직업은 ai로 대체되기',
 '운이 없다고 할 수 밖에. 그런데, 곧 다른 직업들도 따라갈거 같아서 미래가 참 어찌될지.',
 '아 내 아들 일같아 마음 아프다 ㅠㅠ 청년들 일자리 많아졌으면 너무 좋겠다',
 '대학 졸업장이 큰 의미가 없어지는 세상이 온거다. 그걸 전 사회가 깨닫는데 5년은 걸리겠지만.  직업학교역할 하던 대학들은 문 닫는다.',
 '청년실업이 심각하다. 정부는 정년연장에만 관심갖지말고 취업에 대한 대책 먼저 마련해라',
 '시대의 필요에 따라 직업군도 당연히 바뀌지...',
 '그와중에 되는 회계사들은 코딩, AI배워서 어떻게 실무에 적용하고 기존 프로세스 개선할 수 있는지 사이드프로젝트 만든걸로 어필해서 취업하더라. 안된다고 징징댈게 아니라 왜 예전의 방식으로는 안되는지, 어떻게 하면 기회를 잡을지 정확하게 진단해내면 누구나 할 수 있다는 방증.',
 '여기 댓글들 왜 이렇게 꼬였냐 사람들이',
 '04:09 사회 트렌드? ㅋㅋㅋ 내 밥그릇은 뺏으면 안되지~ 라고 입은 삐뚤어져도 말은 똑바로 솔직하게 해야지 ㅋㅋㅋㅋ',
 '5년..진짜 스스로도 미치겠네',
 '애초에 많이 뽑은 게 회계기준 개정으로 갑자기 인력 필요해져서 아닌가?',
 '국내 중소기업 다죽어가는데 뭔 회계사고 ㅋㅋㅋㅋ 손님들이없는데 뽑을리가',
 '그대들의 성실함을 인정합니다! ㅎ',
 '세상이 많이 변했어요 다른 직업들도 많이 없어지겠죠 그 과정중 하나일뿐 안타깝네요',
 '판사가 왜필요하노 법대로안하는데 AI로대체해라',
 '지금은 프롬프트 라도 잘짜는게 능력이라지만.. 이 조차도 한 5년쯤 지나면 걍 생가나는 대로 지껄이면 그 프롬프트 조차도 짜주는 수준으로 될거임. 지금 부장이 신입급한테 프롬프트급으로 조리있게 업무지시 안하잖어?.. 걍 알잘딱깔센 같은 느낌으로 25년도 분기별 매출실적 예쁘게 정리해봐 정도 레벨만 말해도 돌아가는 수준까지 몇년 안남음..',
 '인간이 필요없어짐. 앞으로 인간이 할수 있는 일은 밥먹는 거 외에 없음',
 '상담직도 사라질수도.. gpt한테 상담해봐라  부끄러운것도 없고 나름 그사람 감정 이해하고 객관적인 답해줌 ㄷㄷ',
 '진짜 한국은 저출산이 축복이다 ㅋㅋㅋ 이런 상황에서 출생아수 70만명이면 취업 못한사람들 수두룩 사회가 불안할듯',
 '이거보니 아들 공부하란 소리가 안나오네요',
 '8:22 지원을 5개밖에 안했다는 거 자체가 이상했는데 카이스트.. ㅋㅋㅋ',
 '변호사도 없어질듯 고소장이랑 의견서를 ai가 직접 작성해줌',
 '젊은 세대가 참으로 딱하고  안타깝습니다 ㅠㅠ',
 '작곡도도 살아남기.힘듬',
 '판검변호사도 조속히 AI로 대체해야 합니다ㅡ',
 '이제 시작인가 지금 정치권이 자기 밥그릇 싸움할 때가 아닌 것 같은데 말야 국민들도 이런 사회적 문제를 더 심각하게 받아 들여야 한다. 누굴를 감옥 보내고 이런건 우리의 삶과 아무 소용없는 것들이다. 더 무서운 게 다가오고 있는데 쓸모없는 일에 우리가 몰두하고 있는 게 아닌가를 생각할 때인 것 같다.',
 '의사도 ai로봇 수술기로 대체 될것이다. 이미 의료기본사항들은 ai가 터득다함.',
 'Ai를 이기지말고 그냥 이용하자 그냥 창업해 물론 힘들겠지만 그냥 새로운걸 창조해내자',
 '자기는 AI로 대체되기 싫고 신입 회계사들만 대체하고 싶어서 회계사 공급통제하자고 주장하는게 얼마나 이기적인가. 지들은 1000명씩 뽑을 때 붙어놓고는ㅋㅋㅋ',
 '심각한 위기라고 생각되네요..에휴  우리세대는 그럭적럭 살아왓다만  내 손주세대는 정말 걱정스럽다.. 결국은 몸으로 때우는 일만이 사람이 직접해야 하는것만이 살아남겟네..',
 '인생은 선택을 잘해야함. 아무리 머리좋고 노력 많이해도 세상 흐름 못읽고 잘못된 선택하면 도태됨.',
 '출산하면 안되는 시대 이제는 결혼해도 자식 낳지말자 로 가야함. 금수저나 상위 몇프로만 자식 낳자. 흙수저는 낳지 말자. 생각없이 낳다가 내 자식 직업 없으면 어쩌려고 현실을 바로 보자 ~',
 '이런영상보면 중국인지 한국인지 모르겠다.상황이 똑같네.',
 '사람에 의한 건 인공지능으로 대체 못함.',
 '안됐지만 눈을 돌리셔야합니다. 몸쓰는 일에도 가능성을 열어두시길..',
 'AI로 판사부터 대체해라.',
 'ai와  로봇의  조합은  육체노동도  상당수  대체가능할것. 로봇이  자율주행차에서  내려서  택배기사처럼  배달하겟지.',
 '구구단 5년동안 외웠는데 계산기 나온꼴',
 '2.3백이라도 벌어서 ai기업이나 미래 산업에 투자를 해서 이 죽음의 나선을 벗어나야지. Ai랑 싸울려고 하면 안됨. 거대한 흐름에 편성하고 자본시장을 인정해야지 범재가 노동으로 역전할수 있는 세상은 이미 지났음.',
 '그동안 숫자놀음 해주고 과도하게 받앗던거지 ai 몇초면 되는걸',
 '우리아이들은 무슨일을 하고 살아야할까요 걱정이네요..',
 '공인회계사 난이도는 거의 3고시 다음 아닌가..? 얼마나 속이 뒤집어지고 울화통이 터질지 이해 가 간다.',
 'ai가 마지막까지 대체하지 못하는 직업 중에 하나가 미용사입니다.',
 '이미 코로나전부터도 회계사,변호사 AI는 나왔었음. 그냥 부정하고 싶어서 "우리 직종은 절대 AI가 대체 불가하다.그게 한국어로 번역과정에서 경리를 회계사로 오역한거다" 라고 합리화 하고 있었을뿐. 시간문제인데 한국은 노조가 있어서 시간 좀 걸릴듯',
 '나도 회계사지만, 어쩔수 없다. 시대가 요구하는 수준으로 나를 끌어올려야 한다. 세상을 탓하지말고 자신의 부족함을 탓해야~ 자격증 하나로 평생 먹고 살려는 생각부터 버려야 한다.',
 '결국은 기술직이 살아남겠다',
 '다큐의 제왕 공영방송 KBS 잘 봤습니다.',
 '사람이 꼭 필요한 현장 기술직  노가다 등이  가장 오래 살아남을 직종이죠ㆍㆍ ㆍㆍ  로봇으로 대처가 가능한 건 공장의  일이고',
 '그냥 빨리 ai로 대체할수있는건 대체하고 기본소득줘라',
 '억울해도 어쩔수없어요. 시대흐름을 따라가야죠. 다른일 알아보세요.',
 '수습도 안 해 줄 거면 시험 자체를 없애라',
 '전화 교환원이 사라진거랑 같은맥락임…앞으로 저런게 점점 더 늘어날꺼야 빠르면 1년 길어도 10년…',
 '중소 지원 안하냐는 말하는 뉴스 댓글들 많이봤는데 이게 현실임 ㅋㅋ 중소조차 한명뽑는데, 과제, 시험, n차 면접 하는 시대이더군요 막상들어가면 시스템은 중소라 당연히 없을테고 .. 청년 세대는 시작을 못하고 중년 세대는 언제 대체될지 모르고.. 근데 이게 걱정인게 시니어가 하루아침에 만들어지는게 아닌데 다음 시니어 세대가 되었을때 주니어가 없으니 ..  일본의 잃어버린 30년이 생각나네요',
 '회계사 되고 싶어서 cpa 시험 준비하고 있는데 가끔은 막막해질 때가 많네요..',
 'AI를 활용해 더 성장하는 사람이 있고 도태되는 사람이 있음 시대의 흐름을 읽고 잘 적응해 살아남아야 함',
 '대학 타이틀만으로 취업하던시대는 또 언제냐? 내가아는건 20년전에도 그런적은 없다는거임. 그때도 코딩테스트 다 하고 인재인지 벌래인지 가려냈음',
 '젠슨황이 전기기사 배관공은 ai시대에서도 살아남는다 그랬음',
 '몸으로 때우는 시설관리나 현장직업이 끝까지 살아남을듯',
 '머해먹고 사냐?   대학도 굳이 다닐필요도 없을듯 한데...',
 '05학번인데 저희 졸업할 때가 회계사 막바지 전성기였다고 생각합니다. 2010년대부터 앞으로 사라질 직업 상위권에 회계사가 꾸준히 나오기 시작했거든요. 15년만에 일반인도 체감할 수준으로 나타난 거구요. 그런데 모두가 바라는 법조계의 AI대체는 기득권 때문에 절대 현실화되진 않을 것 같아요.우리 나라는 문과가 정치를 주도하는 국가인지라...',
 '공공기관 행정직 입니다. AI가 업무 판도를 싹 다 바꿔놨습니다. 사업 제안서, 결과, 발표자료 등 예전에는 20~30분 걸릴 작업을 지금은 5분이내로 그것도 더 좋은 퀄리티로 만들어냅니다. 무결성 데이터 관련해선 아직 다시 확인해야 되지만, 글짓기 같은건 내가 찾는 범위+속도와 비교도 안되게 AI가 더 빠르고 광범위하게 찾으니 더 논리적이고 위에 보고할때도 설득이 훨씬 더 빠릅니다. 업무뿐 아니라 일상생활까지 다 바꿔놨는데요. 최근에는 15년 동안 붓고 있던 종신보험도 계약서 PDF 딱 올려서 현재 이걸 유지해야 되나 특약변경을 해야되나 그만 넣어야 하나 하는 판단도 보험설계사 이상 수준으로 30초 내에 정리를 해서 보여줍니다. 이게 얼마나 무서운거냐면, 지금도 AI를 잘 안쓰는 사람들이 많아요. AI를 100% 잘 활용하는 사람과, 조금 써보는 사람과 아예 안쓰는 사람 간의 격차가 엄청나게 벌어진다는 겁니다. 지금도 저희 회사만 봐도 AI 잘 활용하는 직원과 안쓰는 직원 차이 엄청 납니다. PC에 익숙하지 않은 부장 이상 세대에선 AI 이전에도 젊은 직원들과 격차가 있었는데 지금은 완전 바보가 되어 가는 중이에요.',
 'Ai 창작물 무단학습 규제 법안좀 만들어주세요...작품이나 디자인 저작물 학습 극혐입니다',
 '가장먼저 ai 대체가 시급한 직업군이 바로 판사, 검사인데 말이지...',
 "It's not just Korea",
 '이런논리라면 의대도 줄여야됨 증원한다고 소란피우지말고',
 '공대나와서 코딩만할줄알면 취업보장되는시절이 있었는데 몇년사이에 이렇게 바뀔줄이야…',
 '04:00 저 회계사분은 적게 뽑아야 한다고 할때가 아닌데 저러다 완전 AI로 대체되면 어쩌려구 저러나…',
 '문과 전문직 자격증은 3년안에 싹 다 없어질겁니다.',
 '한공회가 쳇지피티로 데이터를 정리한다고? 정보보안법 위반 아니냐?',
 '인문계는  문 닫는다.',
 'AI가 프로그래밍이나 자료 정리를 도와줘도 결국 누군가는 AI를 다뤄야 하기 때문에 사람이 필요하긴 한데 경력자는 필요하고 신입은 필요가 없게 되는 상황. 근데 프로그램도 그렇고 회계도 그렇고 정형화된 업무나 데이터가 아닌 경우는 물론이고 최종적으로는 사람이 돌아가게 해야 하기 때문에 사람 없이는 안됨. 주니어 레벨의 필요가 줄어들긴 하는데 그냥 AI 핑계로 감원하는 거 같음.',
 '이기주의봐라. 출입문은 줄이고 법령으로 철밥통은 보호받고 싶다고? 회계사들 이기주의봐라.',
 '백날 천날 면허 하나로 날먹하는 의새들이 이상한거 ㅋㅋ 최소 5년에 한번씩 면허 갱신 시험제도 도입해야함',
 '이제는 감정 이용하고 몸 쓰는 직업이 오히려 수요인듯',
 '회계사/변호사/세무사가 몇년안에 없어질 직업이라고 하던데...;;;',
 '회계사 도장받아야 되는 일 그냥 기관 담당자가 지피티로 엑셀에 함수넣어서 돌려보고 오류없으면 통과시키자. 회계사 진짜 필요없음',
 '카이스트 나와도 취업걱정을 하다니..진짜 전기공,배관공 해야되나봐...',
 '디자인쪽도 마찬가지 채용공고가 2026년 들어서서 급격하게 줄음 그나마 올라오는것도 지원자가 100명이 넘음....5인미만 중소기업인데도 100명 넘게 지원함...다른길을 도전해야되나 심란하다 매일매일이',
 '대학에 갈 필요가 없어졌어. 이젠 예체능, 감정서비스, 심리상담가등 서비스업과 손노동만이 살아남을듯.',
 '분석이 완전 틀렸는데..ㅋㅋ AI 때문에 회계사 일자리가 없는게 아님 회계감사 가격후려치기 때문에 법인들 이익이 줄고, 그로인해 신규채용이 줄어든거임',
 '어찌하리오~~시험하실정도로 머리가 좋으신분이니까 인공지능에 맞는 분야 찾아서 다시 시작 가능하실듯 능력이 별로 없는  나 ...슬프네',
 '세상과 경제가 변하면서 직업이 사라지고 생기기도 한다.  거기에 맞추어 살아 남는 수밖에..,',
 '회계사 자격 있으면 먹고 살 수 있다. 자기 사업을 시작하는 것도 괜찮다. 대부분은 용기가 없어 낭떨어지 못 떨어진다. 그러나 용기가 있는자는 자생하여 더 강해진다.',
 '와 진짜 꼬우면 일찍 태어나야했구나',
 '간 초음파 사진 AI에게 넣고 물어본 내용과 이후 병원 진료일에 의사한테 들은 이야기가 똑같... 이젠 의사의 역할도 사라질 판...',
 '마지막 말이 핵심. "컴퓨터 앞에 앉아서 일하는 사람들은 다 위기에요." !!!',
 '뭔가 착각하는게 회계사 자격증이 회계감사 업무에만 필요하다고 보는 모양이지.?? 미국처럼 일정 점수 이상이면 모두 합격시켜주고 합격 후 진로는 본인들의 능력으로 가는거다.. 이 놈의 나라는 왜 자꾸 제한을 두어서 경쟁을 막으려 하는지 모르겠다..',
 '앞으로 회계사 세무사 필요없다 AI 발전이 상상을 초월한다 사람보다 더 탁월하다 무섭다',
 '현직 회계산데 빅펌에서 미취업 신입회계사가 많아지는 이유는 AI가 아니라 몇년동안 지속된 증원때문입니다. 이런식으로  호도하지마세요 방송국들아',
 '이젠 어떤 직업을 찾아야하나.....',
 '이건 또 뭐냐...진짜.. AI떄문 맞나?',
 '사실상 10년안에 없어질 직업 : 회계사,세무사,법무사,변리사,행정사, 약사, 전화응대원, 몽키 코더 등등,  업무가 정형화된 반복작업만 하는 것들.',
 '제일 쓸데없는 걱정이 전문직 연예인 걱정임 ㅋㅋㅋ 전문직 걱정하는거 아니야~ 약코 적당히 해라',
 '스포츠 선수는 대체 불가 겠네요 .',
 '진짜 큰문제임 회계사 세무사는 5년내 공인중개사 정도와 비슷해짐 ai를 정통으로 얻어맞음',
 '세무사 회계사들 솔까 10분상담에 20만원씩 잘 받아쳐먹었자나 그동안 그것도 현금으로  최근에 세무사상담 5분에 15만원 주고 받았는데 챗지피티가 알려준 거보다 덜 정확하드라 그냥 인간에게 들으니 안심한 정도 그이상도 이하도 아니더라  회계사 세무사 특히 세무사들은 국세청에서도 ai돌리면 뭐 가공경비 다 잡아낼테네 필요없어지몀서 투명해질듯',
 '이렇게 될걸 모르는게 이상한거 아냐...? 저거 붙을 머리로',
 '옛날 전화번호부를 전부 외우는 시험이 있다고 가정했을때 난이도는 아주 어렵겠지만 메모리 장치의 상용화로 쓸모가 없음. CPA도 AI의 등장으로 비슷한 흐름으로 가는거지... 근데 저분들은 뭘해도 될 분들이라 제 길을 잘 찾아가시리라 믿음.',
 '판사도 대체해라 솔직히 3분의 1만 써도 될듯',
 '기타 사무직은 가만 냅두고 전문직인 회계사가 먼저 사라질거라는분들 ㅜㅜ 저기요. 저희들이 가서 보는게 님들이 뭔짓 해놨는지 보는거에요ㅋㅋㅋ님들이 헛짓거리 해놓은거는 ai도 몰라요. 태반이 세상에 없는거라서요ㅋㅋ회계업계가 ai로 다 장악되려면 우선 일반 회사자체가 전부 표준화된 전산화가 가능해야합니다. 지금 회계사 미지정은 문정부때 갑자기 확 늘려놨는데 그때는 내부회계도 있었고, 코로나로 돈풀려서 기업도 호황이고 그랬었는데, 내부회계 다구축해서 더이상 일없고, 경기안좋아서 대규모 채용안하는 이유가 더커요.',
 '다른 업종은 모르겠지만, 현재 회계사가 AI로 대체되는 것이 아니라, 파트너 등 임원들이 프로젝트를 따오기 위해서 가격을 후려치는 저가 수임이 만연화되었고, 얼마 되지 않는 계약금으로 일을 하려다보니 충분한 인원을 투입하지 않고 있는 상황입니다. 저가 계약으로 3명이 해야 하는 일을 1명이 하다 보니, 최근 회계빅펌에서 자살하거나 젊은 나이에도 병으로 사망하는 사례가 나오고 있고, 회계사들은 새벽 2시 퇴근이 빠른 퇴근이라고 할 정도의 극한 환경에 내몰리고 있습니다. AI는 약간의 보조 도구일 뿐, 회계사의 업무를 중단기내  대체하기에는 아직 그 수준이 너무 미흡합니다. 현재는 AI 핑계로 고위급들이 투입 인력을 무리하게 급격히 줄이고 있을 뿐, 실제 사람이 해야할 일은 그대로 남아 있는 것이 진짜 문제입니다.',
 '단순노동이 제일 늦게 대체될수밖에 없는게 가장 싸거든 세상이 무너지기 시작한다',
 'ㅋㅋㅋㅋㅋ이런 뉴스보고 좋아라하는 사람들은 몸쓰는 사람들이 태반인가? 자영업자라던지 일용직이라던지',
 '회계사 채용이슈는 향후에는 당연히 AI영향이 있을 수 있겠지만, 당장 올해로 한정하면 90% 이상 정책실패의 문제임. 현업에서 AI가 뉴스텝 업무를 대체한다? 아직은 단순 가공업무의 보조적인 역할일뿐이지, 당장 AI한테 조금만 복잡한 회계 레퍼런스 물어보면 말도안되는 조항 가지고 옴. 오픈소스 사용하기에는 기업자료 보안이슈도 있고.. 회계사 수요는 기업회계랑 내부회계에 대한 규제정도가 강해지면 회계법인 수임료가 올라가고 회계사 채용이 늘어나는 구조인데, 지정감사 호황 몇년 지나고 기업 불경기 겹치니까, 죽도록 경쟁입찰 해서 단가가 낮아져서 걍 채용을 못하는거..',

In [11]:
len(clean_data)

1146

In [12]:
ko_stopwords = [
"아","휴","아이구","아이쿠","아이고","어","나","우리","저희","따라","의해","을","를","에","의","가","으로","로","에게",
"뿐이다","의거하여","근거하여","입각하여","기준으로","예하면","예를 들면","예를 들자면","저","소인","소생","저희",
"지말고","하지마","하지마라","다른","물론","또한","그리고","비길수 없다","해서는 안된다","뿐만 아니라","만이 아니다",
"만은 아니다","막론하고","관계없이","그치지 않다","그러나","그런데","하지만","든간에","논하지 않다","따지지 않다",
"설사","비록","더라도","아니면","만 못하다","하는 편이 낫다","불문하고","향하여","향해서","향하다","쪽으로","틈타",
"이용하여","타다","오르다","제외하고","이 외에","이 밖에","하여야","비로소","한다면 몰라도","외에도","이곳","여기",
"부터","기점으로","따라서","할 생각이다","하려고하다","이리하여","그리하여","그렇게 함으로써","일때","할때",
"앞에서","중에서","보는데서","으로써","로써","까지","해야한다","일것이다","반드시","할줄알다","할수있다",
"할수있어","임에 틀림없다","한다면","등","등등","제","겨우","단지","다만","할뿐","딩동","댕그","대해서",
"대하여","대하면","훨씬","얼마나","얼마만큼","얼마큼","남짓","여","얼마간","약간","다소","좀","조금","다수",
"몇","얼마","지만","하물며","또한","그러나","그렇지만","하지만","이외에도","대해 말하자면","뿐이다","다음에",
"반대로","반대로 말하자면","이와 반대로","바꾸어서 말하면","바꾸어서 한다면","만약","그렇지않으면","까악","툭",
"딱","삐걱거리다","보드득","비걱거리다","꽈당","응당","해야한다","에 가서","각","각각","여러분","각종",
"각자","제각기","하도록하다","와","과","그러므로","그래서","고로","한 까닭에","하기 때문에","거니와",
"이지만","대하여","관하여","관한","과연","실로","아니나다를가","생각한대로","진짜로","한적이있다",
"하곤하였다","하","하하","허허","아하","거바","와","오","왜","어째서","무엇때문에","어찌","하겠는가",
"무슨","어디","어느곳","더군다나","하물며","더욱이는","어느때","언제","야","이봐","어이","여보시오",
"흐흐","흥","휴","헉헉","헐떡헐떡","영차","여차","어기여차","끙끙","아야","앗","아야","콸콸","졸졸",
"좍좍","뚝뚝","주룩주룩","솨","우르르","그래도","또","그리고","바꾸어말하면","바꾸어말하자면","혹은",
"혹시","답다","및","그에 따르는","때가 되어","즉","지든지","설령","가령","하더라도","할지라도",
"일지라도","몇","거의","하마터면","인젠","이젠","된바에야","된이상","만큼","어찌됏든","그위에",
"게다가","점에서 보아","비추어 보아","고려하면","하게될것이다","비교적","보다더","비하면",
"시키다","하게하다","할만하다","의해서","연이서","이어서","잇따라","뒤따라","뒤이어","결국",
"의지하여","기대여","통하여","자마자","더욱더","불구하고","얼마든지","마음대로","주저하지 않고",
"곧","즉시","바로","당장","하자마자","밖에 안된다","하면된다","그래","그렇지","요컨대",
"다시 말하자면","바꿔 말하면","구체적으로","말하자면","시작하여","시초에","이상","허","헉","허걱",
"바와같이","해도좋다","해도된다","더구나","와르르","팍","퍽","펄렁","동안","이래",
"하고있었다","이었다","에서","로부터","함께","같이","더불어","마저","마저도","양자","모두",
"습니다","가까스로","즈음하여","다른 방면으로","해봐요","습니까","했어요","말할것도 없고",
"무릎쓰고","개의치않고","하는것만 못하다","하는것이 낫다","매","매번","들","모",
"어느것","어느","갖고말하자면","어느쪽","어느해","어느 년도","라 해도","언젠가",
"어떤것","저기","저쪽","저것","그때","그럼","그러면","요만한걸","저것만큼",
"그저","이르기까지","할 줄 안다","할 힘이 있다","너","너희","당신","설마","차라리",
"할지언정","할망정","구토하다","게우다","토하다","메쓰겁다","옆사람","퉤","쳇",
"힘입어","그","다음","버금","두번째로","기타","첫번째로","나머지는","그중에서",
"견지에서","형식으로 쓰여","입장에서","위해서","의해되다","하도록시키다","뿐만아니라",
"전후","전자","앞의것","잠시","잠깐","하면서","그러한즉","그런즉","남들","아무거나",
"어찌하든지","같다","비슷하다","예컨대","이럴정도로","어떻게","만일","위에서 서술한바와같이",
"인 듯하다","하지 않는다면","만약에","무엇","어느","어떤","아래윗","조차","한데",
"그럼에도 불구하고","여전히","심지어","까지도","조차도","하지 않도록","않기 위하여",
"때","시각","무렵","시간","어때","어떠한","하여금","네","예","우선","누구",
"누가 알겠는가","아무도","줄은모른다","줄은 몰랏다","하는 김에","겸사겸사","하는바",
"그런 까닭에","한 이유는","그러니","그러니까","때문에","그들","너희들","타인","것","것들",
"위하여","공동으로","동시에","하기 위하여","어찌하여","붕붕","윙윙","엉엉","휘익",
"오호","어쨋든","하기보다는","놀라다","상대적으로 말하자면","마치","아니라면","쉿",
"그렇지 않으면","그렇지 않다면","안 그러면","아니었다면","하든지","이라면","좋아",
"알았어","하는것도","그만이다","어쩔수 없다","하나","일","일반적으로","일단",
"한켠으로는","오자마자","이렇게되면","이와같다면","전부","한마디","한항목",
"근거로","하기에","아울러","않기 위해서","이 되다","로 인하여","까닭으로",
"이유만으로","이로 인하여","이 때문에","알 수 있다","결론을 낼 수 있다",
"으로 인하여","있다","관계가 있다","관련이 있다","연관되다","에 대해","여부",
"하느니","하면 할수록","운운","이러이러하다","하구나","하도다","다시말하면",
"다음으로","에 있다","에 달려 있다","우리들","오히려","하기는한데",
"어떻해","어찌됏어","본대로","자","이","이쪽","이것","이번",
"이렇게말하자면","이런","이러한","이와 같은","요만큼","요만한 것",
"얼마 안 되는 것","이만큼","이 정도의","이렇게 많은 것",
"이와 같다","이때","이렇구나","것과 같이","끼익","삐걱",
"따위","와 같은 사람들","부류의 사람들","왜냐하면","중의하나",
"오직","오로지","에 한하다","하기만 하면","도착하다",
"까지 미치다","도달하다","정도에 이르다","할 지경이다",
"결과에 이르다","관해서는","하고 있다","한 후","혼자",
"자기","자기집","자신","우에 종합한것과같이","총적으로 보면",
"총적으로 말하면","총적으로","대로 하다","으로서","참",
"할 따름이다","쿵","탕탕","쾅쾅","둥둥","봐","봐라",
"아이야","아니","와아","응","아이","참나","년","월","일",
"령","영","이","삼","사","오","육","륙","칠","팔","구",
"이천육","이천칠","이천팔","이천구","하나","둘","셋","넷",
"다섯","여섯","일곱","여덟","아홉",'의','가','이','은',
'들','는','좀','잘','걍','과','도','를','으로','자','에',
'와','한','하다','에서','입니다','있습니다','아니라'
]

In [15]:
from konlpy.tag import Okt
import re

okt = Okt()


preprocessed_token = []
token_sentence = []


for sentence in clean_data:
    sentence = re.sub(r'[^가-힣\s]','',sentence)
    tokens = okt.morphs(sentence,stem=True)
    tokens = [token for token in tokens if token not in ko_stopwords]
    preprocessed_token.append(tokens)

preprocessed_token

[['공인', '회계사', '최종', '합격자', '카이스트', '컴공', '취업', '걱정', '세상'],
 ['카이스트',
  '물리학',
  '컴공',
  '복수',
  '전공',
  '분',
  '때문',
  '취업',
  '쉬다',
  '않다',
  '대학',
  '출신',
  '힘들다',
  '상상',
  '알다'],
 ['다',
  '들다',
  '멀다',
  '이야기',
  '라고',
  '생각',
  '지금',
  '만',
  '보다',
  '재연',
  '대역',
  '배우',
  '아니다',
  '그냥',
  '영상',
  '다',
  '대체',
  '하고',
  '벌써',
  '시작',
  '하고'],
 ['회계사', '대체', '되다', '정도', '면', '이미', '컴퓨터', '앉다', '대부분', '사무직', '전멸'],
 ['앞', '살아가다', '내', '자식', '청년', '미래', '너무', '불투명하다', '안타깝다', '서글프다'],
 ['걸치다', '버스안내양', '합격', '자동', '문', '나오다', '버리다', '꼴'],
 ['숫자', '다루다', '업무', '특히', '가다'],
 ['개발',
  '자다',
  '그냥',
  '기',
  '도합',
  '니',
  '다',
  '제발',
  '기술',
  '공리',
  '행복',
  '증진',
  '방향',
  '발전',
  '되다',
  '기르다',
  '개인',
  '발버둥치다',
  '대비',
  '거나',
  '바꾸다',
  '수',
  '수준',
  '아니다',
  '그야말로',
  '대혁명',
  '불의',
  '발견',
  '전기',
  '발견',
  '거나',
  '느껴지다'],
 ['정말', '어렵다', '시험', '인데', '그걸', '따다', '백수', '라니', '너무', '안타깝다'],
 ['유튜브',
  '회계사',
  '합격',
  '하고',
  '가족',
  '울면',
  '서',
  '전화하다',
  '합격자',
  '상보',
  '니',
  '진짜',
  '허무하다'],
 ['문과',
  '사무직',
  '인데',
  '불과',
  '전',
  '만해',
  '주변',
  '퇴사',
  '하고',
  '코딩',
  '교육',
  '받다',
  '개발자',
  '재',
  '취업',
  '사람',
  '은근',
  '시장',
  '이렇게',
  '와장창',
  '무너지다'],
 ['합격',
  '증',
  '받다',
  '저렇게',
  '비닐',
  '싸다',
  '보관',
  '정도',
  '면',
  '그만큼',
  '진심',
  '이고',
  '그만큼',
  '인생',
  '중요하다',
  '순간',
  '이라고',
  '생각',
  '진짜',
  '타이밍',
  '안좋다',
  '듯',
  '인공',
  '지능',
  '충분하다',
  '다',
  '대신',
  '수',
  '지경',
  '올',
  '걸',
  '누가',
  '알다'],
 ['공인',
  '회계사',
  '합격',
  '갈아',
  '넣다',
  '자격증',
  '땃을텐데',
  '세상',
  '이렇게',
  '변하다',
  '버리다',
  '너무',
  '슬프다'],
 ['대다',
  '다니다',
  '교수',
  '님',
  '왈',
  '컴공',
  '개발자',
  '구인',
  '구직',
  '인문',
  '학과',
  '보다',
  '더',
  '떨어지다',
  '상황',
  '이르다',
  '갑자기',
  '이렇게',
  '세상',
  '변하다',
  '누가',
  '알다'],
 ['회계사', '라고', '오다', '알', '주다', '직업', '군', '이다', '너무', '안타깝다'],
 ['근데',
  '내',
  '가보',
  '엔',
  '지금',
  '스펙',
  '이고',
  '나발',
  '고간',
  '취업',
  '시장',
  '자체',
  '너무',
  '좁다',
  '그냥',
  '취업',
  '힘드다',
  '맞다'],
 ['시대', '예측', '못', '시대', '너무', '빠르다', '아니다'],
 ['이미', '전망', '없다', '직업', '청춘', '바치다', '편견', '버리다', '다양하다', '직업', '도전', '함'],
 ['회사',
  '경리',
  '회계',
  '더존',
  '프로그램',
  '처음',
  '나오다',
  '경리',
  '부',
  '직원',
  '많이',
  '짤렸',
  '지',
  '분개',
  '기장',
  '더존',
  '프로그램',
  '해',
  '버리다',
  '과장',
  '급',
  '신입',
  '사원',
  '다',
  '일이',
  '되다',
  '획기',
  '적',
  '인',
  '사건',
  '이다'],
 ['뭐', '먹고살다', '진짜', '먹고살다', '힘드다'],
 ['본질', '컴퓨터', '앞', '앉다', '다', '대체', '되다', '거', '다'],
 ['제일',
  '먼저',
  '없어지다',
  '무방',
  '하고',
  '대체',
  '되다',
  '바라다',
  '직업',
  '대한민국',
  '판사',
  '들이다'],
 ['상중', '간', '에도', '미나', '광고', '나오다', '시', '대의', '흐름', '이다'],
 ['인터뷰', '찍다', '카메라', '에도', '탑재', '되다', '전문', '카메라맨', '사라지다'],
 ['필요없다', '공부', '너무', '많다', '인원', '뽑다'],
 ['옛날', '은행원', '회계사', '세무사', '변호사', '없어지다', '직업', '이라고', '점점', '희미하다', '정말로'],
 ['회계사', '세무사', '진짜', '이제', '답', '없다'],
 ['세상', '변화', '속도', '너무', '빠르다'],
 ['앞', '으로는', '주니어', '이다', '중간', '급', '사라지다'],
 ['헐다', '심하다', '추적', '분', '나오다', '정도', '니'],
 ['노력', '배신', '대가', '오다'],
 ['검수',
  '고',
  '인물',
  '능력자',
  '빼다',
  '신규',
  '중간',
  '관리자',
  '안',
  '뽑다',
  '미국',
  '피',
  '바람',
  '불다'],
 ['병찬', '이제', '짬', '안전하다', '사다리', '걷어차다', '보다'],
 ['과거', '자의', '의하다', '취업', '유예', '이다', '지금', '타의', '의하다', '취업', '절벽', '죠'],
 ['진짜', '서글프다', '세', '상이', '요', '힘드다', '시험', '인데', '허망', '요'],
 ['차다', '서글프다', '노력'],
 ['회계', '더', '안타깝다', '적용', '더', '간단하다'],
 ['전',
  '쯤',
  '미래',
  '대체',
  '되다',
  '직업',
  '이라는',
  '리스트',
  '보고',
  '친구',
  '랑',
  '이야기',
  '한적',
  '그게',
  '진짜',
  '현실',
  '돼다'],
 ['출장',
  '다니다',
  '서버',
  '구축',
  '하고',
  '부품',
  '고치다',
  '유지',
  '보수',
  '엔지니어',
  '입',
  '풀칠',
  '겁니다'],
 ['세상', '진짜', '빠르다', '변하다'],
 ['재무관리',
  '경영학',
  '경제학',
  '시험',
  '보다',
  '쓸데없이',
  '난이도',
  '높이다',
  '수험생',
  '괴롭히다',
  '시험',
  '시험',
  '임',
  '본질',
  '가치',
  '대비',
  '고',
  '평가',
  '되어다',
  '온',
  '자격증'],
 ['모든',
  '사무',
  '직종',
  '때문',
  '어시',
  '더',
  '빨리',
  '더',
  '깔끔하다',
  '처리',
  '해주다',
  '실무',
  '결',
  '정권',
  '입장',
  '어시',
  '필요',
  '없어지다'],
 ['차다',
  '인생',
  '알',
  '수',
  '없다',
  '게',
  '전',
  '용산',
  '밥',
  '먹다',
  '옆',
  '테이블',
  '삼일',
  '회계사',
  '회식',
  '중',
  '더',
  '라',
  '아모레',
  '사옥',
  '삼일이',
  '아마',
  '나이',
  '대',
  '친구',
  '이야',
  '젊다',
  '입사',
  '지다',
  '안',
  '돼다',
  '거',
  '기다',
  '전',
  '합격',
  '지금',
  '합격',
  '인생',
  '향',
  '방이',
  '이렇게',
  '달라지다',
  '앞',
  '그게',
  '더',
  '심해지다',
  '이고',
  '회식',
  '참석',
  '친구',
  '앞',
  '어떻다',
  '되다',
  '지다',
  '모르다',
  '거지',
  '나다',
  '살아나다',
  '위해',
  '서',
  '정말',
  '고민',
  '많다',
  '분투',
  '중이',
  '다'],
 ['좌우', '국회의원', '대체', '되다'],
 ['아마', '많다', '취준생들', '거', '라고', '봄', '너무', '밝다', '얘기', '더', '슬프다'],
 ['창', '근', '님', '대표', '님', '칭찬', '주', '니까', '허리', '펴다', '모습', '귀엽다'],
 ['협회', '지금', '자격증', '장사', '중'],
 ['원래',
  '대',
  '전',
  '환기',
  '에는',
  '당연하다',
  '발생',
  '일이',
  '잖다',
  '스마트폰',
  '나오니',
  '삐삐',
  '공장',
  '파산하다',
  '나오니',
  '전문직',
  '필요없다',
  '세상',
  '변하다',
  '어쩔',
  '수'],
 ['때문',
  '신입',
  '취업',
  '어렵다',
  '아우성치다',
  '정작',
  '들어오다',
  '없다',
  '못',
  '더',
  '심해지다',
  '요즘',
  '엔',
  '레포트',
  '내다',
  '친구',
  '들어오다',
  '점'],
 ['날', '갈수록', '미치다', '초면', '끝나다', '세상'],
 ['공인',
  '회계사',
  '예전',
  '쯤',
  '학교',
  '교수',
  '님',
  '없어지다',
  '직종',
  '이라',
  '들다',
  '당시',
  '만해',
  '엄청',
  '유망',
  '해보다',
  '게',
  '지금',
  '실화',
  '되다'],
 ['쓸모없다',
  '변호사',
  '다',
  '필요없다',
  '소장',
  '알다',
  '써주다',
  '변호사',
  '소장',
  '대충',
  '쓰다',
  '받다',
  '감'],
 ['회계사',
  '세무사',
  '법무사',
  '이제',
  '끝나다',
  '감',
  '법무사',
  '신고',
  '서식',
  '간',
  '펀하다',
  '보급',
  '되어다',
  '야하다',
  '비싸다',
  '수수료',
  '처리',
  '함'],
 ['우리나라',
  '노동',
  '경',
  '직성',
  '국가',
  '에서는',
  '안',
  '그렇다',
  '고용',
  '해고',
  '힘드다',
  '리스크',
  '크다',
  '사실',
  '외면'],
 ['가장', '비싸다', '일자리', '일수록', '대체', '되다'],
 ['사무직', '웹디자인', '컴퓨터', '직업', '은행원', '다', '없어지다', '직종'],
 ['컴퓨터', '앞', '사람', '다', '위기', '이다'],
 ['아프다', '말다'],
 ['열심히',
  '공부',
  '어렵다',
  '따다',
  '자격증',
  '평생',
  '벌다',
  '먹다',
  '수',
  '잇다',
  '직장',
  '사이',
  '무너지다'],
 ['현실',
  '빨리',
  '수긍',
  '게',
  '생존',
  '유리하다',
  '내',
  '여태',
  '열심히',
  '해오다',
  '현실',
  '인정',
  '해주다',
  '않다',
  '걸',
  '빨리',
  '적응하다',
  '못',
  '죽음',
  '뿐'],
 ['부모', '공부', '만', '아니다', '세상', '멀리', '내다보다', '눈', '키우다', '중요하다'],
 ['회계사', '합격', '정도', '인재', '면', '걸', '해도', '자다', '함', '힘내다'],
 ['변호사', '판사', '가해', '야하다'],
 ['앞', '앉다', '컴퓨터', '두드리다', '직종', '많이', '사라지다', '보다'],
 ['부부',
  '어떻',
  '게',
  '든',
  '살아나다',
  '수',
  '이제',
  '초딩',
  '인',
  '뭘',
  '대비',
  '정말',
  '너무',
  '빠르다',
  '변하다',
  '막막하다',
  '사회',
  '다'],
 ['출산', '장려', '내', '자식', '장래', '암울하다', '대책', '마련', '하고', '장려', '하든'],
 ['회계사', '미지', '정은', '이미', '역사', '길다', '명대', '시대', '에도', '호황', '착시현상', '뿐'],
 ['회계사', '면', '진짜', '어마', '무시', '게', '공부', '분', '일텐데'],
 ['해외', '인턴', '무급', '이나', '되게', '적다', '받다', '고함'],
 ['카이스트',
  '복전',
  '사람',
  '다',
  '떨어지다',
  '취업',
  '캠프',
  '가다',
  '다시',
  '군데',
  '중',
  '군데',
  '스타트업',
  '인데',
  '진짜',
  '빡세'],
 ['전문직', '정도', '니', '일반', '대', '졸자', '어떻다', '얘기', '인지'],
 ['무섭다', '세상', '이야'],
 ['기자', '대체', '하자', '판사', '다', '없애다', '국민', '삶', '소금', '뿌리다'],
 ['진짜', '맨', '나중', '가면', '진짜', '아예', '인간', '채용', '않다'],
 ['개발자',
  '직',
  '군',
  '진짜',
  '타격',
  '입다',
  '년전',
  '코딩',
  '붐',
  '일어서다',
  '단',
  '기',
  '속성',
  '몇개',
  '공부',
  '프로그래머',
  '취업',
  '사람',
  '지금',
  '연차',
  '쌓이다',
  '거기',
  '까지가',
  '마지노선',
  '인거',
  '이후',
  '신입',
  '분들',
  '땜',
  '취업',
  '시장',
  '발도',
  '못',
  '붙이다'],
 ['그니까', '시니어', '끼리', '시', '다르다', '주니어', '아니다', '한테'],
 ['진짜', '심각하다'],
 ['화이트칼라',
  '인하다',
  '대체',
  '걱정',
  '이고',
  '블루',
  '칼라',
  '중국',
  '발',
  '저가',
  '덤핑',
  '공세',
  '때문',
  '문제',
  '고',
  '쉬다',
  '않다',
  '정말'],
 ['회계사',
  '필요',
  '많이',
  '뽑다',
  '회계사',
  '학벌',
  '보다',
  '지',
  '잡',
  '대',
  '회계사',
  '안',
  '뽑다',
  '수요',
  '보다',
  '공급',
  '많다',
  '뭐',
  '뽑다',
  '프로그램',
  '돌리다',
  '현재',
  '근무',
  '직원',
  '좀더',
  '전문',
  '적',
  '맏',
  '기고',
  '좀더',
  '연봉',
  '지급',
  '전문화',
  '되어다',
  '신입',
  '안',
  '뽑다',
  '뽑다',
  '이유',
  '없다',
  '벌률',
  '상담',
  '챗',
  '미나',
  '돌리다',
  '자세하다',
  '알다',
  '소장',
  '적다',
  '줍다',
  '상담',
  '분',
  '유료',
  '만원',
  '내다',
  '사라지다'],
 ['회계사', '걱정', '정도', '면', '업무', '이미', '폭', '망중'],
 ['자르다', '아버지', '연줄', '없다', '수습', '기간', '채용', '해주다', '회사', '없다'],
 ['무섭다'],
 ['회계사', '정말', '대체', '예상', '위', '이다', '역시', '오다', '오다'],
 ['에구', '젊다', '분', '취업', '점점', '더', '어려워지다', '걱정', '이다'],
 ['웹',
  '프로',
  '그렇다',
  '머',
  '전',
  '에도',
  '전',
  '에도',
  '벌다',
  '이제',
  '제일',
  '먼저',
  '나가야',
  '되다',
  '현실'],
 ['회계사', '자격증', '취득', '사람', '카이스트', '컴공', '취업', '걱정'],
 ['솔직하다',
  '지금',
  '경력',
  '회계사',
  '운',
  '이조',
  '시대',
  '자다',
  '타고나다',
  '지금',
  '시대',
  '쓸다',
  '수',
  '회계사',
  '된거',
  '지',
  '지금',
  '시대',
  '취직',
  '똑같이',
  '이력서',
  '백',
  '개다',
  '안되다',
  '임'],
 ['세상', '정말', '빠르다', '변하다', '요즘', '많이', '느끼다', '중'],
 ['세상',
  '만',
  '빨리',
  '변하다',
  '해',
  '요',
  '너무',
  '빨',
  '라서',
  '소름',
  '이다',
  '사람',
  '세상',
  '이상하다',
  '사람',
  '로만',
  '늘다'],
 ['판사',
  '대체',
  '라는',
  '말',
  '판사',
  '사람',
  '이고',
  '분명',
  '정',
  '황상',
  '억울하다',
  '상황',
  '특히',
  '의하다',
  '살생',
  '행위',
  '대해',
  '피해',
  '받다',
  '사람',
  '그로',
  '인하다',
  '남다',
  '가족',
  '앞',
  '살아가다',
  '감',
  '내해',
  '되다',
  '크다',
  '상처',
  '그렇다',
  '사안',
  '피해자',
  '입장',
  '헤아리다',
  '않다',
  '법리',
  '대로',
  '만',
  '판결',
  '정석',
  '대로',
  '가다',
  '뜻임',
  '특히',
  '음주운전',
  '인하다',
  '사망',
  '억울하다',
  '죽음',
  '묻다',
  '폭행',
  '살인',
  '이러하다',
  '사건',
  '심신',
  '미약',
  '초범',
  '형량',
  '감경',
  '없애다',
  '함',
  '사람',
  '생명',
  '뿐',
  '아니다',
  '앞',
  '남다',
  '인생',
  '살아가다',
  '가족',
  '피해자',
  '엮',
  '야하다'],
 ['울',
  '나라',
  '시험',
  '제도',
  '자다',
  '못',
  '되어다',
  '해외',
  '처럼',
  '단계',
  '별',
  '시험',
  '제도로',
  '기회',
  '주다',
  '아니다',
  '울',
  '나라',
  '떨다',
  '트리',
  '려',
  '시험',
  '제도',
  '때문',
  '시험',
  '문항',
  '쓸다',
  '없다',
  '공부량',
  '많다',
  '시대',
  '흐름',
  '따라가다',
  '못',
  '시험',
  '제도',
  '바꾸다'],
 ['정도', '일찍', '태어나다', '껄', '인간', '일자리', '점점', '더', '없어지다', '집값', '미치다'],
 ['판사', '대체', '되어다'],
 ['무섭다', '세상'],
 ['현직',
  '이다',
  '보다',
  '영상',
  '말',
  '단순하다',
  '자동화',
  '인하다',
  '연차',
  '회계사',
  '대한',
  '수',
  '요',
  '감소',
  '미지',
  '정',
  '상태',
  '난',
  '아니다',
  '구조',
  '적',
  '초반',
  '업황',
  '피크',
  '찍다',
  '내리막',
  '예상',
  '되다',
  '관련',
  '당국',
  '업계',
  '수요',
  '무시',
  '하고',
  '선발',
  '인원',
  '더',
  '늘리다',
  '업',
  '황도',
  '안좋다',
  '자동화',
  '인하다',
  '연차',
  '대한',
  '수요',
  '감소',
  '효과',
  '겹',
  '치다',
  '미지',
  '정',
  '상태',
  '발생',
  '이다'],
 ['공무원', '답', '인가', '벌써', '공무원', '몰리', '고'],
 ['지금',
  '년차',
  '회계사',
  '라고',
  '가다',
  '더욱',
  '발전',
  '하고',
  '저렇게',
  '계속',
  '학습',
  '주다',
  '내년',
  '엔',
  '시니어',
  '회계사',
  '업무',
  '맡다'],
 ['개발자',
  '간',
  '내',
  '시작',
  '에는',
  '차',
  '산업혁명',
  '이니',
  '뭐',
  '니',
  '진짜',
  '개발자',
  '많이',
  '뽑다',
  '진짜',
  '개',
  '븅신',
  '처럼',
  '해도',
  '회사',
  '신입',
  '키우다',
  '써다',
  '한다는',
  '생각',
  '직원',
  '채용',
  '코로나',
  '터지다',
  '시점',
  '이후',
  '가다',
  '발전',
  '프로젝트',
  '급',
  '줄어들다',
  '한순간',
  '신입',
  '취업',
  '힘드다',
  '환경',
  '되어다',
  '이일',
  '해먹',
  '수',
  '아니다',
  '점점',
  '줄어들다',
  '느낌',
  '이다',
  '미래',
  '불투명하다',
  '일이',
  '개발',
  '밖에',
  '없다',
  '뭐',
  '먹다',
  '살다',
  '고민',
  '크다'],
 ['시작', '저년', '차', '신입', '대상', '더', '발전', '중간', '급', '실무', '다', '박살', '나다'],
 ['앞',
  '시대',
  '더',
  '힘들다',
  '끼',
  '다',
  '이건',
  '대',
  '세기',
  '때매',
  '절대',
  '피해',
  '갈수',
  '없다'],
 ['전문성', '상관없다', '노동', '집약', '적', '인', '업무', '가다', '대체', '다', '고', '보다', '이제'],
 ['어쩌면', '저출산', '문제', '멀다', '미래', '보다', '축복', '일지', '모르다'],
 ['불과',
  '전만',
  '저출산',
  '비교',
  '문화',
  '폐해',
  '라고',
  '생각',
  '젠',
  '정말',
  '생존',
  '문제',
  '디폴트',
  '되어다'],
 ['재무',
  '직',
  '신입',
  '취업',
  '너무',
  '안되다',
  '년제',
  '고',
  '학과',
  '세무',
  '학과',
  '고',
  '자격증',
  '안',
  '돼다',
  '정말'],
 ['전문직', '자격증', '안심', '못', '시', '기구'],
 ['지금',
  '년차',
  '회계사',
  '내년',
  '년차',
  '정속',
  '아니다',
  '무섭다',
  '가속',
  '중',
  '이다',
  '물리',
  '보급',
  '화',
  '되다',
  '순간'],
 ['때문',
  '타',
  '업종',
  '불경기',
  '심각하다',
  '애초',
  '채용',
  '자체',
  '안함',
  '주변',
  '공장',
  '식품',
  '조',
  '건설',
  '유통업',
  '대표',
  '직원',
  '만나다',
  '얘기',
  '해보다',
  '최대',
  '매출',
  '빠지다',
  '곳도',
  '들다',
  '봄',
  '작년',
  '까지는',
  '돼다',
  '소식',
  '지금',
  '진짜',
  '좋다',
  '소식',
  '자체',
  '아예',
  '안',
  '들리다',
  '경기',
  '침체',
  '앞',
  '년내',
  '정말',
  '많이',
  '변하다'],
 ['세',
  '일인',
  '자영',
  '업자',
  '이다',
  '무우',
  '배추',
  '양배추',
  '대파',
  '오이',
  '차',
  '싣다',
  '다니다',
  '새벽',
  '식당',
  '납품',
  '크다',
  '돈',
  '안되다',
  '집',
  '살',
  '능력',
  '안되다',
  '보다',
  '똑똑하다',
  '젊은이',
  '힘',
  '내다',
  '꺽',
  '이지',
  '않다',
  '마음',
  '가지',
  '고',
  '취업',
  '성',
  '겅',
  '바라다',
  '화이팅'],
 ['인구', '수', '줄어들다', '맞다', '상황', '출산율', '높다', '경쟁', '불', '지옥', '대한민국', '되다'],
 ['공감', '작년', '조짐', '이상하다', '업계', '모르다', '사람', '없다'],
 ['미국',
  '살다',
  '미국',
  '때문',
  '졸업생',
  '정말',
  '힘들다',
  '많다',
  '한인',
  '자녀',
  '컴공',
  '이나',
  '수학',
  '사용',
  '직업',
  '많이',
  '빠지다',
  '정말',
  '취업',
  '힘들다'],
 ['어떻다', '이렇다', '일이'],
 ['세상', '휘', '둘리', '면', '이도', '못', '그냥', '본인', '집중', '하고', '본인', '싶다', '살다'],
 ['뉴스', '안', '보고', '지내다', '씁쓸하다', '결말', '이네', '요'],
 ['맞다', '얘기', '기다', '본인', '밥그릇', '생각', '사다리', '차다', '느낌', '멘트'],
 ['출생', '그냥', '자연스럽다', '자연', '선택', '이네'],
 ['자격증', '결정', '되다', '직업', '안', '맞다', '미래', '없다'],
 ['지나다', '사무직', '다', '집', '가야', '되다', '듯'],
 ['걸', '보다', '열심히', '공부', '하고', '노력', '해봤다', '아무', '소용없다', '생각', '이듬'],
 ['라는', '거대하다', '흐름', '앞', '자격증', '소용', '시대', '읽다', '능력', '거늘'],
 ['의사',
  '수술',
  '빼다',
  '많이',
  '비슷',
  '혈액',
  '검사',
  '결과',
  '지',
  '보여주다',
  '너무',
  '자다',
  '설명',
  '줌',
  '처방약',
  '알다',
  '설명',
  '많다',
  '이해도',
  '쉬움',
  '병원',
  '가다',
  '의사',
  '랑',
  '대화',
  '해보다',
  '문장',
  '끝임',
  '의사',
  '바쁘다',
  '보',
  '여서',
  '질문',
  '많이',
  '못'],
 ['병찬', '씨', '붙다', '니까', '밥그릇', '지키다', '이제', '덜', '뽑다', '맞다'],
 ['택배', '기사', '하자', '몸', '써다', '되다', '젠'],
 ['저렇게', '열심히', '공부', '남일', '않다', '마음', '아프다'],
 ['담달', '리니지', '클래식', '회계사', '변호사', '세무사', '분들', '오픈', '런'],
 ['판사', '가다', '이유'],
 ['에이', '사용', '오류', '진짜', '많이', '나오다', '다시', '확인'],
 ['뒤', '자기계발', '용', '회계사', '자격증', '따다', '두다'],
 ['본인', '많이', '뽑다', '합격', '이제', '더', '뽑다'],
 ['자급자족', '농사', '답', '이다'],
 ['회계사', '도장', '받다', '야하다', '일도', '없애다', '되다'],
 ['큰일', '이네', '요'],
 ['근데',
  '회계사',
  '연도',
  '바이',
  '연도',
  '원래',
  '심하다',
  '어떻다',
  '땐',
  '대다',
  '법인',
  '전체',
  '티',
  '오가다',
  '회계사',
  '시험',
  '합격자',
  '총',
  '합',
  '보다',
  '많다',
  '그냥',
  '대다',
  '원서',
  '넣다',
  '무조건',
  '대다',
  '회계법인',
  '합격',
  '인',
  '연도',
  '어떻다',
  '스카이',
  '상경',
  '계',
  '회계사',
  '시험',
  '합격',
  '이라는',
  '초',
  '엘리트',
  '코스',
  '밟다',
  '않다',
  '이름',
  '들다',
  '보다',
  '회계법인',
  '에는',
  '못',
  '들어가다',
  '그렇다',
  '해도',
  '그렇다',
  '뭐',
  '엔',
  '심각하다',
  '함'],
 ['론', '미래', '인간', '의사', '보다', '로봇', '의사', '더', '치료', '요'],
 ['모든',
  '산업',
  '똑같다',
  '미국',
  '금융',
  '권',
  '금융',
  '컨설팅',
  '테크',
  '채용',
  '박살',
  '나다',
  '그나마',
  '포지션',
  '열리다',
  '의료',
  '정도',
  '저만',
  '해도',
  '전',
  '명',
  '팀',
  '달',
  '지금',
  '주',
  '만에',
  '그나마',
  '년대',
  '생',
  '까지는',
  '어떻',
  '게',
  '든',
  '밥',
  '벌이',
  '경력',
  '이라도',
  '쌓이다',
  '년대',
  '생',
  '신입',
  '자리',
  '아예',
  '없다'],
 ['문', '제일', '뿐', '안전하다', '직업', '없다'],
 ['앞', '으로는', '없어지다', '직업', '미리', '알아보다', '공부', '고', '자격증', '따다', '되다'],
 ['책상',
  '머리',
  '앉다',
  '컴퓨터',
  '끄적',
  '대다',
  '다',
  '없어지다',
  '임',
  '몸',
  '만',
  '인간',
  '남다',
  '임'],
 ['카이스트', '복수', '전공자', '스타트업', '취직', '햇', '다', '고'],
 ['앞', '으로는', '미래', '지향', '적', '공부', '방향', '전환'],
 ['가장', '먼저', '세무사', '회계사', '없어지다'],
 ['합격자', '면', '서', '댓', '걱정', '분', '보다', '나은', '인생', '이니', '걱정', '안', '되다'],
 ['회계사', '수', '줄이다', '아니다', '수임료', '낮추다'],
 ['컴공', '나오다', '답', '없다', '공기업', '자리', '선점', '오다', '당분간', '먹고살다', '수'],
 ['초딩',
  '대졸',
  '투자',
  '돈',
  '대비',
  '얻다',
  '결과물',
  '이르다',
  '공부',
  '의미',
  '시대',
  '정말',
  '힘드다',
  '세상',
  '이네'],
 ['진짜',
  '충격',
  '적',
  '인게',
  '미나',
  '실습',
  '면접',
  '보다',
  '카이스트',
  '출신',
  '이라도',
  '생',
  '성형',
  '활',
  '용도',
  '낮다',
  '지원',
  '보다',
  '일반',
  '고등학교',
  '졸업',
  '하고',
  '생',
  '성형',
  '이용',
  '극대',
  '화하다',
  '결과물',
  '제출',
  '사람',
  '중',
  '후자',
  '뽑히다',
  '더',
  '충격',
  '적',
  '이다',
  '스타트업',
  '실제',
  '이다'],
 ['지금', '공대', '컴공', '전공자', '작살', '중'],
 ['이렇다',
  '보다',
  '확실하다',
  '기업',
  '이나',
  '주가',
  '거품',
  '끼다',
  '모르다',
  '가다',
  '생산',
  '성',
  '향상',
  '도움',
  '두다',
  '자체',
  '진실',
  '이라',
  '는걸',
  '알',
  '수'],
 ['년대', '년대', '생', '최고', '운', '좋다'],
 ['가다', '못', '손', '기술', '배관', '공', '타', '공', '대세', '되다'],
 ['오다',
  '황병찬',
  '님',
  '본인',
  '회계사',
  '하고',
  '잘리다',
  '없다',
  '신입',
  '많이',
  '안',
  '뽑다',
  '되다',
  '말'],
 ['앞', '회계사', '공인', '중개사', '랑', '똑같다', '취급', '되다'],
 ['지금', '회계사', '걱정', '아니다', '다다', '젓', '돼다'],
 ['회사',
  '지금',
  '되다',
  '디자이너',
  '명',
  '뽑다',
  '아이티',
  '망하다',
  '오래',
  '임',
  '필요없다',
  '가다',
  '다해',
  '서',
  '정치',
  '윗사람',
  '한테',
  '보이다',
  '나오다',
  '셈'],
 ['신입', '변호사', '회계사', '날', '자료', '모으다', '정리', '초면', '끝내', '버리다'],
 ['회계사',
  '세무사',
  '숫자',
  '관련',
  '쪽',
  '대체',
  '쉬다',
  '명',
  '걸',
  '수',
  '되다',
  '나중',
  '에는',
  '일반인',
  '오다',
  '상담',
  '회계사',
  '세무사',
  '의존',
  '낮다',
  '지다',
  '모든',
  '분야',
  '이라도',
  '영향',
  '받다'],
 ['현직',
  '회계',
  '사다',
  '늘다',
  '핑계',
  '뿐',
  '수요',
  '예측',
  '안',
  '하고',
  '회계사',
  '합격',
  '자수',
  '미치다',
  '높이다',
  '업계',
  '자체',
  '덤핑',
  '곪아가',
  '고',
  '욕심',
  '많다',
  '윗',
  '대가리',
  '새끼',
  '스탭들',
  '싸다',
  '부리고',
  '갈아',
  '치우다',
  '많이',
  '뽑다',
  '사단',
  '나다',
  '임',
  '아직',
  '까지는',
  '늘다',
  '거들다',
  '앞',
  '으로는',
  '때문',
  '진짜',
  '업계',
  '힘들다',
  '날',
  '오다'],
 ['화장품',
  '사업',
  '직원',
  '명',
  '필요하다',
  '만원',
  '가다',
  '해주다',
  '느끼다',
  '브랜드',
  '만들다',
  '활용',
  '키우다',
  '답',
  '유통',
  '광고',
  '회계',
  '번역',
  '통역',
  '컨텐츠',
  '점점',
  '직원',
  '필요',
  '없어지다'],
 ['힘들다',
  '공부',
  '취업',
  '않다',
  '되다',
  '젊은이',
  '희망이',
  '없다',
  '싸움질',
  '국회의원',
  '숫자',
  '줄',
  '이지'],
 ['가계부',
  '앱',
  '받다',
  '쓰다',
  '졷같',
  '광고',
  '계속',
  '뜨다',
  '내',
  '앱',
  '만',
  '들어서다',
  '쓰다',
  '쓰다',
  '이렇다',
  '시대',
  '임',
  '하다못해',
  '안',
  '그냥',
  '밑바닥',
  '되다',
  '임'],
 ['작년', '컴공', '졸업생', '진심', '개', '빡치다'],
 ['진짜', '전공', '뭐', '아예', '젠', '대학', '의미', '없다', '취업', '어케하', '라고'],
 ['황당하다'],
 ['이래서',
  '요즘',
  '유튜브',
  '세무사',
  '자극',
  '적',
  '세무조사',
  '세금',
  '폭탄',
  '어쩌',
  '고',
  '영상',
  '많아지다'],
 ['사람', '필요없다', '임', '근대', '자꾸', '애', '낳다', '몰다'],
 ['생각', '속도', '인간', '따라가다', '못', '더', '빨리', '변하다', '느끼다', '기도', '전'],
 ['정말', '우려', '되다', '현실', '이다'],
 ['예상',
  '요즘',
  '기술',
  '발달',
  '보다',
  '진짜',
  '무섭다',
  '정도',
  '앞',
  '직업',
  '생태계',
  '완전하다',
  '바뀌다',
  '예상',
  '하고',
  '젠',
  '사람',
  '감',
  '만족',
  '체험',
  '형',
  '아이템',
  '이나',
  '아이디어',
  '필요하다',
  '분야',
  '커지다',
  '예상',
  '숙련',
  '기술',
  '경계',
  '자체',
  '없어지다'],
 ['꼭', '코앞', '떨어지다', '이르다', '들다', '미리', '미리', '들다', '생각', '못'],
 ['지다', '땃으', '니까', '줄이다', '된댘'],
 ['젠', '스스로', '다', '필요없다', '인간', '되어다', '듯'],
 ['업계',
  '진짜',
  '진작',
  '다',
  '먹히다',
  '소프트웨어',
  '쪽',
  '특히',
  '심다',
  '제일',
  '심하다',
  '게임',
  '업계',
  '임',
  '진짜',
  '끝나다',
  '신입',
  '연차',
  '뿐',
  '만이',
  '문제',
  '아니다',
  '경력',
  '직',
  '회사',
  '망하다',
  '순간',
  '구직',
  '난',
  '임',
  '고',
  '연차',
  '능력',
  '좋다',
  '사람',
  '안',
  '뽑다',
  '시대',
  '임'],
 ['부모',
  '정신차리다',
  '되다',
  '애',
  '대학',
  '보내다',
  '생각',
  '돈',
  '아끼다',
  '빨리',
  '만의',
  '기술',
  '배우다',
  '되다'],
 ['회계사', '랑', '세무사', '완전', '존망', '중', '공부', '분', '시작', '말다', '인생', '좇', '되다'],
 ['아주', '재밌다', '장난', '넘다', '공부', '대체'],
 ['시대',
  '질문',
  '무기',
  '다',
  '두리',
  '뭉',
  '실하다',
  '질문',
  '엔',
  '평범하다',
  '페라리',
  '타고',
  '출퇴근',
  '만',
  '건가',
  '제대로',
  '질문',
  '자만',
  '진짜',
  '달리다',
  '수'],
 ['변호사', '세무사', '회계사', '망하다', '뭐'],
 ['사람', '명', '가치', '한장', '에도', '미치다', '못', '시대'],
 ['회계사', '합격', '정도', '면', '시험', '충분하다', '합격', '다시', '시작', '수'],
 ['자리', '차지', '하고', '고해', '서', '후배', '자리', '없애다', '표독', '사람'],
 ['미국',
  '일반',
  '회계사',
  '계약',
  '직',
  '생활',
  '이고',
  '세무사',
  '동네',
  '마트',
  '책상',
  '놓다',
  '영업',
  '상담',
  '함'],
 ['개인',
  '단체',
  '나라',
  '발버둥치다',
  '막다',
  '보다',
  '해도',
  '이건',
  '어쩔',
  '수',
  '없다',
  '현상',
  '이다',
  '이제',
  '어떻다',
  '살',
  '지'],
 ['젊다', '은애', '살수', '없다', '구조', '돼다', '노가다', '농업', '만'],
 ['전문직', '고시생', '없다', '살리다'],
 ['붙다', '사람', '얘기', '면', '안', '붙다', '사람', '섭섭하다'],
 ['퇴사', '진짜', '미치다', '행동', '이다', '나가다', '들어가다', '곳', '없다'],
 ['병찬', '씨', '자리', '두', '안남다'],
 ['고객',
  '회계',
  '자료',
  '넣다',
  '버리다',
  '유출',
  '되다',
  '예상',
  '안',
  '난',
  '합격',
  '가다',
  '발달',
  '돼다',
  '합격자',
  '줄',
  '이라는',
  '건',
  '뭔',
  '심보'],

In [35]:
preprocessed_sentences = [' '.join(token) for token in preprocessed_token]
preprocessed_sentences

import pandas as pd
pd.Series(preprocessed_sentences).to_csv('실습_전처리.csv', index=False, encoding='utf-8-sig')

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer(
    ngram_range=(1,2),
    max_df=1.0,
    min_df=2
)

comment_vecs = tfidf_vectorizer.fit_transform(preprocessed_sentences)

In [20]:
comment_vecs

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 14517 stored elements and shape (1146, 2431)>

In [21]:
tfidf_vectorizer.vocabulary_

{'공인': 192,
 '회계사': 2369,
 '최종': 2093,
 '합격자': 2294,
 '카이스트': 2129,
 '컴공': 2138,
 '취업': 2107,
 '걱정': 97,
 '세상': 1160,
 '공인 회계사': 195,
 '카이스트 컴공': 2133,
 '컴공 취업': 2141,
 '취업 걱정': 2108,
 '물리학': 810,
 '복수': 960,
 '전공': 1830,
 '때문': 649,
 '쉬다': 1217,
 '않다': 1370,
 '대학': 537,
 '출신': 2102,
 '힘들다': 2429,
 '상상': 1104,
 '알다': 1377,
 '카이스트 물리학': 2130,
 '쉬다 않다': 1218,
 '들다': 628,
 '멀다': 765,
 '이야기': 1646,
 '라고': 671,
 '생각': 1113,
 '지금': 1955,
 '보다': 927,
 '배우': 879,
 '아니다': 1322,
 '그냥': 254,
 '영상': 1488,
 '대체': 521,
 '하고': 2246,
 '벌써': 890,
 '시작': 1256,
 '라고 생각': 672,
 '아니다 그냥': 1324,
 '대체 하고': 533,
 '시작 하고': 1258,
 '되다': 584,
 '정도': 1870,
 '이미': 1640,
 '컴퓨터': 2142,
 '앉다': 1367,
 '대부분': 506,
 '사무직': 1070,
 '전멸': 1839,
 '회계사 대체': 2376,
 '대체 되다': 525,
 '컴퓨터 앉다': 2143,
 '살아가다': 1096,
 '자식': 1776,
 '청년': 2079,
 '미래': 820,
 '너무': 385,
 '불투명하다': 991,
 '안타깝다': 1364,
 '서글프다': 1131,
 '걸치다': 114,
 '합격': 2287,
 '자동': 1759,
 '나오다': 353,
 '버리다': 883,
 '숫자': 1213,
 '다루다': 467,
 '업무': 1424,
 '특히': 2189,
 '가다': 10,
 '숫자 다루다': 1216,
 '특히 가다': 2190,
 '개발': 74,
 '자다': 1752,
 '도합': 570,
 '제발': 1894,
 '기술': 304,
 '행복': 2314,
 '방향': 876,
 '발전': 867,
 '개인': 83,
 '발버둥치다': 865,
 '대비': 507,
 '거나': 86,
 '바꾸다': 835,
 '수준': 1205,
 '전기': 1832,
 '수준 아니다': 1206,
 '정말': 1874,
 '어렵다': 1402,
 '시험': 1263,
 '인데': 1689,
 '그걸': 248,
 '따다': 641,
 '백수': 881,
 '시험 인데': 1266,
 '인데 그걸': 1690,
 '너무 안타깝다': 389,
 '유튜브': 1559,
 '가족': 40,
 '상보': 1103,
 '진짜': 2028,
 '허무하다': 2324,
 '회계사 합격': 2405,
 '합격 하고': 2293,
 '문과': 797,
 '불과': 987,
 '만해': 728,
 '주변': 1923,
 '퇴사': 2180,
 '코딩': 2146,
 '교육': 220,
 '받다': 858,
 '개발자': 76,
 '사람': 1044,
 '시장': 1259,
 '이렇게': 1627,
 '무너지다': 790,
 '사무직 인데': 1073,
 '코딩 교육': 2148,
 '교육 받다': 221,
 '개발자 취업': 79,
 '취업 사람': 2110,
 '저렇게': 1819,
 '싸다': 1301,
 '그만큼': 275,
 '진심': 2026,
 '이고': 1591,
 '인생': 1703,
 '중요하다': 1949,
 '순간': 1210,
 '이라고': 1617,
 '타이밍': 2165,
 '안좋다': 1363,
 '인공': 1684,
 '지능': 1970,
 '충분하다': 2103,
 '대신': 511,
 '지경': 1954,
 '누가': 439,
 '이라고 생각': 1619,
 '인공 지능': 1685,
 '누가 알다': 440,
 '갈아': 51,
 '넣다': 398,
 '자격증': 1742,
 '변하다': 904,
 '슬프다': 1231,
 '대다': 502,
 '다니다': 466,
 '교수': 219,
 '구인': 225,
 '구직': 228,
 '인문': 1701,
 '학과': 2265,
 '떨어지다': 660,
 '상황': 1109,
 '이르다': 1636,
 '갑자기': 60,
 '세상 변하다': 1162,
 '오다': 1502,
 '주다': 1921,
 '직업': 1993,
 '이다': 1602,
 '회계사 라고': 2380,
 '직업 이다': 2009,
 '근데': 277,
 '스펙': 1230,
 '나발': 349,
 '자체': 1787,
 '좁다': 1911,
 '힘드다': 2426,
 '맞다': 745,
 '취업 시장': 2111,
 '너무 좁다': 391,
 '취업 힘드다': 2116,
 '힘드다 맞다': 2427,
 '시대': 1238,
 '예측': 1499,
 '빠르다': 1009,
 '시대 너무': 1240,
 '너무 빠르다': 388,
 '전망': 1838,
 '없다': 1430,
 '바치다': 843,
 '편견': 2209,
 '다양하다': 474,
 '도전': 567,
 '없다 직업': 1445,
 '편견 버리다': 2210,
 '회사': 2407,
 '경리': 143,
 '회계': 2363,
 '더존': 548,
 '프로그램': 2227,
 '처음': 2074,
 '직원': 2015,
 '많이': 733,
 '기장': 315,
 '신입': 1276,
 '사원': 1079,
 '일이': 1724,
 '획기': 2411,
 '사건': 1034,
 '회사 경리': 2408,
 '처음 나오다': 2075,
 '먹고살다': 756,
 '본질': 966,
 '제일': 1896,
 '먼저': 761,
 '없어지다': 1449,
 '바라다': 838,
 '대한민국': 541,
 '판사': 2200,
 '들이다': 636,
 '제일 먼저': 1897,
 '먼저 없어지다': 764,
 '에도': 1460,
 '미나': 818,
 '광고': 214,
 '대의': 515,
 '흐름': 2417,
 '대의 흐름': 516,
 '흐름 이다': 2419,
 '인터뷰': 1712,
 '찍다': 2043,
 '카메라': 2128,
 '전문': 1841,
 '사라지다': 1039,
 '필요없다': 2240,
 '공부': 183,
 '많다': 730,
 '인원': 1705,
 '뽑다': 1022,
 '너무 많다': 386,
 '옛날': 1501,
 '은행원': 1569,
 '세무사': 1153,
 '변호사': 908,
 '점점': 1863,
 '정말로': 1875,
 '회계사 세무사': 2387,
 '세무사 변호사': 1155,
 '변호사 없어지다': 913,
 '없어지다 직업': 1453,
 '직업 이라고': 2010,
 '이제': 1656,
 '변화': 916,
 '속도': 1177,
 '세상 변화': 1163,
 '으로는': 1563,
 '주니어': 1919,
 '중간': 1941,
 '헐다': 2325,
 '심하다': 1295,
 '노력': 422,
 '대가': 497,
 '검수': 117,
 '인물': 1702,
 '능력자': 459,
 '빼다': 1019,
 '신규': 1271,
 '관리자': 211,
 '미국': 817,
 '바람': 840,
 '불다': 988,
 '병찬': 921,
 '안전하다': 1361,
 '사다리': 1038,
 '과거': 199,
 '자의': 1786,
 '의하다': 1589,
 '유예': 1556,
 '타의': 2164,
 '이다 지금': 1609,
 '상이': 1107,
 '허망': 2323,
 '차다': 2046,
 '적용': 1826,
 '간단하다': 45,
 '이라는': 1620,
 '보고': 922,
 '친구': 2124,
 '그게': 251,
 '현실': 2329,
 '돼다': 581,
 '되다 직업': 614,
 '직업 이라는': 2011,
 '현실 돼다': 2330,
 '구축': 229,
 '고치다': 170,
 '유지': 1558,
 '보수': 944,
 '엔지니어': 1470,
 '풀칠': 2224,
 '겁니다': 121,
 '진짜 빠르다': 2030,
 '빠르다 변하다': 1011,
 '난이도': 362,
 '높이다': 437,
 '수험생': 1208,
 '가치': 43,
 '평가': 2213,
 '되어다': 621,
 '시험 보다': 1265,
 '모든': 772,
 '사무': 1068,
 '직종': 2019,
 '빨리': 1014,
 '깔끔하다': 329,
 '처리': 2069,
 '해주다': 2310,
 '실무': 1284,
 '정권': 1868,
 '입장': 1738,
 '필요': 2236,
 '사무 직종': 1069,
 '필요 없어지다': 2239,
 '먹다': 757,
 '회식': 2410,
 '아마': 1335,
 '나이': 357,
 '이야': 1645,
 '젊다': 1857,
 '입사': 1737,
 '지다': 1972,
 '기다': 295,
 '방이': 875,
 '달라지다': 491,
 '심해지다': 1297,
 '어떻다': 1397,
 '모르다': 780,
 '거지': 94,
 '나다': 342,
 '살아나다': 1097,
 '위해': 1548,
 '고민': 166,
 '중이': 1950,
 '어떻다 되다': 1398,
 '좌우': 1917,
 '국회의원': 236,
 '밝다': 868,
 '얘기': 1394,
 '대표': 536,
 '니까': 462,
 '협회': 2342,
 '장사': 1809,
 '원래': 1540,
 '환기': 2358,
 '에는': 1458,
 '당연하다': 495,
 '발생': 866,
 '잖다': 1797,
 '스마트폰': 1223,
 '나오니': 352,
 '공장': 196,
 '파산하다': 2192,
 '전문직': 1844,
 '어쩔': 1411,
 '에는 당연하다': 1459,
 '정작': 1883,
 '들어오다': 635,
 '요즘': 1532,
 '내다': 379,
 '신입 취업': 1280,
 '갈수록': 50,
 '미치다': 829,
 '초면': 2085,
 '끝나다': 334,
 '예전': 1498,
 '학교': 2266,
 '이라': 1615,
 '엄청': 1421,
 '유망': 1554,
 '해보다': 2305,
 '실화': 1291,
 '없어지다 직종': 1454,
 '직종 이라': 2022,
 '쓸모없다': 1319,
 '소장': 1175,
 '써주다': 1308,
 '대충': 534,
 '쓰다': 1310,
 '법무사': 897,
 '신고': 1270,
 '보급': 924,
 '야하다': 1389,
 '비싸다': 1003,
 '세무사 법무사': 1154,
 '우리나라': 1537,
 '노동': 416,
 '국가': 230,
 '에서는': 1463,
 '그렇다': 264,
 '고용': 168,
 '해고': 2300,
 '리스크': 702,
 '크다': 2154,
 '사실': 1074,
 '외면': 1525,
 '고용 해고': 169,
 '리스크 크다': 703,
 '가장': 34,
 '일자리': 1728,
 '컴퓨터 직업': 2144,
 '위기': 1546,
 '사람 위기': 1055,
 '아프다': 1352,
 '말다': 741,
 '열심히': 1486,
 '평생': 2214,
 '벌다': 889,
 '잇다': 1740,
 '직장': 2016,
 '사이': 1080,
 '열심히 공부': 1487,
 '따다 자격증': 643,
 '생존': 1127,
 '유리하다': 1553,
 '해오다': 2308,
 '인정': 1708,
 '적응하다': 1829,
 '죽음': 1930,
 '빨리 적응하다': 1017,
 '부모': 971,
 '키우다': 2159,
 '아니다 세상': 1328,
 '인재': 1707,
 '해도': 2302,
 '힘내다': 2425,
 '합격 정도': 2292,
 '변호사 판사': 914,
 '앉다 컴퓨터': 1368,
 '사라지다 보다': 1041,
 '어떻': 1396,
 '초딩': 2084,
 '막막하다': 714,
 '사회': 1083,
 '출산': 2099,
 '장래': 1807,
 '암울하다': 1383,
 '대책': 517,
 '마련': 705,
 '대책 마련': 518,
 '미지': 827,
 '정은': 1882,
 '역사': 1476,
 '길다': 324,
 '호황': 2346,
 '회계사 미지': 2382,
 '미지 정은': 828,
 '시대 에도': 1248,
 '어마': 1404,
 '무시': 793,
 '회계사 진짜': 2399,
 '해외': 2309,
 '인턴': 1713,
 '이나': 1596,
 '되게': 583,
 '적다': 1821,
 '고함': 171,
 '적다 받다': 1822,
 '복전': 962,
 '캠프': 2135,
 '다시': 470,
 '군데': 237,
 '스타트업': 1229,
 '취업 캠프': 2115,
 '일반': 1717,
 '인지': 1710,
 '전문직 정도': 1847,
 '무섭다': 791,
 '무섭다 세상': 792,
 '하자': 2264,
 '없애다': 1448,
 '국민': 233,
 '뿌리다': 1033,
 '나중': 359,
 '가면': 30,
 '아예': 1343,
 '인간': 1675,
 '채용': 2057,
 '타격': 2161,
 '입다': 1736,
 '년전': 408,
 '몇개': 770,
 '프로그래머': 2226,
 '연차': 1483,
 '쌓이다': 1304,
 '거기': 85,
 '인거': 1680,
 '이후': 1671,
 '분들': 979,
 '붙이다': 995,
 '년전 코딩': 409,
 '연차 쌓이다': 1484,
 '그니까': 257,
 '시니어': 1234,
 '끼리': 337,
 '다르다': 468,
 '한테': 2282,
 '심각하다': 1293,
 '진짜 심각하다': 2031,
 '화이트칼라': 2350,
 '인하다': 1715,
 '블루': 996,
 '칼라': 2134,
 '중국': 1945,
 '저가': 1815,
 '덤핑': 551,
 '문제': 801,
 '대체 걱정': 524,
 '블루 칼라': 997,
 '학벌': 2269,
 '수요': 1199,
 '공급': 176,
 '돌리다': 572,
 '현재': 2336,
 '근무': 281,
 '기고': 291,
 '연봉': 1480,
 '지급': 1965,
 '이유': 1649,
 '상담': 1100,
 '줍다': 1940,
 '유료': 1552,
 '만원': 722,
 '회계사 필요': 2401,
 '많이 뽑다': 737,
 '뽑다 회계사': 1031,
 '회계사 학벌': 2404,
 '보다 회계사': 941,
 '회계사 뽑다': 2386,
 '수요 보다': 1200,
 '보다 공급': 929,
 '공급 많다': 177,
 '신입 뽑다': 1278,
 '뽑다 뽑다': 1027,
 '뽑다 이유': 1029,
 '이유 없다': 1650,
 '망중': 743,
 '회계사 걱정': 2372,
 '자르다': 1766,
 '아버지': 1341,
 '수습': 1195,
 '기간': 286,
 '수습 기간': 1196,
 '예상': 1497,
 '역시': 1477,
 '어려워지다': 1401,
 '걱정 이다': 103,
 '프로': 2225,
 '되다 현실': 617,
 '취득': 2106,
 '회계사 자격증': 2396,
 '자격증 취득': 1747,
 '솔직하다': 1179,
 '경력': 138,
 '쓸다': 1314,
 '된거': 623,
 '취직': 2118,
 '똑같이': 665,
 '이력서': 1633,
 '개다': 71,
 '안되다': 1356,
 '지금 경력': 1956,
 '경력 회계사': 142,
 '지금 시대': 1961,
 '이력서 개다': 1634,
 '느끼다': 448,
 '라서': 677,
 '이상하다': 1642,
 '로만': 684,
 '늘다': 451,
 '빨리 변하다': 1016,
 '이다 사람': 1605,
 '라는': 673,
 '분명': 980,
 '억울하다': 1415,
 '행위': 2316,
 '대해': 542,
 '피해': 2234,
 '그로': 270,
 '남다': 363,
 '피해자': 2235,
 '대로': 505,
 '판결': 2196,
 '사망': 1067,
 '이러하다': 1626,
 '형량': 2343,
 '생명': 1124,
 '판사 대체': 2202,
 '판사 사람': 2205,
 '그로 인하다': 271,
 '사람 생명': 1052,
 '나라': 343,
 '제도': 1892,
 '처럼': 2067,
 '단계': 482,
 '기회': 321,
 '떨다': 659,
 '트리': 2186,
 '따라가다': 645,
 '시험 제도': 1267,
 '쓸다 없다': 1316,
 '시대 흐름': 1252,
 '흐름 따라가다': 2418,
 '일찍': 1732,
 '태어나다': 2168,
 '일찍 태어나다': 1733,
 '점점 없어지다': 1864,
 '대체 되어다': 526,
 '현직': 2338,
 '단순하다': 485,
 '자동화': 1761,
 '대한': 540,
 '감소': 56,
 '상태': 1108,
 '구조': 226,
 '초반': 2086,
 '내리막': 381,
 '관련': 207,
 '업계': 1423,
 '선발': 1135,
 '늘리다': 453,
 '효과': 2412,
 '치다': 2119,
 '현직 이다': 2339,
 '보다 영상': 934,
 '무시 하고': 794,
 '선발 인원': 1136,
 '공무원': 181,
 '인가': 1673,
 '몰리': 789,
 '년차': 410,
 '더욱': 547,
 '계속': 158,
 '학습': 2271,
 '내년': 377,
 '지금 년차': 1958,
 '년차 회계사': 412,
 '시니어 회계사': 1237,
 '회계사 업무': 2391,
 '산업혁명': 1087,
 '이니': 1600,
 '써다': 1305,
 '한다는': 2276,
 '코로나': 2149,
 '터지다': 2172,
 '시점': 1261,
 '프로젝트': 2228,
 '줄어들다': 1934,
 '한순간': 2278,
 '환경': 2357,
 '해먹': 2304,
 '느낌': 449,
 '밖에': 849,
 '살다': 1092,
 '산업혁명 이니': 1088,
 '신입 키우다': 1281,
 '가다 발전': 16,
 '점점 줄어들다': 1865,
 '이다 미래': 1604,
 '밖에 없다': 850,
 '먹다 살다': 758,
 '대상': 508,
 '박살': 846,
 '박살 나다': 847,
 '이건': 1590,
 '절대': 1855,
 '갈수': 49,
 '전문성': 1843,
 '상관없다': 1099,
 '집약': 2038,
 '노동 집약': 417,
 '업무 가다': 1425,
 '가다 대체': 14,
 '어쩌면': 1410,
 '저출산': 1820,
 '축복': 2096,
 '미래 보다': 821,
 '전만': 1837,
 '비교': 1000,
 '문화': 807,
 '재무': 1811,
 '세무': 1152,
 '취업 너무': 2109,
 '안심': 1360,
 '전문직 자격증': 1846,
 '가속': 32,
 '물리': 809,
 '업종': 1429,
 '불경기': 986,
 '애초': 1387,
 '안함': 1365,
 '건설': 109,
 '만나다': 715,
 '최대': 2091,
 '매출': 751,
 '빠지다': 1012,
 '곳도': 172,
 '작년': 1791,
 '까지는': 326,
 '좋다': 1912,
 '경기': 136,
 '년내': 400,
 '지금 진짜': 1963,
 '많이 변하다': 735,
 '일인': 1726,
 '자영': 1782,
 '업자': 1428,
 '새벽': 1112,
 '능력': 457,
 '똑똑하다': 666,
 '젊은이': 1861,
 '이지': 1662,
 '마음': 707,
 '가지': 41,
 '자영 업자': 1783,
 '능력 안되다': 458,
 '이지 않다': 1663,
 '않다 마음': 1372,
 '인구': 1686,
 '출산율': 2100,
 '높다': 435,
 '경쟁': 148,
 '지옥': 1983,
 '모르다 사람': 782,
 '사람 없다': 1054,
 '졸업생': 1910,
 '자녀': 1751,
 '수학': 1207,
 '사용': 1078,
 '직업 많이': 2000,
 '취업 힘들다': 2117,
 '이렇다': 1629,
 '어떻다 이렇다': 1399,
 '본인': 965,
 '싶다': 1299,
 '뉴스': 445,
 '이네': 1599,
 '뉴스 보고': 446,
 '밥그릇': 869,
 '출생': 2101,
 '자연': 1780,
 '선택': 1141,
 '결정': 132,
 '미래 없다': 822,
 '지나다': 1966,
 '가야': 33,
 '아무': 1337,
 '소용없다': 1174,
 '공부 하고': 188,
 '아무 소용없다': 1338,
 '거대하다': 87,
 '소용': 1173,
 '읽다': 1734,
 '거대하다 흐름': 88,
 '의사': 1578,
 '수술': 1194,
 '검사': 115,
 '결과': 129,
 '보여주다': 946,
 '설명': 1145,
 '이해도': 1670,
 '병원': 920,
 '대화': 544,
 '문장': 800,
 '여서': 1474,
 '질문': 2036,
 '의사 수술': 1583,
 '너무 자다': 390,
 '붙다': 993,
 '지키다': 1987,
 '밥그릇 지키다': 871,
 '이제 뽑다': 1658,
 '택배': 2170,
 '기사': 301,
 '택배 기사': 2171,
 '써다 되다': 1306,
 '남일': 367,
 '남일 않다': 368,
 '마음 아프다': 708,
 '오픈': 1508,
 '회계사 변호사': 2384,
 '변호사 세무사': 911,
 '세무사 분들': 1156,
 '에이': 1467,
 '오류': 1505,
 '확인': 2356,
 '다시 확인': 473,
 '두다': 624,
 '자격증 따다': 1743,
 '농사': 432,
 '농사 이다': 433,
 '도장': 565,
 '일도': 1716,
 '회계사 도장': 2377,
 '도장 받다': 566,
 '받다 야하다': 861,
 '큰일': 2156,
 '큰일 이네': 2157,
 '법인': 898,
 '전체': 1848,
 '무조건': 796,
 '회계법인': 2368,
 '스카이': 1226,
 '상경': 1098,
 '엘리트': 1472,
 '들어가다': 630,
 '근데 회계사': 278,
 '회계사 시험': 2389,
 '시험 합격': 1268,
 '로봇': 686,
 '치료': 2122,
 '산업': 1086,
 '똑같다': 663,
 '금융': 283,
 '테크': 2174,
 '그나마': 252,
 '의료': 1575,
 '만에': 721,
 '년대': 401,
 '이라도': 1621,
 '자리': 1767,
 '채용 박살': 2058,
 '신입 자리': 1279,
 '직업 없다': 2006,
 '미리': 825,
 '알아보다': 1381,
 '책상': 2062,
 '머리': 753,
 '책상 머리': 2063,
 '없어지다 인간': 1452,
 '전공자': 1831,
 '지향': 1990,
 '전환': 1853,
 '미래 지향': 824,
 '가장 먼저': 35,
 '세무사 회계사': 1158,
 '회계사 없어지다': 2393,
 '나은': 355,
 '걱정 되다': 98,
 '줄이다': 1935,
 '수임료': 1204,
 '낮추다': 373,
 '회계사 줄이다': 2398,
 '줄이다 아니다': 1938,
 '공기업': 178,
 '당분간': 494,
 '컴공 나오다': 2139,
 '투자': 2182,
 '얻다': 1420,
 '결과물': 130,
 '의미': 1576,
 '힘드다 세상': 2428,
 '세상 이네': 1166,
 '인게': 1683,
 '면접': 767,
 '용도': 1534,
 '낮다': 371,
 '지원': 1984,
 '고등학교': 164,
 '졸업': 1908,
 '이용': 1648,
 '화하다': 2353,
 '뽑히다': 1032,
 '실제': 1287,
 '카이스트 출신': 2132,
 '고등학교 졸업': 165,
 '졸업 하고': 1909,
 '공대': 179,
 '작살': 1793,
 '컴공 전공자': 2140,
 '확실하다': 2355,
 '기업': 310,
 '주가': 1918,
 '거품': 96,
 '끼다': 336,
 '생산': 1125,
 '향상': 2319,
 '도움': 561,
 '는걸': 450,
 '기업 이나': 312,
 '이라 는걸': 1616,
 '최고': 2088,
 '배관': 877,
 '대세': 509,
 '대세 되다': 510,
 '황병찬': 2362,
 '잘리다': 1799,
 '회계사 하고': 2403,
 '없다 신입': 1440,
 '신입 많이': 1277,
 '뽑다 되다': 1026,
 '중개사': 1942,
 '취급': 2105,
 '공인 중개사': 194,
 '지금 회계사': 1964,
 '걱정 아니다': 99,
 '디자이너': 638,
 '아이티': 1347,
 '망하다': 744,
 '오래': 1504,
 '다해': 476,
 '정치': 1885,
 '보이다': 948,
 '자료': 1763,
 '모으다': 785,
 '정리': 1873,
 '변호사 회계사': 915,
 '일반인': 1718,
 '의존': 1588,
 '분야': 982,
 '영향': 1494,
 '숫자 관련': 1214,
 '모든 분야': 774,
 '영향 받다': 1495,
 '사다': 1037,
 '핑계': 2245,
 '자수': 1775,
 '욕심': 1533,
 '대가리': 498,
 '부리고': 970,
 '치우다': 2123,
 '아직': 1349,
 '거들다': 89,
 '현직 회계': 2340,
 '회계 사다': 2364,
 '늘다 핑계': 452,
 '수요 예측': 1201,
 '하고 회계사': 2254,
 '합격 자수': 2291,
 '갈아 치우다': 52,
 '화장품': 2352,
 '사업': 1076,
 '필요하다': 2241,
 '만들다': 716,
 '활용': 2360,
 '번역': 888,
 '통역': 2176,
 '공부 취업': 187,
 '취업 않다': 2113,
 '뜨다': 670,
 '들어서다': 634,
 '이렇다 시대': 1632,
 '의미 없다': 1577,
 '자극': 1749,
 '세금': 1148,
 '어쩌': 1406,
 '많아지다': 732,
 '근대': 276,
 '자꾸': 1750,
 '낳다': 374,
 '몰다': 788,
 '사람 필요없다': 1061,
 '기도': 296,
 '속도 인간': 1178,
 '우려': 1536,
 '현실 이다': 2332,
 '발달': 864,
 '완전하다': 1519,
 '바뀌다': 836,
 '아이디어': 1346,
 '커지다': 2136,
 '숙련': 1209,
 '기술 발달': 305,
 '자체 없어지다': 1788,
 '스스로': 1224,
 '스스로 필요없다': 1225,
 '먹히다': 760,
 '소프트웨어': 1176,
 '심다': 1294,
 '게임': 123,
 '만이': 725,
 '문제 아니다': 804,
 '좋다 사람': 1914,
 '사람 뽑다': 1048,
 '정신차리다': 1880,
 '보내다': 926,
 '만의': 724,
 '배우다': 880,
 '기술 배우다': 307,
 '완전': 1517,
 '아주': 1348,
 '장난': 1806,
 '넘다': 395,
 '건가': 106,
 '제대로': 1891,
 '자만': 1771,
 '다시 시작': 472,
 '차지': 2048,
 '후배': 2415,
 '자리 차지': 1770,
 '차지 하고': 2049,
 '계약': 159,
 ...}

In [22]:
tfidf_vectorizer.get_feature_names_out()

array(['가가', '가격', '가격 후려치다', ..., '힘드다 세상', '힘들다', '힘쓰다'],
      shape=(2431,), dtype=object)

In [23]:
import pandas as pd
vocab = sorted(tfidf_vectorizer.vocabulary_.items(),key=lambda x : x[1])
vocab_df = pd.DataFrame(vocab,columns=['word','index'])

In [24]:
vocab_df

         word  index
0          가가      0
1          가격      1
2     가격 후려치다      2
3          가공      3
4         가깝다      4
...       ...    ...
2426      힘드다   2426
2427   힘드다 맞다   2427
2428   힘드다 세상   2428
2429      힘들다   2429
2430      힘쓰다   2430

[2431 rows x 2 columns]

In [41]:
comment_vecs.toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.21173738,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]], shape=(1146, 2431))

In [26]:
pd.DataFrame(comment_vecs.toarray(),columns=tfidf_vectorizer.get_feature_names_out())

,가가,가격,가격 후려치다,가공,가깝다,가끔,가능,가능성,가능하다,가능하다 공장,...,흘러가다,희망,희생,희생 강요,힘내다,힘드다,힘드다 맞다,힘드다 세상,힘들다,힘쓰다
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.211737,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1141,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.173453,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
1142,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.445331,0.0,0.0,0.000000,0.0
1143,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
1144,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.388807,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
1145,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0

In [27]:
from sklearn.cluster import KMeans

kmeans = KMeans(
    n_clusters=2,
    max_iter=5000,
    random_state=0
)

news_label = kmeans.fit_predict(comment_vecs)

In [28]:
center = kmeans.cluster_centers_
center_arg_idx = center.argsort()[::-1]
idx_top_20 = center_arg_idx[:,:20]
feature_names = tfidf_vectorizer.get_feature_names_out()
feature_names[idx_top_20]

array([['가다 발전', '회사 경리', '회사 다니다', '회식', '가다 아니다', '가다 인간', '가다 정확하다',
        '가다 진짜', '가도', '가라', '가면', '힘드다 세상', '희생', '가속', '흐름', '희생 강요',
        '회계사 보다는', '가야', '힘내다', '가장 크다'],
       ['숫자 놀이', '대체 가능하다', '의사 변호사', '의사 대체', '대체 없다', '대체 직업',
        '대체 시급하다', '대체 되어다', '되다 대체', '직업 이라는', '처방', '대체 가능', '늦다 대체',
        '시대 대체', '완벽하다 대체', '되다 미래', '완전 대체', '직업 대체', '직업 대부분', '직업 의사']],
      dtype=object)

In [ ]:
df = pd.DataFrame(preprocessed_sentences,columns=['댓글'])
df['label'] = kmeans.fit_predict(comment_vecs)

                                                   댓글  label
0                      공인 회계사 최종 합격자 카이스트 컴공 취업 걱정 세상      0
1     카이스트 물리학 컴공 복수 전공 분 때문 취업 쉬다 않다 대학 출신 힘들다 상상 알다      0
2   다 들다 멀다 이야기 라고 생각 지금 만 보다 재연 대역 배우 아니다 그냥 영상 다...      0
3                 회계사 대체 되다 정도 면 이미 컴퓨터 앉다 대부분 사무직 전멸      1
4                앞 살아가다 내 자식 청년 미래 너무 불투명하다 안타깝다 서글프다      0
5                         걸치다 버스안내양 합격 자동 문 나오다 버리다 꼴      0
6                                     숫자 다루다 업무 특히 가다      0
7   개발 자다 그냥 기 도합 니 다 제발 기술 공리 행복 증진 방향 발전 되다 기르다 ...      0
8                    정말 어렵다 시험 인데 그걸 따다 백수 라니 너무 안타깝다      0
9         유튜브 회계사 합격 하고 가족 울면 서 전화하다 합격자 상보 니 진짜 허무하다      0
10  문과 사무직 인데 불과 전 만해 주변 퇴사 하고 코딩 교육 받다 개발자 재 취업 사...      0
11  합격 증 받다 저렇게 비닐 싸다 보관 정도 면 그만큼 진심 이고 그만큼 인생 중요하...      0
12     공인 회계사 합격 갈아 넣다 자격증 땃을텐데 세상 이렇게 변하다 버리다 너무 슬프다      0
13  대다 다니다 교수 님 왈 컴공 개발자 구인 구직 인문 학과 보다 더 떨어지다 상황 ...      0
14                     회계사 라고 오다 알 주다 직업 군 이다 너무 안타깝다      0
15  근데 내 가보 엔 지금 스펙 이고 나발 고간 취업 시장 자체 너무 좁다 그냥 취업 ...      0
16                              시대 예측 못 시대 너무 빠르다 아니다      0
17             이미 전망 없다 직업 청춘 바치다 편견 버리다 다양하다 직업 도전 함      0
18  회사 경리 회계 더존 프로그램 처음 나오다 경리 부 직원 많이 짤렸 지 분개 기장 ...      0
19                                 뭐 먹고살다 진짜 먹고살다 힘드다      0
20                            본질 컴퓨터 앞 앉다 다 대체 되다 거 다      1
21          제일 먼저 없어지다 무방 하고 대체 되다 바라다 직업 대한민국 판사 들이다      1
22                       상중 간 에도 미나 광고 나오다 시 대의 흐름 이다      0
23                   인터뷰 찍다 카메라 에도 탑재 되다 전문 카메라맨 사라지다      0
24                                필요없다 공부 너무 많다 인원 뽑다      0
25         옛날 은행원 회계사 세무사 변호사 없어지다 직업 이라고 점점 희미하다 정말로      0
26                                 회계사 세무사 진짜 이제 답 없다      0
27                                    세상 변화 속도 너무 빠르다      0
28                             앞 으로는 주니어 이다 중간 급 사라지다      0
29                               헐다 심하다 추적 분 나오다 정도 니      0
30                                        노력 배신 대가 오다      0
31           검수 고 인물 능력자 빼다 신규 중간 관리자 안 뽑다 미국 피 바람 불다      0
32                           병찬 이제 짬 안전하다 사다리 걷어차다 보다      0
33               과거 자의 의하다 취업 유예 이다 지금 타의 의하다 취업 절벽 죠      0
34                      진짜 서글프다 세 상이 요 힘드다 시험 인데 허망 요      0
35                                         차다 서글프다 노력      0
36                                회계 더 안타깝다 적용 더 간단하다      0
37  전 쯤 미래 대체 되다 직업 이라는 리스트 보고 친구 랑 이야기 한적 그게 진짜 현...      1
38         출장 다니다 서버 구축 하고 부품 고치다 유지 보수 엔지니어 입 풀칠 겁니다      0
39                                      세상 진짜 빠르다 변하다      0
40  재무관리 경영학 경제학 시험 보다 쓸데없이 난이도 높이다 수험생 괴롭히다 시험 시험...      0
41  모든 사무 직종 때문 어시 더 빨리 더 깔끔하다 처리 해주다 실무 결 정권 입장 어...      0
42  차다 인생 알 수 없다 게 전 용산 밥 먹다 옆 테이블 삼일 회계사 회식 중 더 라...      0
43                                      좌우 국회의원 대체 되다      1
44                   아마 많다 취준생들 거 라고 봄 너무 밝다 얘기 더 슬프다      0
45                    창 근 님 대표 님 칭찬 주 니까 허리 펴다 모습 귀엽다      0
46                                     협회 지금 자격증 장사 중      0
47  원래 대 전 환기 에는 당연하다 발생 일이 잖다 스마트폰 나오니 삐삐 공장 파산하다...      0
48  때문 신입 취업 어렵다 아우성치다 정작 들어오다 없다 못 더 심해지다 요즘 엔 레포...      0
49                                날 갈수록 미치다 초면 끝나다 세상      0

In [46]:
from sklearn.metrics.pairwise import cosine_similarity

base_idx = 214
baseline_vector = comment_vecs[base_idx]
baseline_vector

similarities = cosine_similarity(comment_vecs, baseline_vector).flatten()

df['base_similarity'] = similarities
print(df.iloc[base_idx])

댓글                 그대 성실하다 인정
label                       0
base_similarity           1.0
Name: 214, dtype: object

In [48]:
df.sort_values(by='base_similarity',ascending=False)

,댓글,label,base_similarity
214,그대 성실하다 인정,0,1.000000
431,회계사 경리 처럼 단 순 업무 만 않다 예전 유명 가수 분 세금 문제 관련 오다 여...,0,0.286883
59,현실 빨리 수긍 게 생존 유리하다 내 여태 열심히 해오다 현실 인정 해주다 않다 걸...,0,0.262877
240,백이 라도 벌다 기업 이나 미래 산업 투자 죽음 나선 벗어나다 랑 싸우다 안되다 거...,0,0.232214
421,시대 흐름 이라 어쩔 수가 없다 디지털 카메라 나오다 사진관 개업 사람 누가 지금 ...,0,0.206319
...,...,...,...
1125,아무리 영향 받다 들다 사회 적 위치 소득 여전하다 상위 권 이고 변하다 않다 가다...,0,0.000000
1126,아이티 공부 해 라 가다 미래 다,0,0.000000
1127,내 친척 동생 카이스트 석사 나오다 개발자 초봉 연봉 받다 지방 대 나오다 회사 다...,0,0.000000
1128,난 다행하다 외모 보다 직종 이라 랑 관련 없다,0,0.000000
25,옛날 은행원 회계사 세무사 변호사 없어지다 직업 이라고 점점 희미하다 정말로,0,0.000000