# BoW 기반 텍스트 분석 연습

1. 적절한 데이터셋을 찾거나 생성하고, 적절한 전처리를 진행한다. (01_preprocessing.ipynb)
2. TF-IDF Vectorizer를 이용하여 벡터화한다.
3. Cosine Similarity를 계산하여 입력된 문자열의 긍/부정을 판단한다.

In [27]:
import pandas as pd
df = pd.read_csv('실습_전처리.csv',encoding='utf-8')
df = df.dropna()
preprocessed_sentences = df.values.flatten()
preprocessed_sentences

array(['공인 회계사 최종 합격자 카이스트 컴공 취업 걱정 세상',
       '카이스트 물리학 컴공 복수 전공 분 때문 취업 쉬다 않다 대학 출신 힘들다 상상 알다',
       '다 들다 멀다 이야기 라고 생각 지금 만 보다 재연 대역 배우 아니다 그냥 영상 다 대체 하고 벌써 시작 하고',
       ...,
       '나이 어리다 나오다 애 위주 대 법인 선호 이나 공부 하고 나이 듣보잡 대학 나오다 빅펌 못 그게 현실 이지 가다 원인 아니다',
       '시 대 다시 대 흐름 흘러가다 되다 생각 좋다 변화 뒤 처지 면 그냥 걸 끝 이야 알 알다 외면',
       '근데 입장 바꾸다 나라 안 뽑다 딸 깍 방이 면 다 되다 어떻다 정신 나가다 사람 뽑다'],
      shape=(1137,), dtype=object)

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer(
    ngram_range=(1,2),
    max_df=1.0,
    min_df=2
)

comment_vecs = tfidf_vectorizer.fit_transform(preprocessed_sentences)

In [29]:
comment_vecs

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 14517 stored elements and shape (1137, 2431)>

In [30]:
tfidf_vectorizer.vocabulary_

{'공인': 192,
 '회계사': 2369,
 '최종': 2093,
 '합격자': 2294,
 '카이스트': 2129,
 '컴공': 2138,
 '취업': 2107,
 '걱정': 97,
 '세상': 1160,
 '공인 회계사': 195,
 '카이스트 컴공': 2133,
 '컴공 취업': 2141,
 '취업 걱정': 2108,
 '물리학': 810,
 '복수': 960,
 '전공': 1830,
 '때문': 649,
 '쉬다': 1217,
 '않다': 1370,
 '대학': 537,
 '출신': 2102,
 '힘들다': 2429,
 '상상': 1104,
 '알다': 1377,
 '카이스트 물리학': 2130,
 '쉬다 않다': 1218,
 '들다': 628,
 '멀다': 765,
 '이야기': 1646,
 '라고': 671,
 '생각': 1113,
 '지금': 1955,
 '보다': 927,
 '배우': 879,
 '아니다': 1322,
 '그냥': 254,
 '영상': 1488,
 '대체': 521,
 '하고': 2246,
 '벌써': 890,
 '시작': 1256,
 '라고 생각': 672,
 '아니다 그냥': 1324,
 '대체 하고': 533,
 '시작 하고': 1258,
 '되다': 584,
 '정도': 1870,
 '이미': 1640,
 '컴퓨터': 2142,
 '앉다': 1367,
 '대부분': 506,
 '사무직': 1070,
 '전멸': 1839,
 '회계사 대체': 2376,
 '대체 되다': 525,
 '컴퓨터 앉다': 2143,
 '살아가다': 1096,
 '자식': 1776,
 '청년': 2079,
 '미래': 820,
 '너무': 385,
 '불투명하다': 991,
 '안타깝다': 1364,
 '서글프다': 1131,
 '걸치다': 114,
 '합격': 2287,
 '자동': 1759,
 '나오다': 353,
 '버리다': 883,
 '숫자': 1213,
 '다루다': 467,
 '업무': 1424,
 '특히': 2189,
 '가다': 10,
 '숫자 다루다': 1216,
 '특히 가다': 2190,
 '개발': 74,
 '자다': 1752,
 '도합': 570,
 '제발': 1894,
 '기술': 304,
 '행복': 2314,
 '방향': 876,
 '발전': 867,
 '개인': 83,
 '발버둥치다': 865,
 '대비': 507,
 '거나': 86,
 '바꾸다': 835,
 '수준': 1205,
 '전기': 1832,
 '수준 아니다': 1206,
 '정말': 1874,
 '어렵다': 1402,
 '시험': 1263,
 '인데': 1689,
 '그걸': 248,
 '따다': 641,
 '백수': 881,
 '시험 인데': 1266,
 '인데 그걸': 1690,
 '너무 안타깝다': 389,
 '유튜브': 1559,
 '가족': 40,
 '상보': 1103,
 '진짜': 2028,
 '허무하다': 2324,
 '회계사 합격': 2405,
 '합격 하고': 2293,
 '문과': 797,
 '불과': 987,
 '만해': 728,
 '주변': 1923,
 '퇴사': 2180,
 '코딩': 2146,
 '교육': 220,
 '받다': 858,
 '개발자': 76,
 '사람': 1044,
 '시장': 1259,
 '이렇게': 1627,
 '무너지다': 790,
 '사무직 인데': 1073,
 '코딩 교육': 2148,
 '교육 받다': 221,
 '개발자 취업': 79,
 '취업 사람': 2110,
 '저렇게': 1819,
 '싸다': 1301,
 '그만큼': 275,
 '진심': 2026,
 '이고': 1591,
 '인생': 1703,
 '중요하다': 1949,
 '순간': 1210,
 '이라고': 1617,
 '타이밍': 2165,
 '안좋다': 1363,
 '인공': 1684,
 '지능': 1970,
 '충분하다': 2103,
 '대신': 511,
 '지경': 1954,
 '누가': 439,
 '이라고 생각': 1619,
 '인공 지능': 1685,
 '누가 알다': 440,
 '갈아': 51,
 '넣다': 398,
 '자격증': 1742,
 '변하다': 904,
 '슬프다': 1231,
 '대다': 502,
 '다니다': 466,
 '교수': 219,
 '구인': 225,
 '구직': 228,
 '인문': 1701,
 '학과': 2265,
 '떨어지다': 660,
 '상황': 1109,
 '이르다': 1636,
 '갑자기': 60,
 '세상 변하다': 1162,
 '오다': 1502,
 '주다': 1921,
 '직업': 1993,
 '이다': 1602,
 '회계사 라고': 2380,
 '직업 이다': 2009,
 '근데': 277,
 '스펙': 1230,
 '나발': 349,
 '자체': 1787,
 '좁다': 1911,
 '힘드다': 2426,
 '맞다': 745,
 '취업 시장': 2111,
 '너무 좁다': 391,
 '취업 힘드다': 2116,
 '힘드다 맞다': 2427,
 '시대': 1238,
 '예측': 1499,
 '빠르다': 1009,
 '시대 너무': 1240,
 '너무 빠르다': 388,
 '전망': 1838,
 '없다': 1430,
 '바치다': 843,
 '편견': 2209,
 '다양하다': 474,
 '도전': 567,
 '없다 직업': 1445,
 '편견 버리다': 2210,
 '회사': 2407,
 '경리': 143,
 '회계': 2363,
 '더존': 548,
 '프로그램': 2227,
 '처음': 2074,
 '직원': 2015,
 '많이': 733,
 '기장': 315,
 '신입': 1276,
 '사원': 1079,
 '일이': 1724,
 '획기': 2411,
 '사건': 1034,
 '회사 경리': 2408,
 '처음 나오다': 2075,
 '먹고살다': 756,
 '본질': 966,
 '제일': 1896,
 '먼저': 761,
 '없어지다': 1449,
 '바라다': 838,
 '대한민국': 541,
 '판사': 2200,
 '들이다': 636,
 '제일 먼저': 1897,
 '먼저 없어지다': 764,
 '에도': 1460,
 '미나': 818,
 '광고': 214,
 '대의': 515,
 '흐름': 2417,
 '대의 흐름': 516,
 '흐름 이다': 2419,
 '인터뷰': 1712,
 '찍다': 2043,
 '카메라': 2128,
 '전문': 1841,
 '사라지다': 1039,
 '필요없다': 2240,
 '공부': 183,
 '많다': 730,
 '인원': 1705,
 '뽑다': 1022,
 '너무 많다': 386,
 '옛날': 1501,
 '은행원': 1569,
 '세무사': 1153,
 '변호사': 908,
 '점점': 1863,
 '정말로': 1875,
 '회계사 세무사': 2387,
 '세무사 변호사': 1155,
 '변호사 없어지다': 913,
 '없어지다 직업': 1453,
 '직업 이라고': 2010,
 '이제': 1656,
 '변화': 916,
 '속도': 1177,
 '세상 변화': 1163,
 '으로는': 1563,
 '주니어': 1919,
 '중간': 1941,
 '헐다': 2325,
 '심하다': 1295,
 '노력': 422,
 '대가': 497,
 '검수': 117,
 '인물': 1702,
 '능력자': 459,
 '빼다': 1019,
 '신규': 1271,
 '관리자': 211,
 '미국': 817,
 '바람': 840,
 '불다': 988,
 '병찬': 921,
 '안전하다': 1361,
 '사다리': 1038,
 '과거': 199,
 '자의': 1786,
 '의하다': 1589,
 '유예': 1556,
 '타의': 2164,
 '이다 지금': 1609,
 '상이': 1107,
 '허망': 2323,
 '차다': 2046,
 '적용': 1826,
 '간단하다': 45,
 '이라는': 1620,
 '보고': 922,
 '친구': 2124,
 '그게': 251,
 '현실': 2329,
 '돼다': 581,
 '되다 직업': 614,
 '직업 이라는': 2011,
 '현실 돼다': 2330,
 '구축': 229,
 '고치다': 170,
 '유지': 1558,
 '보수': 944,
 '엔지니어': 1470,
 '풀칠': 2224,
 '겁니다': 121,
 '진짜 빠르다': 2030,
 '빠르다 변하다': 1011,
 '난이도': 362,
 '높이다': 437,
 '수험생': 1208,
 '가치': 43,
 '평가': 2213,
 '되어다': 621,
 '시험 보다': 1265,
 '모든': 772,
 '사무': 1068,
 '직종': 2019,
 '빨리': 1014,
 '깔끔하다': 329,
 '처리': 2069,
 '해주다': 2310,
 '실무': 1284,
 '정권': 1868,
 '입장': 1738,
 '필요': 2236,
 '사무 직종': 1069,
 '필요 없어지다': 2239,
 '먹다': 757,
 '회식': 2410,
 '아마': 1335,
 '나이': 357,
 '이야': 1645,
 '젊다': 1857,
 '입사': 1737,
 '지다': 1972,
 '기다': 295,
 '방이': 875,
 '달라지다': 491,
 '심해지다': 1297,
 '어떻다': 1397,
 '모르다': 780,
 '거지': 94,
 '나다': 342,
 '살아나다': 1097,
 '위해': 1548,
 '고민': 166,
 '중이': 1950,
 '어떻다 되다': 1398,
 '좌우': 1917,
 '국회의원': 236,
 '밝다': 868,
 '얘기': 1394,
 '대표': 536,
 '니까': 462,
 '협회': 2342,
 '장사': 1809,
 '원래': 1540,
 '환기': 2358,
 '에는': 1458,
 '당연하다': 495,
 '발생': 866,
 '잖다': 1797,
 '스마트폰': 1223,
 '나오니': 352,
 '공장': 196,
 '파산하다': 2192,
 '전문직': 1844,
 '어쩔': 1411,
 '에는 당연하다': 1459,
 '정작': 1883,
 '들어오다': 635,
 '요즘': 1532,
 '내다': 379,
 '신입 취업': 1280,
 '갈수록': 50,
 '미치다': 829,
 '초면': 2085,
 '끝나다': 334,
 '예전': 1498,
 '학교': 2266,
 '이라': 1615,
 '엄청': 1421,
 '유망': 1554,
 '해보다': 2305,
 '실화': 1291,
 '없어지다 직종': 1454,
 '직종 이라': 2022,
 '쓸모없다': 1319,
 '소장': 1175,
 '써주다': 1308,
 '대충': 534,
 '쓰다': 1310,
 '법무사': 897,
 '신고': 1270,
 '보급': 924,
 '야하다': 1389,
 '비싸다': 1003,
 '세무사 법무사': 1154,
 '우리나라': 1537,
 '노동': 416,
 '국가': 230,
 '에서는': 1463,
 '그렇다': 264,
 '고용': 168,
 '해고': 2300,
 '리스크': 702,
 '크다': 2154,
 '사실': 1074,
 '외면': 1525,
 '고용 해고': 169,
 '리스크 크다': 703,
 '가장': 34,
 '일자리': 1728,
 '컴퓨터 직업': 2144,
 '위기': 1546,
 '사람 위기': 1055,
 '아프다': 1352,
 '말다': 741,
 '열심히': 1486,
 '평생': 2214,
 '벌다': 889,
 '잇다': 1740,
 '직장': 2016,
 '사이': 1080,
 '열심히 공부': 1487,
 '따다 자격증': 643,
 '생존': 1127,
 '유리하다': 1553,
 '해오다': 2308,
 '인정': 1708,
 '적응하다': 1829,
 '죽음': 1930,
 '빨리 적응하다': 1017,
 '부모': 971,
 '키우다': 2159,
 '아니다 세상': 1328,
 '인재': 1707,
 '해도': 2302,
 '힘내다': 2425,
 '합격 정도': 2292,
 '변호사 판사': 914,
 '앉다 컴퓨터': 1368,
 '사라지다 보다': 1041,
 '어떻': 1396,
 '초딩': 2084,
 '막막하다': 714,
 '사회': 1083,
 '출산': 2099,
 '장래': 1807,
 '암울하다': 1383,
 '대책': 517,
 '마련': 705,
 '대책 마련': 518,
 '미지': 827,
 '정은': 1882,
 '역사': 1476,
 '길다': 324,
 '호황': 2346,
 '회계사 미지': 2382,
 '미지 정은': 828,
 '시대 에도': 1248,
 '어마': 1404,
 '무시': 793,
 '회계사 진짜': 2399,
 '해외': 2309,
 '인턴': 1713,
 '이나': 1596,
 '되게': 583,
 '적다': 1821,
 '고함': 171,
 '적다 받다': 1822,
 '복전': 962,
 '캠프': 2135,
 '다시': 470,
 '군데': 237,
 '스타트업': 1229,
 '취업 캠프': 2115,
 '일반': 1717,
 '인지': 1710,
 '전문직 정도': 1847,
 '무섭다': 791,
 '무섭다 세상': 792,
 '하자': 2264,
 '없애다': 1448,
 '국민': 233,
 '뿌리다': 1033,
 '나중': 359,
 '가면': 30,
 '아예': 1343,
 '인간': 1675,
 '채용': 2057,
 '타격': 2161,
 '입다': 1736,
 '년전': 408,
 '몇개': 770,
 '프로그래머': 2226,
 '연차': 1483,
 '쌓이다': 1304,
 '거기': 85,
 '인거': 1680,
 '이후': 1671,
 '분들': 979,
 '붙이다': 995,
 '년전 코딩': 409,
 '연차 쌓이다': 1484,
 '그니까': 257,
 '시니어': 1234,
 '끼리': 337,
 '다르다': 468,
 '한테': 2282,
 '심각하다': 1293,
 '진짜 심각하다': 2031,
 '화이트칼라': 2350,
 '인하다': 1715,
 '블루': 996,
 '칼라': 2134,
 '중국': 1945,
 '저가': 1815,
 '덤핑': 551,
 '문제': 801,
 '대체 걱정': 524,
 '블루 칼라': 997,
 '학벌': 2269,
 '수요': 1199,
 '공급': 176,
 '돌리다': 572,
 '현재': 2336,
 '근무': 281,
 '기고': 291,
 '연봉': 1480,
 '지급': 1965,
 '이유': 1649,
 '상담': 1100,
 '줍다': 1940,
 '유료': 1552,
 '만원': 722,
 '회계사 필요': 2401,
 '많이 뽑다': 737,
 '뽑다 회계사': 1031,
 '회계사 학벌': 2404,
 '보다 회계사': 941,
 '회계사 뽑다': 2386,
 '수요 보다': 1200,
 '보다 공급': 929,
 '공급 많다': 177,
 '신입 뽑다': 1278,
 '뽑다 뽑다': 1027,
 '뽑다 이유': 1029,
 '이유 없다': 1650,
 '망중': 743,
 '회계사 걱정': 2372,
 '자르다': 1766,
 '아버지': 1341,
 '수습': 1195,
 '기간': 286,
 '수습 기간': 1196,
 '예상': 1497,
 '역시': 1477,
 '어려워지다': 1401,
 '걱정 이다': 103,
 '프로': 2225,
 '되다 현실': 617,
 '취득': 2106,
 '회계사 자격증': 2396,
 '자격증 취득': 1747,
 '솔직하다': 1179,
 '경력': 138,
 '쓸다': 1314,
 '된거': 623,
 '취직': 2118,
 '똑같이': 665,
 '이력서': 1633,
 '개다': 71,
 '안되다': 1356,
 '지금 경력': 1956,
 '경력 회계사': 142,
 '지금 시대': 1961,
 '이력서 개다': 1634,
 '느끼다': 448,
 '라서': 677,
 '이상하다': 1642,
 '로만': 684,
 '늘다': 451,
 '빨리 변하다': 1016,
 '이다 사람': 1605,
 '라는': 673,
 '분명': 980,
 '억울하다': 1415,
 '행위': 2316,
 '대해': 542,
 '피해': 2234,
 '그로': 270,
 '남다': 363,
 '피해자': 2235,
 '대로': 505,
 '판결': 2196,
 '사망': 1067,
 '이러하다': 1626,
 '형량': 2343,
 '생명': 1124,
 '판사 대체': 2202,
 '판사 사람': 2205,
 '그로 인하다': 271,
 '사람 생명': 1052,
 '나라': 343,
 '제도': 1892,
 '처럼': 2067,
 '단계': 482,
 '기회': 321,
 '떨다': 659,
 '트리': 2186,
 '따라가다': 645,
 '시험 제도': 1267,
 '쓸다 없다': 1316,
 '시대 흐름': 1252,
 '흐름 따라가다': 2418,
 '일찍': 1732,
 '태어나다': 2168,
 '일찍 태어나다': 1733,
 '점점 없어지다': 1864,
 '대체 되어다': 526,
 '현직': 2338,
 '단순하다': 485,
 '자동화': 1761,
 '대한': 540,
 '감소': 56,
 '상태': 1108,
 '구조': 226,
 '초반': 2086,
 '내리막': 381,
 '관련': 207,
 '업계': 1423,
 '선발': 1135,
 '늘리다': 453,
 '효과': 2412,
 '치다': 2119,
 '현직 이다': 2339,
 '보다 영상': 934,
 '무시 하고': 794,
 '선발 인원': 1136,
 '공무원': 181,
 '인가': 1673,
 '몰리': 789,
 '년차': 410,
 '더욱': 547,
 '계속': 158,
 '학습': 2271,
 '내년': 377,
 '지금 년차': 1958,
 '년차 회계사': 412,
 '시니어 회계사': 1237,
 '회계사 업무': 2391,
 '산업혁명': 1087,
 '이니': 1600,
 '써다': 1305,
 '한다는': 2276,
 '코로나': 2149,
 '터지다': 2172,
 '시점': 1261,
 '프로젝트': 2228,
 '줄어들다': 1934,
 '한순간': 2278,
 '환경': 2357,
 '해먹': 2304,
 '느낌': 449,
 '밖에': 849,
 '살다': 1092,
 '산업혁명 이니': 1088,
 '신입 키우다': 1281,
 '가다 발전': 16,
 '점점 줄어들다': 1865,
 '이다 미래': 1604,
 '밖에 없다': 850,
 '먹다 살다': 758,
 '대상': 508,
 '박살': 846,
 '박살 나다': 847,
 '이건': 1590,
 '절대': 1855,
 '갈수': 49,
 '전문성': 1843,
 '상관없다': 1099,
 '집약': 2038,
 '노동 집약': 417,
 '업무 가다': 1425,
 '가다 대체': 14,
 '어쩌면': 1410,
 '저출산': 1820,
 '축복': 2096,
 '미래 보다': 821,
 '전만': 1837,
 '비교': 1000,
 '문화': 807,
 '재무': 1811,
 '세무': 1152,
 '취업 너무': 2109,
 '안심': 1360,
 '전문직 자격증': 1846,
 '가속': 32,
 '물리': 809,
 '업종': 1429,
 '불경기': 986,
 '애초': 1387,
 '안함': 1365,
 '건설': 109,
 '만나다': 715,
 '최대': 2091,
 '매출': 751,
 '빠지다': 1012,
 '곳도': 172,
 '작년': 1791,
 '까지는': 326,
 '좋다': 1912,
 '경기': 136,
 '년내': 400,
 '지금 진짜': 1963,
 '많이 변하다': 735,
 '일인': 1726,
 '자영': 1782,
 '업자': 1428,
 '새벽': 1112,
 '능력': 457,
 '똑똑하다': 666,
 '젊은이': 1861,
 '이지': 1662,
 '마음': 707,
 '가지': 41,
 '자영 업자': 1783,
 '능력 안되다': 458,
 '이지 않다': 1663,
 '않다 마음': 1372,
 '인구': 1686,
 '출산율': 2100,
 '높다': 435,
 '경쟁': 148,
 '지옥': 1983,
 '모르다 사람': 782,
 '사람 없다': 1054,
 '졸업생': 1910,
 '자녀': 1751,
 '수학': 1207,
 '사용': 1078,
 '직업 많이': 2000,
 '취업 힘들다': 2117,
 '이렇다': 1629,
 '어떻다 이렇다': 1399,
 '본인': 965,
 '싶다': 1299,
 '뉴스': 445,
 '이네': 1599,
 '뉴스 보고': 446,
 '밥그릇': 869,
 '출생': 2101,
 '자연': 1780,
 '선택': 1141,
 '결정': 132,
 '미래 없다': 822,
 '지나다': 1966,
 '가야': 33,
 '아무': 1337,
 '소용없다': 1174,
 '공부 하고': 188,
 '아무 소용없다': 1338,
 '거대하다': 87,
 '소용': 1173,
 '읽다': 1734,
 '거대하다 흐름': 88,
 '의사': 1578,
 '수술': 1194,
 '검사': 115,
 '결과': 129,
 '보여주다': 946,
 '설명': 1145,
 '이해도': 1670,
 '병원': 920,
 '대화': 544,
 '문장': 800,
 '여서': 1474,
 '질문': 2036,
 '의사 수술': 1583,
 '너무 자다': 390,
 '붙다': 993,
 '지키다': 1987,
 '밥그릇 지키다': 871,
 '이제 뽑다': 1658,
 '택배': 2170,
 '기사': 301,
 '택배 기사': 2171,
 '써다 되다': 1306,
 '남일': 367,
 '남일 않다': 368,
 '마음 아프다': 708,
 '오픈': 1508,
 '회계사 변호사': 2384,
 '변호사 세무사': 911,
 '세무사 분들': 1156,
 '에이': 1467,
 '오류': 1505,
 '확인': 2356,
 '다시 확인': 473,
 '두다': 624,
 '자격증 따다': 1743,
 '농사': 432,
 '농사 이다': 433,
 '도장': 565,
 '일도': 1716,
 '회계사 도장': 2377,
 '도장 받다': 566,
 '받다 야하다': 861,
 '큰일': 2156,
 '큰일 이네': 2157,
 '법인': 898,
 '전체': 1848,
 '무조건': 796,
 '회계법인': 2368,
 '스카이': 1226,
 '상경': 1098,
 '엘리트': 1472,
 '들어가다': 630,
 '근데 회계사': 278,
 '회계사 시험': 2389,
 '시험 합격': 1268,
 '로봇': 686,
 '치료': 2122,
 '산업': 1086,
 '똑같다': 663,
 '금융': 283,
 '테크': 2174,
 '그나마': 252,
 '의료': 1575,
 '만에': 721,
 '년대': 401,
 '이라도': 1621,
 '자리': 1767,
 '채용 박살': 2058,
 '신입 자리': 1279,
 '직업 없다': 2006,
 '미리': 825,
 '알아보다': 1381,
 '책상': 2062,
 '머리': 753,
 '책상 머리': 2063,
 '없어지다 인간': 1452,
 '전공자': 1831,
 '지향': 1990,
 '전환': 1853,
 '미래 지향': 824,
 '가장 먼저': 35,
 '세무사 회계사': 1158,
 '회계사 없어지다': 2393,
 '나은': 355,
 '걱정 되다': 98,
 '줄이다': 1935,
 '수임료': 1204,
 '낮추다': 373,
 '회계사 줄이다': 2398,
 '줄이다 아니다': 1938,
 '공기업': 178,
 '당분간': 494,
 '컴공 나오다': 2139,
 '투자': 2182,
 '얻다': 1420,
 '결과물': 130,
 '의미': 1576,
 '힘드다 세상': 2428,
 '세상 이네': 1166,
 '인게': 1683,
 '면접': 767,
 '용도': 1534,
 '낮다': 371,
 '지원': 1984,
 '고등학교': 164,
 '졸업': 1908,
 '이용': 1648,
 '화하다': 2353,
 '뽑히다': 1032,
 '실제': 1287,
 '카이스트 출신': 2132,
 '고등학교 졸업': 165,
 '졸업 하고': 1909,
 '공대': 179,
 '작살': 1793,
 '컴공 전공자': 2140,
 '확실하다': 2355,
 '기업': 310,
 '주가': 1918,
 '거품': 96,
 '끼다': 336,
 '생산': 1125,
 '향상': 2319,
 '도움': 561,
 '는걸': 450,
 '기업 이나': 312,
 '이라 는걸': 1616,
 '최고': 2088,
 '배관': 877,
 '대세': 509,
 '대세 되다': 510,
 '황병찬': 2362,
 '잘리다': 1799,
 '회계사 하고': 2403,
 '없다 신입': 1440,
 '신입 많이': 1277,
 '뽑다 되다': 1026,
 '중개사': 1942,
 '취급': 2105,
 '공인 중개사': 194,
 '지금 회계사': 1964,
 '걱정 아니다': 99,
 '디자이너': 638,
 '아이티': 1347,
 '망하다': 744,
 '오래': 1504,
 '다해': 476,
 '정치': 1885,
 '보이다': 948,
 '자료': 1763,
 '모으다': 785,
 '정리': 1873,
 '변호사 회계사': 915,
 '일반인': 1718,
 '의존': 1588,
 '분야': 982,
 '영향': 1494,
 '숫자 관련': 1214,
 '모든 분야': 774,
 '영향 받다': 1495,
 '사다': 1037,
 '핑계': 2245,
 '자수': 1775,
 '욕심': 1533,
 '대가리': 498,
 '부리고': 970,
 '치우다': 2123,
 '아직': 1349,
 '거들다': 89,
 '현직 회계': 2340,
 '회계 사다': 2364,
 '늘다 핑계': 452,
 '수요 예측': 1201,
 '하고 회계사': 2254,
 '합격 자수': 2291,
 '갈아 치우다': 52,
 '화장품': 2352,
 '사업': 1076,
 '필요하다': 2241,
 '만들다': 716,
 '활용': 2360,
 '번역': 888,
 '통역': 2176,
 '공부 취업': 187,
 '취업 않다': 2113,
 '뜨다': 670,
 '들어서다': 634,
 '이렇다 시대': 1632,
 '의미 없다': 1577,
 '자극': 1749,
 '세금': 1148,
 '어쩌': 1406,
 '많아지다': 732,
 '근대': 276,
 '자꾸': 1750,
 '낳다': 374,
 '몰다': 788,
 '사람 필요없다': 1061,
 '기도': 296,
 '속도 인간': 1178,
 '우려': 1536,
 '현실 이다': 2332,
 '발달': 864,
 '완전하다': 1519,
 '바뀌다': 836,
 '아이디어': 1346,
 '커지다': 2136,
 '숙련': 1209,
 '기술 발달': 305,
 '자체 없어지다': 1788,
 '스스로': 1224,
 '스스로 필요없다': 1225,
 '먹히다': 760,
 '소프트웨어': 1176,
 '심다': 1294,
 '게임': 123,
 '만이': 725,
 '문제 아니다': 804,
 '좋다 사람': 1914,
 '사람 뽑다': 1048,
 '정신차리다': 1880,
 '보내다': 926,
 '만의': 724,
 '배우다': 880,
 '기술 배우다': 307,
 '완전': 1517,
 '아주': 1348,
 '장난': 1806,
 '넘다': 395,
 '건가': 106,
 '제대로': 1891,
 '자만': 1771,
 '다시 시작': 472,
 '차지': 2048,
 '후배': 2415,
 '자리 차지': 1770,
 '차지 하고': 2049,
 '계약': 159,
 ...}

In [31]:
tfidf_vectorizer.get_feature_names_out()

array(['가가', '가격', '가격 후려치다', ..., '힘드다 세상', '힘들다', '힘쓰다'],
      shape=(2431,), dtype=object)

In [32]:
import pandas as pd
vocab = sorted(tfidf_vectorizer.vocabulary_.items(),key=lambda x : x[1])
vocab_df = pd.DataFrame(vocab,columns=['word','index'])

In [33]:
vocab_df

         word  index
0          가가      0
1          가격      1
2     가격 후려치다      2
3          가공      3
4         가깝다      4
...       ...    ...
2426      힘드다   2426
2427   힘드다 맞다   2427
2428   힘드다 세상   2428
2429      힘들다   2429
2430      힘쓰다   2430

[2431 rows x 2 columns]

In [34]:
pd.DataFrame(comment_vecs.toarray(),columns=tfidf_vectorizer.get_feature_names_out())

,가가,가격,가격 후려치다,가공,가깝다,가끔,가능,가능성,가능하다,가능하다 공장,...,흘러가다,희망,희생,희생 강요,힘내다,힘드다,힘드다 맞다,힘드다 세상,힘들다,힘쓰다
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.211677,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1132,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.173494,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
1133,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.445321,0.0,0.0,0.000000,0.0
1134,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
1135,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.388942,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0
1136,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0

In [35]:
from sklearn.cluster import KMeans

kmeans = KMeans(
    n_clusters=2,
    max_iter=5000,
    random_state=0
)

news_label = kmeans.fit_predict(comment_vecs)

In [36]:
center = kmeans.cluster_centers_
center_arg_idx = center.argsort()[:,::-1]
idx_top_20 = center_arg_idx[:,:40]
feature_names = tfidf_vectorizer.get_feature_names_out()
feature_names[idx_top_20]

array([['가다', '보다', '회계사', '되다', '없다', '이다', '아니다', '대체', '사람', '직업',
        '인간', '하고', '이제', '자다', '지금', '뽑다', '의사', '사라지다', '나오다', '가다 대체',
        '시험', '회계', '많다', '모르다', '업무', '문제', '쓰다', '세상', '로봇', '않다',
        '세무사', '변호사', '그렇다', '들다', '때문', '진짜', '필요하다', '늘다', '생각', '필요'],
       ['되다', '회계사', '대체', '없다', '사람', '시대', '직업', '아니다', '판사', '취업',
        '이다', '세상', '뽑다', '진짜', '자격증', '하고', '그냥', '이제', '않다', '걱정',
        '공부', '대체 되다', '없어지다', '오다', '개발자', '변호사', '그렇다', '지금', '너무',
        '많이', '살아나다', '인데', '들다', '생각', '세무사', '미래', '안되다', '나오다', '빨리',
        '정도']], dtype=object)

In [37]:
df = pd.DataFrame(preprocessed_sentences,columns=['댓글'])
df['label'] = kmeans.fit_predict(comment_vecs)

In [38]:
from sklearn.metrics.pairwise import cosine_similarity

base_idx = 214
baseline_vector = comment_vecs[base_idx]
baseline_vector

similarities = cosine_similarity(comment_vecs, baseline_vector).flatten()

df['base_similarity'] = similarities
print(df.iloc[base_idx])

댓글                 그대 성실하다 인정
label                       1
base_similarity           1.0
Name: 214, dtype: object

In [39]:
df.sort_values(by='base_similarity',ascending=False)

,댓글,label,base_similarity
214,그대 성실하다 인정,1,1.000000
429,회계사 경리 처럼 단 순 업무 만 않다 예전 유명 가수 분 세금 문제 관련 오다 여...,1,0.286941
59,현실 빨리 수긍 게 생존 유리하다 내 여태 열심히 해오다 현실 인정 해주다 않다 걸...,1,0.262910
240,백이 라도 벌다 기업 이나 미래 산업 투자 죽음 나선 벗어나다 랑 싸우다 안되다 거...,1,0.232235
420,시대 흐름 이라 어쩔 수가 없다 디지털 카메라 나오다 사진관 개업 사람 누가 지금 ...,1,0.206351
...,...,...,...
1116,아무리 영향 받다 들다 사회 적 위치 소득 여전하다 상위 권 이고 변하다 않다 가다...,1,0.000000
1117,아이티 공부 해 라 가다 미래 다,0,0.000000
1118,내 친척 동생 카이스트 석사 나오다 개발자 초봉 연봉 받다 지방 대 나오다 회사 다...,1,0.000000
1119,난 다행하다 외모 보다 직종 이라 랑 관련 없다,0,0.000000
0,공인 회계사 최종 합격자 카이스트 컴공 취업 걱정 세상,1,0.000000